INSERT INTO AwardedTitles (TitleID, AwardName, YearAwarded, Area, Country, LastName, FirstName, Title, ISBN, ImageURL, Comments) VALUES (1, 'Booker', NULL, '', '', 'McEwan', 'Ian', 'Amsterdam', ' 0385494246 ', '~/Images/AwardedTitles/Booker/Amsterdam.jpg', NULL),
(2, 'Booker', NULL, '', '', '', '', 'Disgrace', '0140296409', '~/Images/AwardedTitles/Booker/Disgrace.jpg', NULL),
(3, 'Booker', NULL, '', '', '', '', 'G', NULL, '~/Images/AwardedTitles/Booker/G.jpg', NULL),
(4, 'Booker', NULL, '', '', '', '', 'God of Small Things', NULL, '~/Images/AwardedTitles/Booker/God_of_Small_Things.jpg', NULL),
(5, 'Booker', NULL, '', '', '', '', 'Heat and Dust', NULL, '~/Images/AwardedTitles/Booker/Heat_and_Dust.jpg', NULL),
(6, 'Booker', NULL, '', '', '', '', 'Holiday', NULL, '~/Images/AwardedTitles/Booker/Holiday.jpg', NULL),
(7, 'Booker', NULL, '', '', '', '', 'Hotel DuLac', NULL, '~/Images/AwardedTitles/Booker/Hotel_DuLac.jpg', NULL),
(8, 'Booker', NULL, '', '', '', '', 'How Late it was How Late', NULL, '~/Images/AwardedTitles/Booker/How_Late_it_was_How_Late.jpg', NULL),
(9, 'Booker', NULL, '', '', '', '', 'In a Free State', NULL, '~/Images/AwardedTitles/Booker/In_a_Free_State.jpg', NULL),
(10, 'Booker', NULL, '', '', '', '', 'Last Orders', NULL, '~/Images/AwardedTitles/Booker/Last_Orders.jpg', NULL),
(11, 'Booker', NULL, '', '', '', '', 'Life and Time of Michael K', NULL, '~/Images/AwardedTitles/Booker/Life_and_Time_of_Michael_K.jpg', NULL),
(12, 'Booker', NULL, '', '', '', '', 'Life of Pi', NULL, '~/Images/AwardedTitles/Booker/Life_of_Pi.jpg', NULL),
(13, 'Booker', NULL, '', '', '', '', 'Midnights Children', NULL, '~/Images/AwardedTitles/Booker/Midnights_Children.jpg', NULL),
(14, 'Booker', NULL, '', '', '', '', 'Moon Tiger', NULL, '~/Images/AwardedTitles/Booker/Moon_Tiger.jpg', NULL),
(15, 'Booker', NULL, '', '', '', '', 'Offshore', NULL, '~/Images/AwardedTitles/Booker/Offshore.jpg', NULL),
(16, 'Booker', NULL, '', '', '', '', 'Oscar and Lucinda', NULL, '~/Images/AwardedTitles/Booker/Oscar_and_Lucinda.jpg', NULL),
(17, 'Booker', NULL, '', '', '', '', 'Paddy Clarke Ha Ha Ha', NULL, '~/Images/AwardedTitles/Booker/Paddy_Clarke_Ha_Ha_Ha.jpg', NULL),
(18, 'Booker', NULL, '', '', '', '', 'Possession', NULL, '~/Images/AwardedTitles/Booker/Possession.jpg', NULL),
(19, 'Booker', NULL, '', '', '', '', 'Remains of the Day', NULL, '~/Images/AwardedTitles/Booker/Remains_of_the_Day.jpg', NULL),
(20, 'Booker', NULL, '', '', '', '', 'Rites of Passage', NULL, '~/Images/AwardedTitles/Booker/Rites_of_Passage.jpg', NULL),
(21, 'Booker', NULL, '', '', '', '', 'Sacred Hunger', NULL, '~/Images/AwardedTitles/Booker/Sacred_Hunger.jpg', NULL),
(22, 'Booker', NULL, '', '', '', '', 'Saville', NULL, '~/Images/AwardedTitles/Booker/Saville.jpg', NULL),
(23, 'Booker', NULL, '', '', '', '', 'Schindlers Ark', NULL, '~/Images/AwardedTitles/Booker/Schindlers_Ark.jpg', NULL),
(24, 'Booker', NULL, '', '', '', '', 'Something to Answer For', NULL, '~/Images/AwardedTitles/Booker/Something_to_Answer_For.jpg', NULL),
(25, 'Booker', NULL, '', '', '', '', 'Staying On', NULL, '~/Images/AwardedTitles/Booker/Staying_On.jpg', NULL),
(26, 'Booker', NULL, '', '', '', '', 'The Blind Assasin', NULL, '~/Images/AwardedTitles/Booker/The_Blind_Assasin.jpg', NULL),
(27, 'Booker', NULL, '', '', '', '', 'The Bone People', NULL, '~/Images/AwardedTitles/Booker/The_Bone_People.jpg', NULL),
(28, 'Booker', NULL, '', '', '', '', 'The Conservationist', NULL, '~/Images/AwardedTitles/Booker/The_Conservationist.jpg', NULL),
(29, 'Booker', NULL, '', '', '', '', 'The Elected Member', NULL, '~/Images/AwardedTitles/Booker/The_Elected_Member.jpg', NULL),
(30, 'Booker', NULL, '', '', '', '', 'The English Patient', NULL, '~/Images/AwardedTitles/Booker/The_English_Patient.jpg', NULL),
(31, 'Booker', NULL, '', '', '', '', 'The Famished Road', NULL, '~/Images/AwardedTitles/Booker/The_Famished_Road.jpg', NULL),
(32, 'Booker', NULL, '', '', '', '', 'The Gathering', NULL, '~/Images/AwardedTitles/Booker/The_Gathering.jpg', NULL),
(33, 'Booker', NULL, '', '', '', '', 'The Ghost Road', NULL, '~/Images/AwardedTitles/Booker/The_Ghost_Road.jpg', NULL),
(34, 'Booker', NULL, '', '', '', '', 'The History of the Kelly Gang', NULL, '~/Images/AwardedTitles/Booker/The_History_of_the_Kelly_Gang.jpg', NULL),
(35, 'Booker', NULL, '', '', '', '', 'The Inheritance of Loss', NULL, '~/Images/AwardedTitles/Booker/The_Inheritance_of_Loss.jpg', NULL),
(36, 'Booker', NULL, '', '', '', '', 'The Line of Beauty', NULL, '~/Images/AwardedTitles/Booker/The_Line_of_Beauty.jpg', NULL),
(37, 'Booker', NULL, '', '', '', '', 'The Old Devils', NULL, '~/Images/AwardedTitles/Booker/The_Old_Devils.jpg', NULL),
(38, 'Booker', NULL, '', '', '', '', 'The Sea', NULL, '~/Images/AwardedTitles/Booker/The_Sea.jpg', NULL),
(39, 'Booker', NULL, '', '', '', '', 'The Sea the Sea', NULL, '~/Images/AwardedTitles/Booker/The_Sea_the_Sea.jpg', NULL),
(40, 'Booker', NULL, '', '', '', '', 'The Siege of Krishnapur', NULL, '~/Images/AwardedTitles/Booker/The_Siege_of_Krishnapur.jpg', NULL),
(41, 'Booker', NULL, '', '', '', '', 'The White Tiger', NULL, '~/Images/AwardedTitles/Booker/The_White_Tiger.jpg', NULL),
(42, 'Booker', NULL, '', '', '', '', 'Vernon God Little', NULL, '~/Images/AwardedTitles/Booker/Vernon_God_Little.jpg', NULL),
(56, 'Commonwealth', NULL, '', '', '', '', 'A Distant Shore', NULL, '~/Images/AwardedTitles/Commonwealth/A_Distant_Shore.jpg', NULL),
(57, 'Commonwealth', NULL, '', '', '', '', 'A Fine Balance', NULL, '~/Images/AwardedTitles/Commonwealth/A_Fine_Balance.jpg', NULL),
(58, 'Commonwealth', NULL, '', '', '', '', 'A Suitable Boy', NULL, '~/Images/AwardedTitles/Commonwealth/A_Suitable_Boy.jpg', NULL),
(59, 'Commonwealth', NULL, '', '', '', '', 'Captain Corellis Mandolin', NULL, '~/Images/AwardedTitles/Commonwealth/Captain_Corellis_Mandolin.jpg', NULL),
(60, 'Commonwealth', NULL, '', '', '', '', 'Carpathians', NULL, '~/Images/AwardedTitles/Commonwealth/Carpathians.jpg', NULL),
(61, 'Commonwealth', NULL, '', '', '', '', 'Disgrace', NULL, '~/Images/AwardedTitles/Commonwealth/Disgrace.jpg', NULL),
(62, 'Commonwealth', NULL, '', '', '', '', 'Eucalyptus', NULL, '~/Images/AwardedTitles/Commonwealth/Eucalyptus.jpg', NULL),
(63, 'Commonwealth', NULL, '', '', '', '', 'Goulds Book of Fish', NULL, '~/Images/AwardedTitles/Commonwealth/Goulds_Book_of_Fish.jpg', NULL),
(64, 'Commonwealth', NULL, '', '', '', '', 'Jack Maggs', NULL, '~/Images/AwardedTitles/Commonwealth/Jack_Maggs.jpg', NULL),
(65, 'Commonwealth', NULL, '', '', '', '', 'Mister Pip', NULL, '~/Images/AwardedTitles/Commonwealth/Mister_Pip.jpg', NULL),
(66, 'Commonwealth', NULL, '', '', '', '', 'Salt', NULL, '~/Images/AwardedTitles/Commonwealth/Salt.jpg', NULL),
(67, 'Commonwealth', NULL, '', '', '', '', 'Small Island', NULL, '~/Images/AwardedTitles/Commonwealth/Small_Island.jpg', NULL),
(68, 'Commonwealth', NULL, '', '', '', '', 'Solomon Gursky Was Here', NULL, '~/Images/AwardedTitles/Commonwealth/Solomon_Gursky_Was_Here.jpg', NULL),
(69, 'Commonwealth', NULL, '', '', '', '', 'Such A Long Journey', NULL, '~/Images/AwardedTitles/Commonwealth/Such_A_Long_Journey.jpg', NULL),
(70, 'Commonwealth', NULL, '', '', '', '', 'Summer Lightning', NULL, '~/Images/AwardedTitles/Commonwealth/Summer_Lightning.jpg', NULL),
(71, 'Commonwealth', NULL, '', '', '', '', 'The Ancestor Game', NULL, '~/Images/AwardedTitles/Commonwealth/The_Ancestor_Game.jpg', NULL),
(72, 'Commonwealth', NULL, '', '', '', '', 'The Book of Negroes', NULL, '~/Images/AwardedTitles/Commonwealth/The_Book_of_Negroes.jpg', NULL),
(73, 'Commonwealth', NULL, '', '', '', '', 'The Great World', NULL, '~/Images/AwardedTitles/Commonwealth/The_Great_World.jpg', NULL),
(74, 'Commonwealth', NULL, '', '', '', '', 'The Polished Hoe', NULL, '~/Images/AwardedTitles/Commonwealth/The_Polished_Hoe.jpg', NULL),
(75, 'Commonwealth', NULL, '', '', '', '', 'The Secret River', NULL, '~/Images/AwardedTitles/Commonwealth/The_Secret_River.jpg', NULL),
(76, 'Commonwealth', NULL, '', '', '', '', 'True History of the Kelly Gang', NULL, '~/Images/AwardedTitles/Commonwealth/True_History_of_the_Kelly_Gang.jpg', NULL),
(77, 'IMPAC', NULL, '', '', '', '', 'A Heart So White', NULL, '~/Images/AwardedTitles/IMPAC/A Heart So White.jpg', NULL),
(78, 'IMPAC', NULL, '', '', '', '', 'Atomised', NULL, '~/Images/AwardedTitles/IMPAC/Atomised.jpg', NULL),
(79, 'IMPAC', NULL, '', '', '', '', 'Ingenious Pain', NULL, '~/Images/AwardedTitles/IMPAC/Ingenious Pain.jpg', NULL),
(80, 'IMPAC', NULL, '', '', '', '', 'My Name is Red', NULL, '~/Images/AwardedTitles/IMPAC/My Name is Red.jpg', NULL),
(81, 'IMPAC', NULL, '', '', '', '', 'No Great Mischief', NULL, '~/Images/AwardedTitles/IMPAC/No Great Mischief.gif', NULL),
(82, 'IMPAC', NULL, '', '', '', '', 'Out Stealing Horses', NULL, '~/Images/AwardedTitles/IMPAC/Out Stealing Horses.jpg', NULL),
(83, 'IMPAC', NULL, '', '', '', '', 'Remembering Babylon', NULL, '~/Images/AwardedTitles/IMPAC/Remembering Babylon.jpg', NULL),
(84, 'IMPAC', NULL, '', '', '', '', 'The Blinding Absence of Light', NULL, '~/Images/AwardedTitles/IMPAC/The Blinding Absence of Light.jpg', NULL),
(85, 'IMPAC', NULL, '', '', '', '', 'The Known World', NULL, '~/Images/AwardedTitles/IMPAC/The Known World.jpg', NULL),
(86, 'IMPAC', NULL, '', '', '', '', 'The Land of Green Plums', NULL, '~/Images/AwardedTitles/IMPAC/The Land of Green Plums.jpg', NULL),
(87, 'IMPAC', NULL, '', '', '', '', 'Wide Open', NULL, '~/Images/AwardedTitles/IMPAC/Wide Open.jpg', NULL),
(94, 'Pulitzer', NULL, '', '', '', '', 'A Nation Under Our Feet', NULL, '~/Images/AwardedTitles/Pulitzer/A Nation Under Our Feet.jpg', NULL),
(95, 'Pulitzer', NULL, '', '', '', '', 'A Problem from Hell', NULL, '~/Images/AwardedTitles/Pulitzer/A Problem from Hell.jpg', NULL),
(96, 'Pulitzer', NULL, '', '', '', '', 'Alive Together', NULL, '~/Images/AwardedTitles/Pulitzer/Alive Together.jpg', NULL),
(97, 'Pulitzer', NULL, '', '', '', '', 'American Pastoral', NULL, '~/Images/AwardedTitles/Pulitzer/American Pastoral.jpg', NULL),
(98, 'Pulitzer', NULL, '', '', '', '', 'American Prometheus', NULL, '~/Images/AwardedTitles/Pulitzer/American Prometheus.jpg', NULL),
(99, 'Pulitzer', NULL, '', '', '', '', 'An Army at Dawn', NULL, '~/Images/AwardedTitles/Pulitzer/An Army at Dawn.jpg', NULL),
(100, 'Pulitzer', NULL, '', '', '', '', 'Angelas Ashes', NULL, '~/Images/AwardedTitles/Pulitzer/Angelas Ashes.jpg', NULL),
(101, 'Pulitzer', NULL, '', '', '', '', 'Anna in the Tropics', NULL, '~/Images/AwardedTitles/Pulitzer/Anna in the Tropics.jpg', NULL),
(102, 'Pulitzer', NULL, '', '', '', '', 'Annals of the Former World', NULL, '~/Images/AwardedTitles/Pulitzer/Annals of the Former World.jpg', NULL),
(103, 'Pulitzer', NULL, '', '', '', '', 'Ashes to Ashes', NULL, '~/Images/AwardedTitles/Pulitzer/Ashes to Ashes.jpg', NULL),
(104, 'Pulitzer', NULL, '', '', '', '', 'Black Zodiac', NULL, '~/Images/AwardedTitles/Pulitzer/Black Zodiac.jpg', NULL),
(105, 'Pulitzer', NULL, '', '', '', '', 'Blizzard of One', NULL, '~/Images/AwardedTitles/Pulitzer/Blizzard of One.jpg', NULL),
(106, 'Pulitzer', NULL, '', '', '', '', 'Carry Me Home', NULL, '~/Images/AwardedTitles/Pulitzer/Carry Me Home.jpg', NULL),
(107, 'Pulitzer', NULL, '', '', '', '', 'de Kooning', NULL, '~/Images/AwardedTitles/Pulitzer/de Kooning.jpg', NULL),
(108, 'Pulitzer', NULL, '', '', '', '', 'Delights and Shadows', NULL, '~/Images/AwardedTitles/Pulitzer/Delights and Shadows.jpg', NULL),
(109, 'Pulitzer', NULL, '', '', '', '', 'Different Hours', NULL, '~/Images/AwardedTitles/Pulitzer/Different Hours.jpg', NULL),
(110, 'Pulitzer', NULL, '', '', '', '', 'Dinner With Friends', NULL, '~/Images/AwardedTitles/Pulitzer/Dinner With Friends.jpg', NULL),
(111, 'Pulitzer', NULL, '', '', '', '', 'Doubt', NULL, '~/Images/AwardedTitles/Pulitzer/Doubt.jpg', NULL),
(112, 'Pulitzer', NULL, '', '', '', '', 'Embracing Defeat', NULL, '~/Images/AwardedTitles/Pulitzer/Embracing Defeat.jpg', NULL),
(113, 'Pulitzer', NULL, '', '', '', '', 'Empire Falls', NULL, '~/Images/AwardedTitles/Pulitzer/Empire Falls.jpg', NULL),
(114, 'Pulitzer', NULL, '', '', '', '', 'Founding Brothers', NULL, '~/Images/AwardedTitles/Pulitzer/Founding Brothers.jpg', NULL),
(115, 'Pulitzer', NULL, '', '', '', '', 'Freedom from Fear', NULL, '~/Images/AwardedTitles/Pulitzer/Freedom from Fear.jpg', NULL),
(116, 'Pulitzer', NULL, '', '', '', '', 'Ghost Wars', NULL, '~/Images/AwardedTitles/Pulitzer/Ghost Wars.jpg', NULL),
(117, 'Pulitzer', NULL, '', '', '', '', 'Gilead', NULL, '~/Images/AwardedTitles/Pulitzer/Gilead.jpg', NULL),
(118, 'Pulitzer', NULL, '', '', '', '', 'God - A Biography', NULL, '~/Images/AwardedTitles/Pulitzer/God - A Biography.jpg', NULL),
(119, 'Pulitzer', NULL, '', '', '', '', 'Gotham', NULL, '~/Images/AwardedTitles/Pulitzer/Gotham.jpg', NULL),
(120, 'Pulitzer', NULL, '', '', '', '', 'Gulag', NULL, '~/Images/AwardedTitles/Pulitzer/Gulag.jpg', NULL),
(121, 'Pulitzer', NULL, '', '', '', '', 'Guns, Germs, And Steel', NULL, '~/Images/AwardedTitles/Pulitzer/Guns, Germs, And Steel.jpg', NULL),
(122, 'Pulitzer', NULL, '', '', '', '', 'Harriet Beecher Stowe', NULL, '~/Images/AwardedTitles/Pulitzer/Harriet Beecher Stowe.jpg', NULL),
(123, 'Pulitzer', NULL, '', '', '', '', 'Hiroshito and the Making of Modern Japan', NULL, '~/Images/AwardedTitles/Pulitzer/Hiroshito and the Making of Modern Japan.jpg', NULL),
(124, 'Pulitzer', NULL, '', '', '', '', 'How I Learned to Drive', NULL, '~/Images/AwardedTitles/Pulitzer/How I Learned to Drive.jpg', NULL),
(125, 'Pulitzer', NULL, '', '', '', '', 'I Am My Own Wife', NULL, '~/Images/AwardedTitles/Pulitzer/I Am My Own Wife.jpg', NULL),
(126, 'Pulitzer', NULL, '', '', '', '', 'Imperial Reckoning', NULL, '~/Images/AwardedTitles/Pulitzer/Imperial Reckoning.jpg', NULL),
(127, 'Pulitzer', NULL, '', '', '', '', 'Independence Day', NULL, '~/Images/AwardedTitles/Pulitzer/Independence Day.jpg', NULL),
(128, 'Pulitzer', NULL, '', '', '', '', 'Interpreter of Maladies', NULL, '~/Images/AwardedTitles/Pulitzer/Interpreter of Maladies.jpg', NULL),
(129, 'Pulitzer', NULL, '', '', '', '', 'John Adams', NULL, '~/Images/AwardedTitles/Pulitzer/John Adams.jpg', NULL),
(130, 'Pulitzer', NULL, '', '', '', '', 'Khrushchev ', NULL, '~/Images/AwardedTitles/Pulitzer/Khrushchev .jpg', NULL),
(131, 'Pulitzer', NULL, '', '', '', '', 'Late Wife', NULL, '~/Images/AwardedTitles/Pulitzer/Late Wife.jpg', NULL),
(132, 'Pulitzer', NULL, '', '', '', '', 'March', NULL, '~/Images/AwardedTitles/Pulitzer/March.jpg', NULL),
(133, 'Pulitzer', NULL, '', '', '', '', 'Martin Dressler', NULL, '~/Images/AwardedTitles/Pulitzer/Martin Dressler.jpg', NULL),
(134, 'Pulitzer', NULL, '', '', '', '', 'Master of the Senate', NULL, '~/Images/AwardedTitles/Pulitzer/Master of the Senate.jpg', NULL),
(135, 'Pulitzer', NULL, '', '', '', '', 'Middlesex', NULL, '~/Images/AwardedTitles/Pulitzer/Middlesex.jpg', NULL),
(136, 'Pulitzer', NULL, '', '', '', '', 'Moy Sand and Gravel', NULL, '~/Images/AwardedTitles/Pulitzer/Moy Sand and Gravel.jpg', NULL),
(137, 'Pulitzer', NULL, '', '', '', '', 'Native Guard', NULL, '~/Images/AwardedTitles/Pulitzer/Native Guard.jpg', NULL),
(138, 'Pulitzer', NULL, '', '', '', '', 'No Ordinary Time', NULL, '~/Images/AwardedTitles/Pulitzer/No Ordinary Time.jpg', NULL),
(139, 'Pulitzer', NULL, '', '', '', '', 'Original Meanings', NULL, '~/Images/AwardedTitles/Pulitzer/Original Meanings.jpg', NULL),
(140, 'Pulitzer', NULL, '', '', '', '', 'Personal History', NULL, '~/Images/AwardedTitles/Pulitzer/Personal History.jpg', NULL),
(141, 'Pulitzer', NULL, '', '', '', '', 'Polio - An American Story', NULL, '~/Images/AwardedTitles/Pulitzer/Polio - An American Story.jpg', NULL),
(142, 'Pulitzer', NULL, '', '', '', '', 'Practical Gods', NULL, '~/Images/AwardedTitles/Pulitzer/Practical Gods.jpg', NULL),
(143, 'Pulitzer', NULL, '', '', '', '', 'Proof', NULL, '~/Images/AwardedTitles/Pulitzer/Proof.jpg', NULL),
(144, 'Pulitzer', NULL, '', '', '', '', 'Rent', NULL, '~/Images/AwardedTitles/Pulitzer/Rent.jpg', NULL),
(145, 'Pulitzer', NULL, '', '', '', '', 'Repair', NULL, '~/Images/AwardedTitles/Pulitzer/Repair.jpg', NULL),
(146, 'Pulitzer', NULL, '', '', '', '', 'Stone Diaries', NULL, '~/Images/AwardedTitles/Pulitzer/Stone Diaries.jpg', NULL),
(147, 'Pulitzer', NULL, '', '', '', '', 'The Amazing Adventures of Kavalier Clay', NULL, '~/Images/AwardedTitles/Pulitzer/The Amazing Adventures of Kavalier Clay.jpg', NULL),
(148, 'Pulitzer', NULL, '', '', '', '', 'The Beak of the Finch', NULL, '~/Images/AwardedTitles/Pulitzer/The Beak of the Finch.jpg', NULL),
(149, 'Pulitzer', NULL, '', '', '', '', 'The Dream of the Unified Field', NULL, '~/Images/AwardedTitles/Pulitzer/The Dream of the Unified Field.jpg', NULL),
(150, 'Pulitzer', NULL, '', '', '', '', 'The Haunted Land', NULL, '~/Images/AwardedTitles/Pulitzer/The Haunted Land.jpg', NULL),
(151, 'Pulitzer', NULL, '', '', '', '', 'The Hours', NULL, '~/Images/AwardedTitles/Pulitzer/The Hours.jpg', NULL),
(152, 'Pulitzer', NULL, '', '', '', '', 'The Known World', NULL, '~/Images/AwardedTitles/Pulitzer/The Known World.jpg', NULL),
(153, 'Pulitzer', NULL, '', '', '', '', 'The Looming Tower', NULL, '~/Images/AwardedTitles/Pulitzer/The Looming Tower.jpg', NULL),
(154, 'Pulitzer', NULL, '', '', '', '', 'The Metaphysical Club', NULL, '~/Images/AwardedTitles/Pulitzer/The Metaphysical Club.jpg', NULL),
(155, 'Pulitzer', NULL, '', '', '', '', 'The Most Famous Man in America', NULL, '~/Images/AwardedTitles/Pulitzer/The Most Famous Man in America.jpg', NULL),
(156, 'Pulitzer', NULL, '', '', '', '', 'The Race Beat', NULL, '~/Images/AwardedTitles/Pulitzer/The Race Beat.jpg', NULL),
(157, 'Pulitzer', NULL, '', '', '', '', 'The Simple Truth', NULL, '~/Images/AwardedTitles/Pulitzer/The Simple Truth.jpg', NULL),
(158, 'Pulitzer', NULL, '', '', '', '', 'The Young Man from Atlanta', NULL, '~/Images/AwardedTitles/Pulitzer/The Young Man from Atlanta.jpg', NULL),
(159, 'Pulitzer', NULL, '', '', '', '', 'Topdog Underdog', NULL, '~/Images/AwardedTitles/Pulitzer/Topdog Underdog.jpg', NULL),
(160, 'Pulitzer', NULL, '', '', '', '', 'Vera (Mrs', NULL, '~/Images/AwardedTitles/Pulitzer/Vera (Mrs. Vladimir Nabakov).jpg', NULL),
(161, 'Pulitzer', NULL, '', '', '', '', 'W', NULL, '~/Images/AwardedTitles/Pulitzer/W. E. B. Du Bois.jpg', NULL),
(162, 'Pulitzer', NULL, '', '', '', '', 'Walking to Marthas Vineyard', NULL, '~/Images/AwardedTitles/Pulitzer/Walking to Marthas Vineyard.jpg', NULL),
(163, 'Pulitzer', NULL, '', '', '', '', 'Washingtons Crossing', NULL, '~/Images/AwardedTitles/Pulitzer/Washingtons Crossing.jpg', NULL),
(164, 'PEN-Faulkner', NULL, '', '', '', '', 'Barracks Thief', NULL, '~/Images/AwardedTitles/PEN-Faulkner/Barracks_Thief.jpg', NULL),
(165, 'PEN-Faulkner', NULL, '', '', '', '', 'Bel Canto', NULL, '~/Images/AwardedTitles/PEN-Faulkner/Bel_Canto.jpg', NULL),
(166, 'PEN-Faulkner', NULL, '', '', '', '', 'Billy Bathgate', NULL, '~/Images/AwardedTitles/PEN-Faulkner/Billy_Bathgate.jpg', NULL),
(167, 'PEN-Faulkner', NULL, '', '', '', '', 'Dusk', NULL, '~/Images/AwardedTitles/PEN-Faulkner/Dusk.jpg', NULL),
(168, 'PEN-Faulkner', NULL, '', '', '', '', 'Everyman', NULL, '~/Images/AwardedTitles/PEN-Faulkner/Everyman.jpg', NULL),
(169, 'PEN-Faulkner', NULL, '', '', '', '', 'How German Is It', NULL, '~/Images/AwardedTitles/PEN-Faulkner/How_German_Is_It.jpg', NULL),
(170, 'PEN-Faulkner', NULL, '', '', '', '', 'Independence Day', NULL, '~/Images/AwardedTitles/PEN-Faulkner/Independence_Day.jpg', NULL),
(171, 'PEN-Faulkner', NULL, '', '', '', '', 'Mao II', NULL, '~/Images/AwardedTitles/PEN-Faulkner/Mao_II.jpg', NULL),
(172, 'PEN-Faulkner', NULL, '', '', '', '', 'Operation Shylock', NULL, '~/Images/AwardedTitles/PEN-Faulkner/Operation_Shylock.jpg', NULL),
(173, 'PEN-Faulkner', NULL, '', '', '', '', 'Philadelphia Fire', NULL, '~/Images/AwardedTitles/PEN-Faulkner/Philadelphia_Fire.jpg', NULL),
(174, 'PEN-Faulkner', NULL, '', '', '', '', 'Postcards', NULL, '~/Images/AwardedTitles/PEN-Faulkner/Postcards.jpg', NULL),
(175, 'PEN-Faulkner', NULL, '', '', '', '', 'Seaview', NULL, '~/Images/AwardedTitles/PEN-Faulkner/Seaview.jpg', NULL),
(176, 'PEN-Faulkner', NULL, '', '', '', '', 'Sent for you Yesterday', NULL, '~/Images/AwardedTitles/PEN-Faulkner/Sent_for_you_Yesterday.jpg', NULL),
(177, 'PEN-Faulkner', NULL, '', '', '', '', 'Snow Falling on Cedars', NULL, '~/Images/AwardedTitles/PEN-Faulkner/Snow_Falling_on_Cedars.jpg', NULL),
(178, 'PEN-Faulkner', NULL, '', '', '', '', 'Soldiers in Hiding', NULL, '~/Images/AwardedTitles/PEN-Faulkner/Soldiers_in_Hiding.jpg', NULL),
(179, 'PEN-Faulkner', NULL, '', '', '', '', 'The Bear Comes Home', NULL, '~/Images/AwardedTitles/PEN-Faulkner/The_Bear_Comes_Home.jpg', NULL),
(180, 'PEN-Faulkner', NULL, '', '', '', '', 'The Caprices', NULL, '~/Images/AwardedTitles/PEN-Faulkner/The_Caprices.jpg', NULL),
(181, 'PEN-Faulkner', NULL, '', '', '', '', 'The Chaneysville Incident', NULL, '~/Images/AwardedTitles/PEN-Faulkner/The_Chaneysville_Incident.jpg', NULL),
(182, 'PEN-Faulkner', NULL, '', '', '', '', 'The Early Stories 1953-1975', NULL, '~/Images/AwardedTitles/PEN-Faulkner/The_Early_Stories_1953-1975.jpg', NULL),
(183, 'PEN-Faulkner', NULL, '', '', '', '', 'The Great Man', NULL, '~/Images/AwardedTitles/PEN-Faulkner/The_Great_Man.jpg', NULL),
(184, 'PEN-Faulkner', NULL, '', '', '', '', 'The Hours', NULL, '~/Images/AwardedTitles/PEN-Faulkner/The_Hours.jpg', NULL),
(185, 'PEN-Faulkner', NULL, '', '', '', '', 'The Human Stain', NULL, '~/Images/AwardedTitles/PEN-Faulkner/The_Human_Stain.jpg', NULL),
(186, 'PEN-Faulkner', NULL, '', '', '', '', 'The March', NULL, '~/Images/AwardedTitles/PEN-Faulkner/The_March.jpg', NULL),
(187, 'PEN-Faulkner', NULL, '', '', '', '', 'The Old Forest', NULL, '~/Images/AwardedTitles/PEN-Faulkner/The_Old_Forest.jpg', NULL),
(188, 'PEN-Faulkner', NULL, '', '', '', '', 'Waiting', NULL, '~/Images/AwardedTitles/PEN-Faulkner/Waiting.jpg', NULL),
(189, 'PEN-Faulkner', NULL, '', '', '', '', 'War Trash', NULL, '~/Images/AwardedTitles/PEN-Faulkner/War_Trash.jpg', NULL),
(190, 'PEN-Faulkner', NULL, '', '', '', '', 'Women in their Beds', NULL, '~/Images/AwardedTitles/PEN-Faulkner/Women_in_their_Beds.jpg', NULL),
(191, 'PEN-Faulkner', NULL, '', '', '', '', 'Worlds End', NULL, '~/Images/AwardedTitles/PEN-Faulkner/Worlds_End.jpg', NULL),
(192, 'NBA', NULL, '', '', '', '', 'All the Pretty Horses', NULL, '~/Images/AwardedTitles/NBA/All_the_Pretty_Horses.jpg', NULL),
(193, 'NBA', NULL, '', '', '', '', 'Augustus', NULL, '~/Images/AwardedTitles/NBA/Augustus.jpg', NULL),
(194, 'NBA', NULL, '', '', '', '', 'A Crown of Feathers and Other Stories', NULL, '~/Images/AwardedTitles/NBA/A_Crown_of_Feathers_and_Other_Stories.jpg', NULL),
(195, 'NBA', NULL, '', '', '', '', 'A Fable', NULL, '~/Images/AwardedTitles/NBA/A_Fable.jpg', NULL),
(196, 'NBA', NULL, '', '', '', '', 'A Frolic of His Own', NULL, '~/Images/AwardedTitles/NBA/A_Frolic_of_His_Own.jpg', NULL),
(197, 'NBA', NULL, '', '', '', '', 'Blood Tie', NULL, '~/Images/AwardedTitles/NBA/Blood Tie.jpg', NULL),
(198, 'NBA', NULL, '', '', '', '', 'Charming Billy', NULL, '~/Images/AwardedTitles/NBA/Charming_Billy.jpg', NULL),
(199, 'NBA', NULL, '', '', '', '', 'Chimera', NULL, '~/Images/AwardedTitles/NBA/Chimera.jpg', NULL),
(200, 'NBA', NULL, '', '', '', '', 'Cold Mountain', NULL, '~/Images/AwardedTitles/NBA/Cold_Mountain.jpg', NULL),
(201, 'NBA', NULL, '', '', '', '', 'Corrections', NULL, '~/Images/AwardedTitles/NBA/Corrections.jpg', NULL),
(202, 'NBA', NULL, '', '', '', '', 'Dog Soldiers', NULL, '~/Images/AwardedTitles/NBA/Dog_Soldiers.jpg', NULL),
(203, 'NBA', NULL, '', '', '', '', 'Europe Central', NULL, '~/Images/AwardedTitles/NBA/Europe_Central.jpg', NULL),
(204, 'NBA', NULL, '', '', '', '', 'From Here to Eternity', NULL, '~/Images/AwardedTitles/NBA/From_Here_to_Eternity.jpg', NULL),
(205, 'NBA', NULL, '', '', '', '', 'Going After Cacciato', NULL, '~/Images/AwardedTitles/NBA/Going_After_Cacciato.jpg', NULL),
(206, 'NBA', NULL, '', '', '', '', 'Goodbye Columbus', NULL, '~/Images/AwardedTitles/NBA/Goodbye_Columbus.jpg', NULL),
(207, 'NBA', NULL, '', '', '', '', 'Gravitys Rainbow', NULL, '~/Images/AwardedTitles/NBA/Gravitys_Rainbow.jpg', NULL),
(208, 'NBA', NULL, '', '', '', '', 'Herzog', NULL, '~/Images/AwardedTitles/NBA/Herzog.jpg', NULL),
(209, 'NBA', NULL, '', '', '', '', 'Invisible Man', NULL, '~/Images/AwardedTitles/NBA/Invisible_Man.jpg', NULL),
(210, 'NBA', NULL, '', '', '', '', 'In America', NULL, '~/Images/AwardedTitles/NBA/In_America.jpg', NULL),
(211, 'NBA', NULL, '', '', '', '', 'JR', NULL, '~/Images/AwardedTitles/NBA/JR.jpg', NULL),
(212, 'NBA', NULL, '', '', '', '', 'Mating', NULL, '~/Images/AwardedTitles/NBA/Mating.jpg', NULL),
(213, 'NBA', NULL, '', '', '', '', 'Middle Passage', NULL, '~/Images/AwardedTitles/NBA/Middle_Passage.jpg', NULL),
(214, 'NBA', NULL, '', '', '', '', 'Morte dUrban', NULL, '~/Images/AwardedTitles/NBA/Morte_dUrban.jpg', NULL),
(215, 'NBA', NULL, '', '', '', '', 'Mr Slammers Planet', NULL, '~/Images/AwardedTitles/NBA/Mr_Slammers_Planet.jpg', NULL),
(216, 'NBA', NULL, '', '', '', '', 'Pacos Story', NULL, '~/Images/AwardedTitles/NBA/Pacos_Story.jpg', NULL),
(217, 'NBA', NULL, '', '', '', '', 'Paris Trout', NULL, '~/Images/AwardedTitles/NBA/Paris_Trout.jpg', NULL),
(218, 'NBA', NULL, '', '', '', '', 'Plains Song', NULL, '~/Images/AwardedTitles/NBA/Plains_Song.jpg', NULL),
(219, 'NBA', NULL, '', '', '', '', 'Rabbit is Rich', NULL, '~/Images/AwardedTitles/NBA/Rabbit_is_Rich.jpg', NULL),
(220, 'NBA', NULL, '', '', '', '', 'Sabbaths Theatre', NULL, '~/Images/AwardedTitles/NBA/Sabbaths_Theatre.jpg', NULL),
(221, 'NBA', NULL, '', '', '', '', 'Shadow Country', NULL, '~/Images/AwardedTitles/NBA/Shadow_Country.jpg', NULL),
(222, 'NBA', NULL, '', '', '', '', 'Ship Fever and Other Stories', NULL, '~/Images/AwardedTitles/NBA/Ship_Fever_and_Other_Stories.jpg', NULL),
(223, 'NBA', NULL, '', '', '', '', 'Sophies Choice', NULL, '~/Images/AwardedTitles/NBA/Sophies_Choice.jpg', NULL),
(224, 'NBA', NULL, '', '', '', '', 'Spartina', NULL, '~/Images/AwardedTitles/NBA/Spartina.jpg', NULL),
(225, 'NBA', NULL, '', '', '', '', 'Steps', NULL, '~/Images/AwardedTitles/NBA/Steps.jpg', NULL),
(226, 'NBA', NULL, '', '', '', '', 'Ten North Frederick', NULL, '~/Images/AwardedTitles/NBA/Ten_North_Frederick.jpg', NULL),
(227, 'NBA', NULL, '', '', '', '', 'The Fixer', NULL, '~/Images/AwardedTitles/NBA/The Fixer.jpg', NULL),
(228, 'NBA', NULL, '', '', '', '', 'Them', NULL, '~/Images/AwardedTitles/NBA/Them.jpg', NULL),
(229, 'NBA', NULL, '', '', '', '', 'The Adventures of Augie March', NULL, '~/Images/AwardedTitles/NBA/The_Adventures_of_Augie_March.jpg', NULL),
(230, 'NBA', NULL, '', '', '', '', 'The Centaur', NULL, '~/Images/AwardedTitles/NBA/The_Centaur.jpg', NULL),
(231, 'NBA', NULL, '', '', '', '', 'The Collected Stories', NULL, '~/Images/AwardedTitles/NBA/The_Collected_Stories.jpg', NULL),
(232, 'NBA', NULL, '', '', '', '', 'The Collected Stories by Porter', NULL, '~/Images/AwardedTitles/NBA/The_Collected_Stories_by_Porter.jpg', NULL),
(233, 'NBA', NULL, '', '', '', '', 'The Collected Stories by Welty', NULL, '~/Images/AwardedTitles/NBA/The_Collected_Stories_by_Welty.jpg', NULL),
(234, 'NBA', NULL, '', '', '', '', 'The Color Purple', NULL, '~/Images/AwardedTitles/NBA/The_Color_Purple.jpg', NULL),
(235, 'NBA', NULL, '', '', '', '', 'The Complete Stories', NULL, '~/Images/AwardedTitles/NBA/The_Complete_Stories.jpg', NULL),
(236, 'NBA', NULL, '', '', '', '', 'The Echo Maker', NULL, '~/Images/AwardedTitles/NBA/The_Echo_Maker.jpg', NULL),
(237, 'NBA', NULL, '', '', '', '', 'The Field of Vision', NULL, '~/Images/AwardedTitles/NBA/The_Field_of_Vision.jpg', NULL),
(238, 'NBA', NULL, '', '', '', '', 'The Great Fire', NULL, '~/Images/AwardedTitles/NBA/The_Great_Fire.jpg', NULL),
(239, 'NBA', NULL, '', '', '', '', 'The Hair of Harold Roux', NULL, '~/Images/AwardedTitles/NBA/The_Hair_of_Harold_Roux.jpg', NULL),
(240, 'NBA', NULL, '', '', '', '', 'The Magic Barrel', NULL, '~/Images/AwardedTitles/NBA/The_Magic_Barrel.jpg', NULL),
(241, 'NBA', NULL, '', '', '', '', 'The Man with the Golden Arm', NULL, '~/Images/AwardedTitles/NBA/The_Man_with_the_Golden_Arm.jpg', NULL),
(242, 'NBA', NULL, '', '', '', '', 'The Moviegoer', NULL, '~/Images/AwardedTitles/NBA/The_Moviegoer.jpg', NULL),
(243, 'NBA', NULL, '', '', '', '', 'The News from Paraguay', NULL, '~/Images/AwardedTitles/NBA/The_News_from_Paraguay.jpg', NULL),
(244, 'NBA', NULL, '', '', '', '', 'The Shipping News', NULL, '~/Images/AwardedTitles/NBA/The_Shipping_News.jpg', NULL),
(245, 'NBA', NULL, '', '', '', '', 'The Spectator Bird', NULL, '~/Images/AwardedTitles/NBA/The_Spectator_Bird.jpg', NULL),
(246, 'NBA', NULL, '', '', '', '', 'The Wapshot Chronicle', NULL, '~/Images/AwardedTitles/NBA/The_Wapshot_Chronicle.jpg', NULL),
(247, 'NBA', NULL, '', '', '', '', 'The Waters of Kronos', NULL, '~/Images/AwardedTitles/NBA/The_Waters_of_Kronos.jpg', NULL),
(248, 'NBA', NULL, '', '', '', '', 'The World According to Garp', NULL, '~/Images/AwardedTitles/NBA/The_World_According_to_Garp.jpg', NULL),
(249, 'NBA', NULL, '', '', '', '', 'Three Junes', NULL, '~/Images/AwardedTitles/NBA/Three_Junes.jpg', NULL),
(250, 'NBA', NULL, '', '', '', '', 'Tree-of Smoke', NULL, '~/Images/AwardedTitles/NBA/Tree-of_Smoke.jpg', NULL),
(251, 'NBA', NULL, '', '', '', '', 'Victory Over Japan', NULL, '~/Images/AwardedTitles/NBA/Victory_Over_Japan.jpg', NULL),
(252, 'NBA', NULL, '', '', '', '', 'Waiting', NULL, '~/Images/AwardedTitles/NBA/Waiting.jpg', NULL),
(253, 'NBA', NULL, '', '', '', '', 'Worlds Fair', NULL, '~/Images/AwardedTitles/NBA/Worlds_Fair.jpg', NULL),
(342, 'Nobel', NULL, '', '', '', '', 'Abducting Diana', NULL, '~/Images/AwardedTitles/Nobel/Abducting_Diana.jpg', NULL),
(343, 'Nobel', NULL, '', '', '', '', 'Absent Without Leave', NULL, '~/Images/AwardedTitles/Nobel/Absent_Without_Leave.jpg', NULL),
(344, 'Nobel', NULL, '', '', '', '', 'African Laughter', NULL, '~/Images/AwardedTitles/Nobel/African_Laughter.jpg', NULL),
(345, 'Nobel', NULL, '', '', '', '', 'After the Divorce', NULL, '~/Images/AwardedTitles/Nobel/After_the_Divorce.jpg', NULL),
(346, 'Nobel', NULL, '', '', '', '', 'And Quiet Flows the Don', NULL, '~/Images/AwardedTitles/Nobel/And_Quiet_Flows_the_Don.jpg', NULL),
(347, 'Nobel', NULL, '', '', '', '', 'An Age Ago', NULL, '~/Images/AwardedTitles/Nobel/An_Age_Ago.jpg', NULL),
(348, 'Nobel', NULL, '', '', '', '', 'As I Lay Dying', NULL, '~/Images/AwardedTitles/Nobel/As_I_Lay_Dying.jpg', NULL),
(349, 'Nobel', NULL, '', '', '', '', 'Auto Da Fe', NULL, '~/Images/AwardedTitles/Nobel/Auto_Da_Fe.jpg', NULL),
(350, 'Nobel', NULL, '', '', '', '', 'A Bridge for Passing', NULL, '~/Images/AwardedTitles/Nobel/A_Bridge_for_Passing.jpg', NULL),
(351, 'Nobel', NULL, '', '', '', '', 'A Farewell to Arms', NULL, '~/Images/AwardedTitles/Nobel/A_Farewell_to_Arms.jpg', NULL),
(352, 'Nobel', NULL, '', '', '', '', 'A Part of Speech', NULL, '~/Images/AwardedTitles/Nobel/A_Part_of_Speech.jpg', NULL),
(353, 'Nobel', NULL, '', '', '', '', 'A Personal Matter', NULL, '~/Images/AwardedTitles/Nobel/A_Personal_Matter.jpg', NULL),
(354, 'Nobel', NULL, '', '', '', '', 'A Tomb for Boris Davidovich', NULL, '~/Images/AwardedTitles/Nobel/A_Tomb_for_Boris_Davidovich.jpg', NULL),
(355, 'Nobel', NULL, '', '', '', '', 'Babbit', NULL, '~/Images/AwardedTitles/Nobel/Babbit.jpg', NULL),
(356, 'Nobel', NULL, '', '', '', '', 'Barabbas', NULL, '~/Images/AwardedTitles/Nobel/Barabbas.jpg', NULL),
(357, 'Nobel', NULL, '', '', '', '', 'Beloved', NULL, '~/Images/AwardedTitles/Nobel/Beloved.jpg', NULL),
(358, 'Nobel', NULL, '', '', '', '', 'Between Hell and Reason', NULL, '~/Images/AwardedTitles/Nobel/Between_Hell_and_Reason.jpg', NULL),
(359, 'Nobel', NULL, '', '', '', '', 'Beyond Human Might', NULL, '~/Images/AwardedTitles/Nobel/Beyond_Human_Might.jpg', NULL),
(360, 'Nobel', NULL, '', '', '', '', 'Big Woods', NULL, '~/Images/AwardedTitles/Nobel/Big_Woods.jpg', NULL),
(361, 'Nobel', NULL, '', '', '', '', 'Billiards at Half Past Nine', NULL, '~/Images/AwardedTitles/Nobel/Billiards_at_Half_Past_Nine.jpg', NULL),
(362, 'Nobel', NULL, '', '', '', '', 'Blindness', NULL, '~/Images/AwardedTitles/Nobel/Blindness.jpg', NULL),
(363, 'Nobel', NULL, '', '', '', '', 'Blood Toil Tears and Sweat', NULL, '~/Images/AwardedTitles/Nobel/Blood_Toil_Tears_and_Sweat.jpg', NULL),
(364, 'Nobel', NULL, '', '', '', '', 'Bosnian Chronicle', NULL, '~/Images/AwardedTitles/Nobel/Bosnian_Chronicle.jpg', NULL),
(365, 'Nobel', NULL, '', '', '', '', 'Buddenbrooks', NULL, '~/Images/AwardedTitles/Nobel/Buddenbrooks.jpg', NULL),
(366, 'Nobel', NULL, '', '', '', '', 'Burgers Daughter', NULL, '~/Images/AwardedTitles/Nobel/Burgers_Daughter.jpg', NULL),
(367, 'Nobel', NULL, '', '', '', '', 'Caligula', NULL, '~/Images/AwardedTitles/Nobel/Caligula.jpg', NULL),
(368, 'Nobel', NULL, '', '', '', '', 'Camus at Combat', NULL, '~/Images/AwardedTitles/Nobel/Camus_at_Combat.jpg', NULL),
(369, 'Nobel', NULL, '', '', '', '', 'Cancer Ward', NULL, '~/Images/AwardedTitles/Nobel/Cancer_Ward.jpg', NULL),
(370, 'Nobel', NULL, '', '', '', '', 'Canto General', NULL, '~/Images/AwardedTitles/Nobel/Canto_General.jpg', NULL),
(371, 'Nobel', NULL, '', '', '', '', 'Cllected Plays 2', NULL, '~/Images/AwardedTitles/Nobel/Cllected_Plays_2.jpg', NULL),
(372, 'Nobel', NULL, '', '', '', '', 'Cold Literature', NULL, '~/Images/AwardedTitles/Nobel/Cold_Literature.jpg', NULL),
(373, 'Nobel', NULL, '', '', '', '', 'Collected Plays', NULL, '~/Images/AwardedTitles/Nobel/Collected_Plays.jpg', NULL),
(374, 'Nobel', NULL, '', '', '', '', 'Collected Poems 1920-1954', NULL, '~/Images/AwardedTitles/Nobel/Collected_Poems_1920-1954.jpg', NULL),
(375, 'Nobel', NULL, '', '', '', '', 'Collected Poems 1948-1984', NULL, '~/Images/AwardedTitles/Nobel/Collected_Poems_1948-1984.jpg', NULL),
(376, 'Nobel', NULL, '', '', '', '', 'Collected Poems and Prose', NULL, '~/Images/AwardedTitles/Nobel/Collected_Poems_and_Prose.jpg', NULL),
(377, 'Nobel', NULL, '', '', '', '', 'Collected Poems in English', NULL, '~/Images/AwardedTitles/Nobel/Collected_Poems_in_English.jpg', NULL),
(378, 'Nobel', NULL, '', '', '', '', 'Collected Stories of Ivan Bunin', NULL, '~/Images/AwardedTitles/Nobel/Collected_Stories_of_Ivan_Bunin.jpg', NULL),
(379, 'Nobel', NULL, '', '', '', '', 'Collected Stories of William Faulkner', NULL, '~/Images/AwardedTitles/Nobel/Collected_Stories_of_William_Faulkner.jpg', NULL),
(380, 'Nobel', NULL, '', '', '', '', 'Complete Short Stories', NULL, '~/Images/AwardedTitles/Nobel/Complete_Short_Stories.jpg', NULL),
(381, 'Nobel', NULL, '', '', '', '', 'Complete Verse', NULL, '~/Images/AwardedTitles/Nobel/Complete_Verse.jpg', NULL),
(382, 'Nobel', NULL, '', '', '', '', 'Correspondence 1932-1960', NULL, '~/Images/AwardedTitles/Nobel/Correspondence_1932-1960.jpg', NULL),
(383, 'Nobel', NULL, '', '', '', '', 'Crediting Poetry', NULL, '~/Images/AwardedTitles/Nobel/Crediting_Poetry.jpg', NULL),
(384, 'Nobel', NULL, '', '', '', '', 'Crimes of Conscience', NULL, '~/Images/AwardedTitles/Nobel/Crimes_of_Conscience.jpg', NULL),
(385, 'Nobel', NULL, '', '', '', '', 'Cursed Days', NULL, '~/Images/AwardedTitles/Nobel/Cursed_Days.jpg', NULL),
(386, 'Nobel', NULL, '', '', '', '', 'Damned Yard and Other Stories', NULL, '~/Images/AwardedTitles/Nobel/Damned_Yard_and_Other_Stories.jpg', NULL),
(387, 'Nobel', NULL, '', '', '', '', 'Darkness Visible', NULL, '~/Images/AwardedTitles/Nobel/Darkness_Visible.jpg', NULL),
(388, 'Nobel', NULL, '', '', '', '', 'Death in Venice', NULL, '~/Images/AwardedTitles/Nobel/Death_in_Venice.jpg', NULL),
(389, 'Nobel', NULL, '', '', '', '', 'Diary of a Bad Year', NULL, '~/Images/AwardedTitles/Nobel/Diary_of_a_Bad_Year.jpg', NULL),
(390, 'Nobel', NULL, '', '', '', '', 'Discovery', NULL, '~/Images/AwardedTitles/Nobel/Discovery.jpg', NULL),
(391, 'Nobel', NULL, '', '', '', '', 'Disgrace', NULL, '~/Images/AwardedTitles/Nobel/Disgrace.jpg', NULL),
(392, 'Nobel', NULL, '', '', '', '', 'Doctor Zhivago', NULL, '~/Images/AwardedTitles/Nobel/Doctor_Zhivago.jpg', NULL),
(393, 'Nobel', NULL, '', '', '', '', 'Doris Lessing Conversations', NULL, '~/Images/AwardedTitles/Nobel/Doris_Lessing_Conversations.jpg', NULL),
(394, 'Nobel', NULL, '', '', '', '', 'Dragon Seed', NULL, '~/Images/AwardedTitles/Nobel/Dragon_Seed.jpg', NULL),
(395, 'Nobel', NULL, '', '', '', '', 'Early Poetry of Jaroslav Seifert', NULL, '~/Images/AwardedTitles/Nobel/Early_Poetry_of_Jaroslav_Seifert.jpg', NULL),
(396, 'Nobel', NULL, '', '', '', '', 'Electric Light', NULL, '~/Images/AwardedTitles/Nobel/Electric_Light.jpg', NULL),
(397, 'Nobel', NULL, '', '', '', '', 'El Senor Presidente', NULL, '~/Images/AwardedTitles/Nobel/El_Senor_Presidente.jpg', NULL),
(398, 'Nobel', NULL, '', '', '', '', 'Enduring Hemingway', NULL, '~/Images/AwardedTitles/Nobel/Enduring_Hemingway.jpg', NULL),
(399, 'Nobel', NULL, '', '', '', '', 'Exile and the Kingdom', NULL, '~/Images/AwardedTitles/Nobel/Exile_and_the_Kingdom.jpg', NULL),
(400, 'Nobel', NULL, '', '', '', '', 'Fateless', NULL, '~/Images/AwardedTitles/Nobel/Fateless.jpg', NULL),
(401, 'Nobel', NULL, '', '', '', '', 'First Snow on Fuji', NULL, '~/Images/AwardedTitles/Nobel/First_Snow_on_Fuji.jpg', NULL),
(402, 'Nobel', NULL, '', '', '', '', 'Flaws in the Glass', NULL, '~/Images/AwardedTitles/Nobel/Flaws_in_the_Glass.jpg', NULL),
(403, 'Nobel', NULL, '', '', '', '', 'For Whom the Bell Tolls', NULL, '~/Images/AwardedTitles/Nobel/For_Whom_the_Bell_Tolls.jpg', NULL),
(404, 'Nobel', NULL, '', '', '', '', 'Four Plays by Eugene ONeill', NULL, '~/Images/AwardedTitles/Nobel/Four_Plays_by_Eugene_ONeill.jpg', NULL),
(405, 'Nobel', NULL, '', '', '', '', 'Four Quartets', NULL, '~/Images/AwardedTitles/Nobel/Four_Quartets.jpg', NULL),
(406, 'Nobel', NULL, '', '', '', '', 'Fo PLays', NULL, '~/Images/AwardedTitles/Nobel/Fo_PLays.jpg', NULL),
(407, 'Nobel', NULL, '', '', '', '', 'George Bernard Shaws Plays', NULL, '~/Images/AwardedTitles/Nobel/George_Bernard_Shaws_Plays.jpg', NULL),
(408, 'Nobel', NULL, '', '', '', '', 'Gitanjali Song Offerings', NULL, '~/Images/AwardedTitles/Nobel/Gitanjali_Song_Offerings.jpg', NULL),
(409, 'Nobel', NULL, '', '', '', '', 'Go Down Moses', NULL, '~/Images/AwardedTitles/Nobel/Go_Down_Moses.jpg', NULL),
(410, 'Nobel', NULL, '', '', '', '', 'Grapes of Wrath', NULL, '~/Images/AwardedTitles/Nobel/Grapes_of_Wrath.jpg', NULL),
(411, 'Nobel', NULL, '', '', '', '', 'Great Novels of Anatole France', NULL, '~/Images/AwardedTitles/Nobel/Great_Novels_of_Anatole_France.jpg', NULL),
(412, 'Nobel', NULL, '', '', '', '', 'Group Portrait With Lady', NULL, '~/Images/AwardedTitles/Nobel/Group_Portrait_With_Lady.jpg', NULL),
(413, 'Nobel', NULL, '', '', '', '', 'Gunnars Daughter', NULL, '~/Images/AwardedTitles/Nobel/Gunnars_Daughter.jpg', NULL),
(414, 'Nobel', NULL, '', '', '', '', 'Happy Death', NULL, '~/Images/AwardedTitles/Nobel/Happy_Death.jpg', NULL),
(415, 'Nobel', NULL, '', '', '', '', 'Hunger', NULL, '~/Images/AwardedTitles/Nobel/Hunger.jpg', NULL),
(416, 'Nobel', NULL, '', '', '', '', 'Imperial Woman', NULL, '~/Images/AwardedTitles/Nobel/Imperial_Woman.jpg', NULL),
(417, 'Nobel', NULL, '', '', '', '', 'Independent People', NULL, '~/Images/AwardedTitles/Nobel/Independent_People.jpg', NULL),
(418, 'Nobel', NULL, '', '', '', '', 'Intruder in the Dust', NULL, '~/Images/AwardedTitles/Nobel/Intruder_in_the_Dust.jpg', NULL),
(419, 'Nobel', NULL, '', '', '', '', 'Invisible Links', NULL, '~/Images/AwardedTitles/Nobel/Invisible_Links.jpg', NULL),
(420, 'Nobel', NULL, '', '', '', '', 'Istanbul Memories and the City', NULL, '~/Images/AwardedTitles/Nobel/Istanbul_Memories_and_the_City.jpg', NULL),
(421, 'Nobel', NULL, '', '', '', '', 'Jean-Christophe', NULL, '~/Images/AwardedTitles/Nobel/Jean-Christophe.jpg', NULL),
(422, 'Nobel', NULL, '', '', '', '', 'Journals 1889-1913', NULL, '~/Images/AwardedTitles/Nobel/Journals_1889-1913.jpg', NULL),
(423, 'Nobel', NULL, '', '', '', '', 'Kaddish for a Child Not Born', NULL, '~/Images/AwardedTitles/Nobel/Kaddish_for_a_Child_Not_Born.jpg', NULL),
(424, 'Nobel', NULL, '', '', '', '', 'Laughter', NULL, '~/Images/AwardedTitles/Nobel/Laughter.jpg', NULL),
(425, 'Nobel', NULL, '', '', '', '', 'La Colmena', NULL, '~/Images/AwardedTitles/Nobel/La_Colmena.jpg', NULL),
(426, 'Nobel', NULL, '', '', '', '', 'La Cruz de San Andres', NULL, '~/Images/AwardedTitles/Nobel/La_Cruz_de_San_Andres.jpg', NULL),
(427, 'Nobel', NULL, '', '', '', '', 'Less Than One', NULL, '~/Images/AwardedTitles/Nobel/Less_Than_One.jpg', NULL),
(428, 'Nobel', NULL, '', '', '', '', 'Le Lieutenant-Colonel de Maumoort', NULL, '~/Images/AwardedTitles/Nobel/Le_Lieutenant-Colonel_de_Maumoort.jpg', NULL),
(429, 'Nobel', NULL, '', '', '', '', 'Lifes Wisdom', NULL, '~/Images/AwardedTitles/Nobel/Lifes_Wisdom.jpg', NULL),
(430, 'Nobel', NULL, '', '', '', '', 'Life and Times of Michael K', NULL, '~/Images/AwardedTitles/Nobel/Life_and_Times_of_Michael_K.jpg', NULL),
(431, 'Nobel', NULL, '', '', '', '', 'Light in August', NULL, '~/Images/AwardedTitles/Nobel/Light_in_August.jpg', NULL),
(432, 'Nobel', NULL, '', '', '', '', 'Lord of the Flies', NULL, '~/Images/AwardedTitles/Nobel/Lord_of_the_Flies.jpg', NULL),
(433, 'Nobel', NULL, '', '', '', '', 'Love and Geography', NULL, '~/Images/AwardedTitles/Nobel/Love_and_Geography.jpg', NULL),
(434, 'Nobel', NULL, '', '', '', '', 'Lyrical and Critical Essays', NULL, '~/Images/AwardedTitles/Nobel/Lyrical_and_Critical_Essays.jpg', NULL),
(435, 'Nobel', NULL, '', '', '', '', 'Main Street', NULL, '~/Images/AwardedTitles/Nobel/Main_Street.jpg', NULL),
(436, 'Nobel', NULL, '', '', '', '', 'Mandala', NULL, '~/Images/AwardedTitles/Nobel/Mandala.jpg', NULL),
(437, 'Nobel', NULL, '', '', '', '', 'Mazurka for Two Dead Men', NULL, '~/Images/AwardedTitles/Nobel/Mazurka_for_Two_Dead_Men.jpg', NULL),
(438, 'Nobel', NULL, '', '', '', '', 'Men of Maize', NULL, '~/Images/AwardedTitles/Nobel/Men_of_Maize.jpg', NULL),
(439, 'Nobel', NULL, '', '', '', '', 'Mexican Poetry and Anthology', NULL, '~/Images/AwardedTitles/Nobel/Mexican_Poetry_and_Anthology.jpg', NULL),
(440, 'Nobel', NULL, '', '', '', '', 'My Name Is Red', NULL, '~/Images/AwardedTitles/Nobel/My_Name_Is_Red.jpg', NULL),
(441, 'Nobel', NULL, '', '', '', '', 'Nativity Poems', NULL, '~/Images/AwardedTitles/Nobel/Nativity_Poems.jpg', NULL),
(442, 'Nobel', NULL, '', '', '', '', 'Nausea', NULL, '~/Images/AwardedTitles/Nobel/Nausea.jpg', NULL),
(443, 'Nobel', NULL, '', '', '', '', 'New and Collected Poems 1931-2001', NULL, '~/Images/AwardedTitles/Nobel/New_and_Collected_Poems_1931-2001.jpg', NULL),
(444, 'Nobel', NULL, '', '', '', '', 'Notebooks 1935-1951', NULL, '~/Images/AwardedTitles/Nobel/Notebooks_1935-1951.jpg', NULL),
(445, 'Nobel', NULL, '', '', '', '', 'One Hundred Years of Solitude', NULL, '~/Images/AwardedTitles/Nobel/One_Hundred_Years_of_Solitude.jpg', NULL),
(446, 'Nobel', NULL, '', '', '', '', 'On Grief and Reason', NULL, '~/Images/AwardedTitles/Nobel/On_Grief_and_Reason.jpg', NULL),
(447, 'Nobel', NULL, '', '', '', '', 'Penguin Island', NULL, '~/Images/AwardedTitles/Nobel/Penguin_Island.jpg', NULL),
(448, 'Nobel', NULL, '', '', '', '', 'Peony', NULL, '~/Images/AwardedTitles/Nobel/Peony.jpg', NULL),
(449, 'Nobel', NULL, '', '', '', '', 'Platero and I', NULL, '~/Images/AwardedTitles/Nobel/Platero_and_I.jpg', NULL),
(450, 'Nobel', NULL, '', '', '', '', 'Poems New and Collected 1957-1997', NULL, '~/Images/AwardedTitles/Nobel/Poems_New_and_Collected_1957-1997.jpg', NULL),
(451, 'Nobel', NULL, '', '', '', '', 'Quo Vadis', NULL, '~/Images/AwardedTitles/Nobel/Quo_Vadis.jpg', NULL),
(452, 'Nobel', NULL, '', '', '', '', 'Reeds in the Wind', NULL, '~/Images/AwardedTitles/Nobel/Reeds_in_the_Wind.jpg', NULL),
(453, 'Nobel', NULL, '', '', '', '', 'Resistance Rebellion and Death', NULL, '~/Images/AwardedTitles/Nobel/Resistance_Rebellion_and_Death.jpg', NULL),
(454, 'Nobel', NULL, '', '', '', '', 'Rhadopis of Nubia', NULL, '~/Images/AwardedTitles/Nobel/Rhadopis_of_Nubia.jpg', NULL),
(455, 'Nobel', NULL, '', '', '', '', 'Selected Poems', NULL, '~/Images/AwardedTitles/Nobel/Selected_Poems.jpg', NULL),
(456, 'Nobel', NULL, '', '', '', '', 'Selected Poems Nelly Sachs', NULL, '~/Images/AwardedTitles/Nobel/Selected_Poems_Nelly_Sachs.jpg', NULL),
(457, 'Nobel', NULL, '', '', '', '', 'Selected Stories', NULL, '~/Images/AwardedTitles/Nobel/Selected_Stories.jpg', NULL),
(458, 'Nobel', NULL, '', '', '', '', 'Siddhartha', NULL, '~/Images/AwardedTitles/Nobel/Siddhartha.jpg', NULL),
(459, 'Nobel', NULL, '', '', '', '', 'Six Plays', NULL, '~/Images/AwardedTitles/Nobel/Six_Plays.jpg', NULL),
(460, 'Nobel', NULL, '', '', '', '', 'Skeptical Essays', NULL, '~/Images/AwardedTitles/Nobel/Skeptical_Essays.jpg', NULL),
(461, 'Nobel', NULL, '', '', '', '', 'Snow Country and Thousand Cranes', NULL, '~/Images/AwardedTitles/Nobel/Snow_Country_and_Thousand_Cranes.jpg', NULL),
(462, 'Nobel', NULL, '', '', '', '', 'Sons', NULL, '~/Images/AwardedTitles/Nobel/Sons.jpg', NULL),
(463, 'Nobel', NULL, '', '', '', '', 'So Forth', NULL, '~/Images/AwardedTitles/Nobel/So_Forth.jpg', NULL),
(464, 'Nobel', NULL, '', '', '', '', 'Stories Political Writings and Autobiographical Works', NULL, '~/Images/AwardedTitles/Nobel/Stories_Political_Writings_and_Autobiographical_Works.jpg', NULL),
(465, 'Nobel', NULL, '', '', '', '', 'Thais', NULL, '~/Images/AwardedTitles/Nobel/Thais.jpg', NULL),
(466, 'Nobel', NULL, '', '', '', '', 'Therese', NULL, '~/Images/AwardedTitles/Nobel/Therese.jpg', NULL),
(467, 'Nobel', NULL, '', '', '', '', 'The Age of Reason', NULL, '~/Images/AwardedTitles/Nobel/The_Age_of_Reason.jpg', NULL),
(468, 'Nobel', NULL, '', '', '', '', 'The Bluest Eye', NULL, '~/Images/AwardedTitles/Nobel/The_Bluest_Eye.jpg', NULL),
(469, 'Nobel', NULL, '', '', '', '', 'The Burden of Memory', NULL, '~/Images/AwardedTitles/Nobel/The_Burden_of_Memory.jpg', NULL),
(470, 'Nobel', NULL, '', '', '', '', 'The Cairo Trilogy', NULL, '~/Images/AwardedTitles/Nobel/The_Cairo_Trilogy.jpg', NULL),
(471, 'Nobel', NULL, '', '', '', '', 'The Captive Mind', NULL, '~/Images/AwardedTitles/Nobel/The_Captive_Mind.jpg', NULL),
(472, 'Nobel', NULL, '', '', '', '', 'The Collected Poems of Octavio Paz 1957-1987', NULL, '~/Images/AwardedTitles/Nobel/The_Collected_Poems_of_Octavio_Paz_1957-1987.jpg', NULL),
(473, 'Nobel', NULL, '', '', '', '', 'The Collected Poems of Odysseus Elytis', NULL, '~/Images/AwardedTitles/Nobel/The_Collected_Poems_of_Odysseus_Elytis.jpg', NULL),
(474, 'Nobel', NULL, '', '', '', '', 'The Collected Poems of W B Yeats', NULL, '~/Images/AwardedTitles/Nobel/The_Collected_Poems_of_W_B_Yeats.jpg', NULL),
(475, 'Nobel', NULL, '', '', '', '', 'The Collected Stories', NULL, '~/Images/AwardedTitles/Nobel/The_Collected_Stories.jpg', NULL),
(476, 'Nobel', NULL, '', '', '', '', 'The Curch of Solitude', NULL, '~/Images/AwardedTitles/Nobel/The_Curch_of_Solitude.jpg', NULL),
(477, 'Nobel', NULL, '', '', '', '', 'The Daughters of Madame Liang', NULL, '~/Images/AwardedTitles/Nobel/The_Daughters_of_Madame_Liang.jpg', NULL),
(478, 'Nobel', NULL, '', '', '', '', 'The Deluge', NULL, '~/Images/AwardedTitles/Nobel/The_Deluge.jpg', NULL),
(479, 'Nobel', NULL, '', '', '', '', 'The Elagin Affair', NULL, '~/Images/AwardedTitles/Nobel/The_Elagin_Affair.jpg', NULL),
(480, 'Nobel', NULL, '', '', '', '', 'The Ends of the Earth', NULL, '~/Images/AwardedTitles/Nobel/The_Ends_of_the_Earth.jpg', NULL),
(481, 'Nobel', NULL, '', '', '', '', 'The Essential Neruda', NULL, '~/Images/AwardedTitles/Nobel/The_Essential_Neruda.jpg', NULL),
(482, 'Nobel', NULL, '', '', '', '', 'The Fall', NULL, '~/Images/AwardedTitles/Nobel/The_Fall.jpg', NULL),
(483, 'Nobel', NULL, '', '', '', '', 'The First Man', NULL, '~/Images/AwardedTitles/Nobel/The_First_Man.jpg', NULL),
(484, 'Nobel', NULL, '', '', '', '', 'The Forsyte Saga', NULL, '~/Images/AwardedTitles/Nobel/The_Forsyte_Saga.jpg', NULL),
(485, 'Nobel', NULL, '', '', '', '', 'The Good Earth', NULL, '~/Images/AwardedTitles/Nobel/The_Good_Earth.jpg', NULL),
(486, 'Nobel', NULL, '', '', '', '', 'The Gulag Archipelago 1918-1956', NULL, '~/Images/AwardedTitles/Nobel/The_Gulag_Archipelago_1918-1956.jpg', NULL),
(487, 'Nobel', NULL, '', '', '', '', 'The Gunter Grass Reader', NULL, '~/Images/AwardedTitles/Nobel/The_Gunter_Grass_Reader.jpg', NULL),
(488, 'Nobel', NULL, '', '', '', '', 'The Immoralist', NULL, '~/Images/AwardedTitles/Nobel/The_Immoralist.jpg', NULL),
(489, 'Nobel', NULL, '', '', '', '', 'The Invitation', NULL, '~/Images/AwardedTitles/Nobel/The_Invitation.jpg', NULL),
(490, 'Nobel', NULL, '', '', '', '', 'The Lake', NULL, '~/Images/AwardedTitles/Nobel/The_Lake.jpg', NULL),
(491, 'Nobel', NULL, '', '', '', '', 'The Liberation of Tolstoy', NULL, '~/Images/AwardedTitles/Nobel/The_Liberation_of_Tolstoy.jpg', NULL),
(492, 'Nobel', NULL, '', '', '', '', 'The Living Reed', NULL, '~/Images/AwardedTitles/Nobel/The_Living_Reed.jpg', NULL),
(493, 'Nobel', NULL, '', '', '', '', 'The Lost Honor of Katharina Blum', NULL, '~/Images/AwardedTitles/Nobel/The_Lost_Honor_of_Katharina_Blum.jpg', NULL),
(494, 'Nobel', NULL, '', '', '', '', 'The Mad Dog', NULL, '~/Images/AwardedTitles/Nobel/The_Mad_Dog.jpg', NULL),
(495, 'Nobel', NULL, '', '', '', '', 'The Marriage Feast', NULL, '~/Images/AwardedTitles/Nobel/The_Marriage_Feast.jpg', NULL),
(496, 'Nobel', NULL, '', '', '', '', 'The Memoirs of Elias Canetti', NULL, '~/Images/AwardedTitles/Nobel/The_Memoirs_of_Elias_Canetti.jpg', NULL),
(497, 'Nobel', NULL, '', '', '', '', 'The Mother', NULL, '~/Images/AwardedTitles/Nobel/The_Mother.jpg', NULL),
(498, 'Nobel', NULL, '', '', '', '', 'The Myth of Sisyphus', NULL, '~/Images/AwardedTitles/Nobel/The_Myth_of_Sisyphus.jpg', NULL),
(499, 'Nobel', NULL, '', '', '', '', 'The Occasions', NULL, '~/Images/AwardedTitles/Nobel/The_Occasions.jpg', NULL),
(500, 'Nobel', NULL, '', '', '', '', 'The Old Man and the Sea', NULL, '~/Images/AwardedTitles/Nobel/The_Old_Man_and_the_Sea.jpg', NULL),
(501, 'Nobel', NULL, '', '', '', '', 'The Peasants Bible and The Story of the Tiger', NULL, '~/Images/AwardedTitles/Nobel/The_Peasants_Bible_and_The_Story_of_the_Tiger.jpg', NULL),
(502, 'Nobel', NULL, '', '', '', '', 'The Plague', NULL, '~/Images/AwardedTitles/Nobel/The_Plague.jpg', NULL),
(503, 'Nobel', NULL, '', '', '', '', 'The Play of the Eyes', NULL, '~/Images/AwardedTitles/Nobel/The_Play_of_the_Eyes.jpg', NULL),
(504, 'Nobel', NULL, '', '', '', '', 'The Pope and the Witch', NULL, '~/Images/AwardedTitles/Nobel/The_Pope_and_the_Witch.jpg', NULL),
(505, 'Nobel', NULL, '', '', '', '', 'The Promise', NULL, '~/Images/AwardedTitles/Nobel/The_Promise.jpg', NULL),
(506, 'Nobel', NULL, '', '', '', '', 'The Rebel', NULL, '~/Images/AwardedTitles/Nobel/The_Rebel.jpg', NULL),
(507, 'Nobel', NULL, '', '', '', '', 'The Secret Heart of the Clock', NULL, '~/Images/AwardedTitles/Nobel/The_Secret_Heart_of_the_Clock.jpg', NULL),
(508, 'Nobel', NULL, '', '', '', '', 'The Sound and the Fury', NULL, '~/Images/AwardedTitles/Nobel/The_Sound_and_the_Fury.jpg', NULL),
(509, 'Nobel', NULL, '', '', '', '', 'The Tin Drum', NULL, '~/Images/AwardedTitles/Nobel/The_Tin_Drum.jpg', NULL),
(510, 'Nobel', NULL, '', '', '', '', 'The Torch in My Ear', NULL, '~/Images/AwardedTitles/Nobel/The_Torch_in_My_Ear.jpg', NULL),
(511, 'Nobel', NULL, '', '', '', '', 'The Unvanquished', NULL, '~/Images/AwardedTitles/Nobel/The_Unvanquished.jpg', NULL),
(512, 'Nobel', NULL, '', '', '', '', 'The White Castle', NULL, '~/Images/AwardedTitles/Nobel/The_White_Castle.jpg', NULL),
(513, 'Nobel', NULL, '', '', '', '', 'Three Novels', NULL, '~/Images/AwardedTitles/Nobel/Three_Novels.jpg', NULL),
(514, 'Nobel', NULL, '', '', '', '', 'Three Plays', NULL, '~/Images/AwardedTitles/Nobel/Three_Plays.jpg', NULL),
(515, 'Nobel', NULL, '', '', '', '', 'Three Pre-Surrealist Plays', NULL, '~/Images/AwardedTitles/Nobel/Three_Pre-Surrealist_Plays.jpg', NULL),
(516, 'Nobel', NULL, '', '', '', '', 'To Urania', NULL, '~/Images/AwardedTitles/Nobel/To_Urania.jpg', NULL),
(517, 'Nobel', NULL, '', '', '', '', 'We Wont Pay We Wont Pay', NULL, '~/Images/AwardedTitles/Nobel/We_Wont_Pay_We_Wont_Pay.jpg', NULL),
(518, 'Nobel', NULL, '', '', '', '', 'Wild Bouquet', NULL, '~/Images/AwardedTitles/Nobel/Wild_Bouquet.jpg', NULL),
(519, 'Nobel', NULL, '', '', '', '', 'Wise Knut', NULL, '~/Images/AwardedTitles/Nobel/Wise_Knut.jpg', NULL),
(520, 'Nobel', NULL, '', '', '', '', 'Women As Lovers', NULL, '~/Images/AwardedTitles/Nobel/Women_As_Lovers.jpg', NULL),
(521, 'Nobel', NULL, '', '', '', '', 'Women in a River Landscape', NULL, '~/Images/AwardedTitles/Nobel/Women_in_a_River_Landscape.jpg', NULL),
(522, 'Nobel', NULL, '', '', '', '', 'World Light', NULL, '~/Images/AwardedTitles/Nobel/World_Light.jpg', NULL),
(523, 'Nobel', NULL, '', '', '', '', 'Youth', NULL, '~/Images/AwardedTitles/Nobel/Youth.jpg', NULL),
(524, 'NBCC', NULL, '', '', '', '', 'All the Pretty Horses', NULL, '~/Images/AwardedTitles/NBCC/All_the_Pretty_Horses.jpg', NULL),
(525, 'NBCC', NULL, '', '', '', '', 'Atonement', NULL, '~/Images/AwardedTitles/NBCC/Atonement.jpg', NULL),
(526, 'NBCC', NULL, '', '', '', '', 'Austerlitz', NULL, '~/Images/AwardedTitles/NBCC/Austerlitz.jpg', NULL),
(527, 'NBCC', NULL, '', '', '', '', 'A Lesson Before Dying', NULL, '~/Images/AwardedTitles/NBCC/A_Lesson_Before_Dying.jpg', NULL),
(528, 'NBCC', NULL, '', '', '', '', 'A Summons to Memphis', NULL, '~/Images/AwardedTitles/NBCC/A_Summons_to_Memphis.jpg', NULL),
(529, 'NBCC', NULL, '', '', '', '', 'A Thousand Acres', NULL, '~/Images/AwardedTitles/NBCC/A_Thousand_Acres.jpg', NULL),
(530, 'NBCC', NULL, '', '', '', '', 'Being Dead', NULL, '~/Images/AwardedTitles/NBCC/Being_Dead.jpg', NULL),
(531, 'NBCC', NULL, '', '', '', '', 'Billy Bathgate', NULL, '~/Images/AwardedTitles/NBCC/Billy_Bathgate.jpg', NULL),
(532, 'NBCC', NULL, '', '', '', '', 'George Mills', NULL, '~/Images/AwardedTitles/NBCC/George_Mills.jpg', NULL),
(533, 'NBCC', NULL, '', '', '', '', 'Gilead', NULL, '~/Images/AwardedTitles/NBCC/Gilead.jpg', NULL),
(534, 'NBCC', NULL, '', '', '', '', 'Ironweed', NULL, '~/Images/AwardedTitles/NBCC/Ironweed.jpg', NULL),
(535, 'NBCC', NULL, '', '', '', '', 'Love Medicine', NULL, '~/Images/AwardedTitles/NBCC/Love_Medicine.jpg', NULL),
(536, 'NBCC', NULL, '', '', '', '', 'Motherless Brooklyn', NULL, '~/Images/AwardedTitles/NBCC/Motherless_Brooklyn.jpg', NULL),
(537, 'NBCC', NULL, '', '', '', '', 'Mrs Ted Bliss', NULL, '~/Images/AwardedTitles/NBCC/Mrs_Ted_Bliss.jpg', NULL),
(539, 'NBCC', NULL, '', '', '', '', 'October Light', NULL, '~/Images/AwardedTitles/NBCC/October_Light.jpg', NULL),
(540, 'NBCC', NULL, '', '', '', '', 'Rabbit at Rest', NULL, '~/Images/AwardedTitles/NBCC/Rabbit_at_Rest.jpg', NULL),
(541, 'NBCC', NULL, '', '', '', '', 'Rabbit Is Rich', NULL, '~/Images/AwardedTitles/NBCC/Rabbit_Is_Rich.jpg', NULL),
(542, 'NBCC', NULL, '', '', '', '', 'Ragtime', NULL, '~/Images/AwardedTitles/NBCC/Ragtime.jpg', NULL),
(543, 'NBCC', NULL, '', '', '', '', 'Song of Solomon', NULL, '~/Images/AwardedTitles/NBCC/Song_of_Solomon.jpg', NULL),
(544, 'NBCC', NULL, '', '', '', '', 'The Accidental Tourist', NULL, '~/Images/AwardedTitles/NBCC/The_Accidental_Tourist.jpg', NULL),
(545, 'NBCC', NULL, '', '', '', '', 'The Blue Flower', NULL, '~/Images/AwardedTitles/NBCC/The_Blue_Flower.jpg', NULL),
(546, 'NBCC', NULL, '', '', '', '', 'The Brief Wondorous Life of Oscar Wao', NULL, '~/Images/AwardedTitles/NBCC/The_Brief_Wondorous_Life_of_Oscar_Wao.jpg', NULL),
(547, 'NBCC', NULL, '', '', '', '', 'The Counter Life', NULL, '~/Images/AwardedTitles/NBCC/The_Counter_Life.jpg', NULL),
(548, 'NBCC', NULL, '', '', '', '', 'The Inheritance of Loss', NULL, '~/Images/AwardedTitles/NBCC/The_Inheritance_of_Loss.jpg', NULL),
(549, 'NBCC', NULL, '', '', '', '', 'The Known World', NULL, '~/Images/AwardedTitles/NBCC/The_Known_World.jpg', NULL),
(550, 'NBCC', NULL, '', '', '', '', 'The Love of a Good Woman', NULL, '~/Images/AwardedTitles/NBCC/The_Love_of_a_Good_Woman.jpg', NULL),
(551, 'NBCC', NULL, '', '', '', '', 'The March', NULL, '~/Images/AwardedTitles/NBCC/The_March.jpg', NULL),
(552, 'NBCC', NULL, '', '', '', '', 'The Middleman and Other Stories', NULL, '~/Images/AwardedTitles/NBCC/The_Middleman_and_Other_Stories.jpg', NULL),
(553, 'NBCC', NULL, '', '', '', '', 'The Stone Diaries', NULL, '~/Images/AwardedTitles/NBCC/The_Stone_Diaries.jpg', NULL),
(554, 'NBCC', NULL, '', '', '', '', 'The Stories of John Cheever', NULL, '~/Images/AwardedTitles/NBCC/The_Stories_of_John_Cheever.jpg', NULL),
(555, 'NBCC', NULL, '', '', '', '', 'The Transit of Venus', NULL, '~/Images/AwardedTitles/NBCC/The_Transit_of_Venus.jpg', NULL),
(556, 'NBCC', NULL, '', '', '', '', 'The Year of the French', NULL, '~/Images/AwardedTitles/NBCC/The_Year_of_the_French.jpg', NULL),
(557, 'NBCC', NULL, '', '', '', '', 'Women In Their Beds', NULL, '~/Images/AwardedTitles/NBCC/Women_In_Their_Beds.jpg', NULL);