INSERT INTO AwardedAuthors (AuthorID, AwardName, YearAwarded, Area, Country, LastName, FirstName, YearBorn, YearDied, ImageURL, Comments) VALUES (1, 'Booker', NULL, '', '', 'Atwood', 'Margaret', NULL, NULL, 'Images/AwardedAuthors/Booker/Atwood_Margaret.jpg', NULL),
(2, 'Booker', NULL, '', '', 'Banville', 'John', NULL, NULL, 'Images/AwardedAuthors/Booker/Banville_John.jpg', NULL),
(3, 'Booker', NULL, '', '', 'Barker', 'Pat', NULL, NULL, 'Images/AwardedAuthors/Booker/Barker_Pat.jpg', NULL),
(4, 'Booker', NULL, '', '', 'Berger', 'John', NULL, NULL, 'Images/AwardedAuthors/Booker/Berger_John.jpg', NULL),
(5, 'Booker', NULL, '', '', 'Brookner', 'Anita', NULL, NULL, 'Images/AwardedAuthors/Booker/Brookner_Anita.jpg', NULL),
(6, 'Booker', NULL, '', '', 'Byatt', 'A S', NULL, NULL, 'Images/AwardedAuthors/Booker/Byatt_A S.jpg', NULL),
(7, 'Booker', NULL, '', '', 'Carey', 'Peter', NULL, NULL, 'Images/AwardedAuthors/Booker/Carey_Peter.jpg', NULL),
(8, 'Booker', NULL, '', '', 'Coetzee', 'John M', NULL, NULL, 'Images/AwardedAuthors/Booker/Coetzee_John M.jpg', NULL),
(9, 'Booker', NULL, '', '', 'Desai', 'Kiran', NULL, NULL, 'Images/AwardedAuthors/Booker/Desai_Kiran.jpg', NULL),
(10, 'Booker', NULL, '', '', 'Doyle', 'Roddy', NULL, NULL, 'Images/AwardedAuthors/Booker/Doyle_Roddy.jpg', NULL),
(11, 'Booker', NULL, '', '', 'Farrell', 'J G', NULL, NULL, 'Images/AwardedAuthors/Booker/Farrell_J G.jpg', NULL),
(12, 'Booker', NULL, '', '', 'Fitzgerald', 'Penelope', NULL, NULL, 'Images/AwardedAuthors/Booker/Fitzgerald_Penelope.jpg', NULL),
(13, 'Booker', NULL, '', '', 'Golding', 'William', NULL, NULL, 'Images/AwardedAuthors/Booker/Golding_William.jpg', NULL),
(14, 'Booker', NULL, '', '', 'Gordimer', 'Nadine', NULL, NULL, 'Images/AwardedAuthors/Booker/Gordimer_Nadine.jpg', NULL),
(15, 'Booker', NULL, '', '', 'Hollinghurst', 'Alan', NULL, NULL, 'Images/AwardedAuthors/Booker/Hollinghurst_Alan.jpg', NULL),
(16, 'Booker', NULL, '', '', 'Hulme', 'Keri', NULL, NULL, 'Images/AwardedAuthors/Booker/Hulme_Keri.jpg', NULL),
(17, 'Booker', NULL, '', '', 'Ishiguro', 'Kazuo', NULL, NULL, 'Images/AwardedAuthors/Booker/Ishiguro_Kazuo.jpg', NULL),
(18, 'Booker', NULL, '', '', 'Jhabvala', 'Ruth Prawer', NULL, NULL, 'Images/AwardedAuthors/Booker/Jhabvala_Ruth Prawer.jpg', NULL),
(19, 'Booker', NULL, '', '', 'Kelman', 'James', NULL, NULL, 'Images/AwardedAuthors/Booker/Kelman_James.jpg', NULL),
(20, 'Booker', NULL, '', '', 'Keneally', 'Thomas', NULL, NULL, 'Images/AwardedAuthors/Booker/Keneally_Thomas.jpg', NULL),
(21, 'Booker', NULL, '', '', 'Kingsley', 'Amis', NULL, NULL, 'Images/AwardedAuthors/Booker/Kingsley_Amis.jpg', NULL),
(22, 'Booker', NULL, '', '', 'Lively', 'Penelope', NULL, NULL, 'Images/AwardedAuthors/Booker/Lively_Penelope.jpg', NULL),
(23, 'Booker', NULL, '', '', 'Martel', 'Yann', NULL, NULL, 'Images/AwardedAuthors/Booker/Martel_Yann.jpg', NULL),
(24, 'Booker', NULL, '', '', 'McEwan', 'Ian', NULL, NULL, 'Images/AwardedAuthors/Booker/McEwan_Ian.jpg', NULL),
(25, 'Booker', NULL, '', '', 'Murdoch', 'Iris', NULL, NULL, 'Images/AwardedAuthors/Booker/Murdoch_Iris.jpg', NULL),
(26, 'Booker', NULL, '', '', 'Naipaul', 'V S', NULL, NULL, 'Images/AwardedAuthors/Booker/Naipaul_V S.jpg', NULL),
(27, 'Booker', NULL, '', '', 'Newby', 'P H', NULL, NULL, 'Images/AwardedAuthors/Booker/Newby_P H.jpg', NULL),
(28, 'Booker', NULL, '', '', 'Okri', 'Ben', NULL, NULL, 'Images/AwardedAuthors/Booker/Okri_Ben.jpg', NULL),
(29, 'Booker', NULL, '', '', 'Ondaatje', 'Michael', NULL, NULL, 'Images/AwardedAuthors/Booker/Ondaatje_Michael.jpg', NULL),
(30, 'Booker', NULL, '', '', 'Pierre', 'D B C', NULL, NULL, 'Images/AwardedAuthors/Booker/Pierre_D B C.jpg', NULL),
(31, 'Booker', NULL, '', '', 'Roy', 'Arundhati', NULL, NULL, 'Images/AwardedAuthors/Booker/Roy_Arundhati.jpg', NULL),
(32, 'Booker', NULL, '', '', 'Rubens', 'Bernice', NULL, NULL, 'Images/AwardedAuthors/Booker/Rubens_Bernice.jpg', NULL),
(33, 'Booker', NULL, '', '', 'Rushdie', 'Salman', NULL, NULL, 'Images/AwardedAuthors/Booker/Rushdie_Salman.jpg', NULL),
(34, 'Booker', NULL, '', '', 'Scott', 'Paul', NULL, NULL, 'Images/AwardedAuthors/Booker/Scott_Paul.jpg', NULL),
(35, 'Booker', NULL, '', '', 'Storey', 'David', NULL, NULL, 'Images/AwardedAuthors/Booker/Storey_David.jpg', NULL),
(36, 'Booker', NULL, '', '', 'Swift', 'Graham', NULL, NULL, 'Images/AwardedAuthors/Booker/Swift_Graham.jpg', NULL),
(139, 'Pulitzer', NULL, '', '', 'Applebaum', 'Ann', NULL, NULL, 'Images/AwardedAuthors/Pulitzer/Applebaum_Ann.jpg', NULL),
(140, 'Pulitzer', NULL, '', '', 'Applegate', 'Debby', NULL, NULL, 'Images/AwardedAuthors/Pulitzer/Applegate_Debby.jpg', NULL),
(141, 'Pulitzer', NULL, '', '', 'Bird', 'Kai and Serwin_Martin', NULL, NULL, 'Images/AwardedAuthors/Pulitzer/Bird_Kai and Serwin_Martin.jpg', NULL),
(142, 'Pulitzer', NULL, '', '', 'Bird', 'Kai', NULL, NULL, 'Images/AwardedAuthors/Pulitzer/Bird_Kai.jpg', NULL),
(143, 'Pulitzer', NULL, '', '', 'Brooks', 'Geraldine', NULL, NULL, 'Images/AwardedAuthors/Pulitzer/Brooks_Geraldine.jpg', NULL),
(144, 'Pulitzer', NULL, '', '', 'Coll', 'Steve', NULL, NULL, 'Images/AwardedAuthors/Pulitzer/Coll_Steve.jpg', NULL),
(145, 'Pulitzer', NULL, '', '', 'Elkins', 'Caroline', NULL, NULL, 'Images/AwardedAuthors/Pulitzer/Elkins_Caroline.jpg', NULL),
(146, 'Pulitzer', NULL, '', '', 'Emerson', 'Claudia', NULL, NULL, 'Images/AwardedAuthors/Pulitzer/Emerson_Claudia.jpg', NULL),
(147, 'Pulitzer', NULL, '', '', 'Fischer', 'David Hackett', NULL, NULL, 'Images/AwardedAuthors/Pulitzer/Fischer_David Hackett.jpg', NULL),
(148, 'Pulitzer', NULL, '', '', 'Hahn', 'Steven', NULL, NULL, 'Images/AwardedAuthors/Pulitzer/Hahn_Steven.jpg', NULL),
(149, 'Pulitzer', NULL, '', '', 'Jones', 'Edward P', NULL, NULL, 'Images/AwardedAuthors/Pulitzer/Jones_Edward P.jpg', NULL),
(150, 'Pulitzer', NULL, '', '', 'Kooser', 'Ted', NULL, NULL, 'Images/AwardedAuthors/Pulitzer/Kooser_Ted.jpg', NULL),
(151, 'Pulitzer', NULL, '', '', 'Lindsay-Abaire', 'David', NULL, NULL, 'Images/AwardedAuthors/Pulitzer/Lindsay-Abaire_David.jpg', NULL),
(152, 'Pulitzer', NULL, '', '', 'Mccarthy', 'Cormac', NULL, NULL, 'Images/AwardedAuthors/Pulitzer/Mccarthy_Cormac.jpg', NULL),
(153, 'Pulitzer', NULL, '', '', 'Oshinsky', 'David M', NULL, NULL, 'Images/AwardedAuthors/Pulitzer/Oshinsky_David M.jpg', NULL),
(154, 'Pulitzer', NULL, '', '', 'Robinson', 'Marilynne', NULL, NULL, 'Images/AwardedAuthors/Pulitzer/Robinson_Marilynne.jpg', NULL),
(155, 'Pulitzer', NULL, '', '', 'Shanley', 'John Patrick', NULL, NULL, 'Images/AwardedAuthors/Pulitzer/Shanley_John Patrick.jpg', NULL),
(156, 'Pulitzer', NULL, '', '', 'Sherwin', 'Martin', NULL, NULL, 'Images/AwardedAuthors/Pulitzer/Sherwin_Martin.jpg', NULL),
(157, 'Pulitzer', NULL, '', '', 'Stevens', 'Mark and Swan_Annalyn', NULL, NULL, 'Images/AwardedAuthors/Pulitzer/Stevens_Mark and Swan_Annalyn.jpg', NULL),
(158, 'Pulitzer', NULL, '', '', 'Taubman', 'William', NULL, NULL, 'Images/AwardedAuthors/Pulitzer/Taubman_William.jpg', NULL),
(159, 'Pulitzer', NULL, '', '', 'Trethewey', 'Natasha', NULL, NULL, 'Images/AwardedAuthors/Pulitzer/Trethewey_Natasha.jpg', NULL),
(160, 'Pulitzer', NULL, '', '', 'Wright', 'Doug', NULL, NULL, 'Images/AwardedAuthors/Pulitzer/Wright_Doug.jpg', NULL),
(161, 'Pulitzer', NULL, '', '', 'Wright', 'Franz', NULL, NULL, 'Images/AwardedAuthors/Pulitzer/Wright_Franz.jpg', NULL),
(162, 'Pulitzer', NULL, '', '', 'Wright', 'Lawrence', NULL, NULL, 'Images/AwardedAuthors/Pulitzer/Wright_Lawrence.jpg', NULL),
(163, 'Nobel', NULL, '', '', 'Agnon', 'Shmuel Yosef', NULL, NULL, 'Images/AwardedAuthors/Nobel/Agnon_Shmuel Yosef.jpg', NULL),
(164, 'Nobel', NULL, '', '', 'Aleixandre', 'Vincente', NULL, NULL, 'Images/AwardedAuthors/Nobel/Aleixandre_Vincente.jpg', NULL),
(165, 'Nobel', NULL, '', '', 'Andric', 'Ivo', NULL, NULL, 'Images/AwardedAuthors/Nobel/Andric_Ivo.jpg', NULL),
(166, 'Nobel', NULL, '', '', 'Asturias', 'Miguel', NULL, NULL, 'Images/AwardedAuthors/Nobel/Asturias_Miguel.jpg', NULL),
(167, 'Nobel', NULL, '', '', 'Beckett', 'Samuel', NULL, NULL, 'Images/AwardedAuthors/Nobel/Beckett_Samuel.jpg', NULL),
(168, 'Nobel', NULL, '', '', 'Bellow', 'Saul', NULL, NULL, 'Images/AwardedAuthors/Nobel/Bellow_Saul.jpg', NULL),
(169, 'Nobel', NULL, '', '', 'Benavente', 'Jacinto', NULL, NULL, 'Images/AwardedAuthors/Nobel/Benavente_Jacinto.jpg', NULL),
(170, 'Nobel', NULL, '', '', 'Bergson', 'Henri', NULL, NULL, 'Images/AwardedAuthors/Nobel/Bergson_Henri.jpg', NULL),
(171, 'Nobel', NULL, '', '', 'Bjornstjerne', 'Bjornson', NULL, NULL, 'Images/AwardedAuthors/Nobel/Bjornstjerne_Bjornson.jpg', NULL),
(172, 'Nobel', NULL, '', '', 'Boll', 'Heinrich', NULL, NULL, 'Images/AwardedAuthors/Nobel/Boll_Heinrich.jpg', NULL),
(173, 'Nobel', NULL, '', '', 'Brodsky', 'Joseph', NULL, NULL, 'Images/AwardedAuthors/Nobel/Brodsky_Joseph.jpg', NULL),
(174, 'Nobel', NULL, '', '', 'Buck', 'Pearl', NULL, NULL, 'Images/AwardedAuthors/Nobel/Buck_Pearl.jpg', NULL),
(175, 'Nobel', NULL, '', '', 'Bunin', 'Ivan', NULL, NULL, 'Images/AwardedAuthors/Nobel/Bunin_Ivan.jpg', NULL),
(176, 'Nobel', NULL, '', '', 'Camus', 'Albert', NULL, NULL, 'Images/AwardedAuthors/Nobel/Camus_Albert.jpg', NULL),
(177, 'Nobel', NULL, '', '', 'Canetti', 'Elias', NULL, NULL, 'Images/AwardedAuthors/Nobel/Canetti_Elias.jpg', NULL),
(178, 'Nobel', NULL, '', '', 'Carducci', 'Giosue', NULL, NULL, 'Images/AwardedAuthors/Nobel/Carducci_Giosue.jpg', NULL),
(179, 'Nobel', NULL, '', '', 'Cela', 'Camilo Jose', NULL, NULL, 'Images/AwardedAuthors/Nobel/Cela_Camilo Jose.jpg', NULL),
(180, 'Nobel', NULL, '', '', 'Churchill', 'Winston', NULL, NULL, 'Images/AwardedAuthors/Nobel/Churchill_Winston.jpg', NULL),
(181, 'Nobel', NULL, '', '', 'Coetzee', 'John M', NULL, NULL, 'Images/AwardedAuthors/Nobel/Coetzee_John M.jpg', NULL),
(182, 'Nobel', NULL, '', '', 'Deledda', 'Grazia', NULL, NULL, 'Images/AwardedAuthors/Nobel/Deledda_Grazia.jpg', NULL),
(183, 'Nobel', NULL, '', '', 'du Gard', 'Roger', NULL, NULL, 'Images/AwardedAuthors/Nobel/du Gard_Roger.jpg', NULL),
(184, 'Nobel', NULL, '', '', 'Eizaguirre', 'Jose', NULL, NULL, 'Images/AwardedAuthors/Nobel/Eizaguirre_Jose.jpg', NULL),
(185, 'Nobel', NULL, '', '', 'Eliot', 'Thomas Stearns', NULL, NULL, 'Images/AwardedAuthors/Nobel/Eliot_Thomas Stearns.jpg', NULL),
(186, 'Nobel', NULL, '', '', 'Elytis', 'Odysseus', NULL, NULL, 'Images/AwardedAuthors/Nobel/Elytis_Odysseus.jpg', NULL),
(187, 'Nobel', NULL, '', '', 'Eucken', 'Rudolf', NULL, NULL, 'Images/AwardedAuthors/Nobel/Eucken_Rudolf.jpg', NULL),
(188, 'Nobel', NULL, '', '', 'Faulkner', 'William', NULL, NULL, 'Images/AwardedAuthors/Nobel/Faulkner_William.jpg', NULL),
(189, 'Nobel', NULL, '', '', 'Fo', 'Dario', NULL, NULL, 'Images/AwardedAuthors/Nobel/Fo_Dario.jpg', NULL),
(190, 'Nobel', NULL, '', '', 'France', 'Anatole', NULL, NULL, 'Images/AwardedAuthors/Nobel/France_Anatole.jpg', NULL),
(191, 'Nobel', NULL, '', '', 'Galsworthy', 'John', NULL, NULL, 'Images/AwardedAuthors/Nobel/Galsworthy_John.jpg', NULL),
(192, 'Nobel', NULL, '', '', 'Gide', 'Andre', NULL, NULL, 'Images/AwardedAuthors/Nobel/Gide_Andre.jpg', NULL),
(193, 'Nobel', NULL, '', '', 'Gjellerup', 'Karl', NULL, NULL, 'Images/AwardedAuthors/Nobel/Gjellerup_Karl.jpg', NULL),
(194, 'Nobel', NULL, '', '', 'Golding', 'William', NULL, NULL, 'Images/AwardedAuthors/Nobel/Golding_William.jpg', NULL),
(195, 'Nobel', NULL, '', '', 'Gordimer', 'Nadine', NULL, NULL, 'Images/AwardedAuthors/Nobel/Gordimer_Nadine.jpg', NULL),
(196, 'Nobel', NULL, '', '', 'Grass', 'Gunter', NULL, NULL, 'Images/AwardedAuthors/Nobel/Grass_Gunter.jpg', NULL),
(197, 'Nobel', NULL, '', '', 'Hamsun', 'Knut', NULL, NULL, 'Images/AwardedAuthors/Nobel/Hamsun_Knut.jpg', NULL),
(198, 'Nobel', NULL, '', '', 'Hauptmann', 'Gerhart', NULL, NULL, 'Images/AwardedAuthors/Nobel/Hauptmann_Gerhart.jpg', NULL),
(199, 'Nobel', NULL, '', '', 'Heaney', 'Seamus', NULL, NULL, 'Images/AwardedAuthors/Nobel/Heaney_Seamus.jpg', NULL),
(200, 'Nobel', NULL, '', '', 'Hemingway', 'Ernest', NULL, NULL, 'Images/AwardedAuthors/Nobel/Hemingway_Ernest.jpg', NULL),
(201, 'Nobel', NULL, '', '', 'Hesse', 'Hermann', NULL, NULL, 'Images/AwardedAuthors/Nobel/Hesse_Hermann.jpg', NULL),
(202, 'Nobel', NULL, '', '', 'Heyse', 'Paul', NULL, NULL, 'Images/AwardedAuthors/Nobel/Heyse_Paul.jpg', NULL),
(203, 'Nobel', NULL, '', '', 'Jelinek', 'Elfriede', NULL, NULL, 'Images/AwardedAuthors/Nobel/Jelinek_Elfriede.jpg', NULL),
(204, 'Nobel', NULL, '', '', 'Jensen', 'Johannes', NULL, NULL, 'Images/AwardedAuthors/Nobel/Jensen_Johannes.jpg', NULL),
(205, 'Nobel', NULL, '', '', 'Jimenez', 'Juan', NULL, NULL, 'Images/AwardedAuthors/Nobel/Jimenez_Juan.jpg', NULL),
(206, 'Nobel', NULL, '', '', 'Johnson', 'Eyvind', NULL, NULL, 'Images/AwardedAuthors/Nobel/Johnson_Eyvind.jpg', NULL),
(207, 'Nobel', NULL, '', '', 'Karlfeldt', 'Erik', NULL, NULL, 'Images/AwardedAuthors/Nobel/Karlfeldt_Erik.jpg', NULL),
(208, 'Nobel', NULL, '', '', 'Kawabata', 'Yasunari', NULL, NULL, 'Images/AwardedAuthors/Nobel/Kawabata_Yasunari.jpg', NULL),
(209, 'Nobel', NULL, '', '', 'Kertesz', 'Imre', NULL, NULL, 'Images/AwardedAuthors/Nobel/Kertesz_Imre.jpg', NULL),
(210, 'Nobel', NULL, '', '', 'Kipling', 'Rudyard', NULL, NULL, 'Images/AwardedAuthors/Nobel/Kipling_Rudyard.jpg', NULL),
(211, 'Nobel', NULL, '', '', 'Lagerkvist', 'Par', NULL, NULL, 'Images/AwardedAuthors/Nobel/Lagerkvist_Par.jpg', NULL),
(212, 'Nobel', NULL, '', '', 'Lagerlof', 'Selma', NULL, NULL, 'Images/AwardedAuthors/Nobel/Lagerlof_Selma.jpg', NULL),
(213, 'Nobel', NULL, '', '', 'Laxness', 'Halldor', NULL, NULL, 'Images/AwardedAuthors/Nobel/Laxness_Halldor.jpg', NULL),
(214, 'Nobel', NULL, '', '', 'Lewis', 'Sinclair', NULL, NULL, 'Images/AwardedAuthors/Nobel/Lewis_Sinclair.jpg', NULL),
(215, 'Nobel', NULL, '', '', 'Maeterlinck', 'Maurice', NULL, NULL, 'Images/AwardedAuthors/Nobel/Maeterlinck_Maurice.jpg', NULL),
(216, 'Nobel', NULL, '', '', 'Mahfouz', 'Naguib', NULL, NULL, 'Images/AwardedAuthors/Nobel/Mahfouz_Naguib.jpg', NULL),
(217, 'Nobel', NULL, '', '', 'Mann', 'Thomas', NULL, NULL, 'Images/AwardedAuthors/Nobel/Mann_Thomas.jpg', NULL),
(218, 'Nobel', NULL, '', '', 'Marquez', 'Gabriel Garcia', NULL, NULL, 'Images/AwardedAuthors/Nobel/Marquez_Gabriel Garcia.jpg', NULL),
(219, 'Nobel', NULL, '', '', 'Martinson', 'Harry', NULL, NULL, 'Images/AwardedAuthors/Nobel/Martinson_Harry.jpg', NULL),
(220, 'Nobel', NULL, '', '', 'Mauriac', 'Francois', NULL, NULL, 'Images/AwardedAuthors/Nobel/Mauriac_Francois.jpg', NULL),
(221, 'Nobel', NULL, '', '', 'Milosz', 'Czeslaw', NULL, NULL, 'Images/AwardedAuthors/Nobel/Milosz_Czeslaw.jpg', NULL),
(222, 'Nobel', NULL, '', '', 'Mistral', 'Frederic', NULL, NULL, 'Images/AwardedAuthors/Nobel/Mistral_Frederic.jpg', NULL),
(223, 'Nobel', NULL, '', '', 'Mistral', 'Gabriela', NULL, NULL, 'Images/AwardedAuthors/Nobel/Mistral_Gabriela.jpg', NULL),
(224, 'Nobel', NULL, '', '', 'Mommsen', 'Theodor', NULL, NULL, 'Images/AwardedAuthors/Nobel/Mommsen_Theodor.jpg', NULL),
(225, 'Nobel', NULL, '', '', 'Montale', 'Eugenio', NULL, NULL, 'Images/AwardedAuthors/Nobel/Montale_Eugenio.jpg', NULL),
(226, 'Nobel', NULL, '', '', 'Morrison', 'Toni', NULL, NULL, 'Images/AwardedAuthors/Nobel/Morrison_Toni.jpg', NULL),
(227, 'Nobel', NULL, '', '', 'Naipaul', 'V S', NULL, NULL, 'Images/AwardedAuthors/Nobel/Naipaul_V S.jpg', NULL),
(228, 'Nobel', NULL, '', '', 'Neruda', 'Pablo', NULL, NULL, 'Images/AwardedAuthors/Nobel/Neruda_Pablo.jpg', NULL),
(229, 'Nobel', NULL, '', '', 'Oe', 'Kenzaburo', NULL, NULL, 'Images/AwardedAuthors/Nobel/Oe_Kenzaburo.jpg', NULL),
(230, 'Nobel', NULL, '', '', 'ONeill', 'Eugene', NULL, NULL, 'Images/AwardedAuthors/Nobel/ONeill_Eugene.jpg', NULL),
(231, 'Nobel', NULL, '', '', 'Pamuk', 'Orhan', NULL, NULL, 'Images/AwardedAuthors/Nobel/Pamuk_Orhan.jpg', NULL),
(232, 'Nobel', NULL, '', '', 'Pasternak', 'Boris', NULL, NULL, 'Images/AwardedAuthors/Nobel/Pasternak_Boris.jpg', NULL),
(233, 'Nobel', NULL, '', '', 'Paz', 'Octavio', NULL, NULL, 'Images/AwardedAuthors/Nobel/Paz_Octavio.jpg', NULL),
(234, 'Nobel', NULL, '', '', 'Perse', 'Saint-John', NULL, NULL, 'Images/AwardedAuthors/Nobel/Perse_Saint-John.jpg', NULL),
(235, 'Nobel', NULL, '', '', 'Pinter', 'Harold', NULL, NULL, 'Images/AwardedAuthors/Nobel/Pinter_Harold.jpg', NULL),
(236, 'Nobel', NULL, '', '', 'Pirandello', 'Luigi', NULL, NULL, 'Images/AwardedAuthors/Nobel/Pirandello_Luigi.jpg', NULL),
(237, 'Nobel', NULL, '', '', 'Pontoppidan', 'Henrik', NULL, NULL, 'Images/AwardedAuthors/Nobel/Pontoppidan_Henrik.jpg', NULL),
(238, 'Nobel', NULL, '', '', 'Prudhomme', 'Sully', NULL, NULL, 'Images/AwardedAuthors/Nobel/Prudhomme_Sully.jpg', NULL),
(239, 'Nobel', NULL, '', '', 'Quasimodo', 'Salvatore', NULL, NULL, 'Images/AwardedAuthors/Nobel/Quasimodo_Salvatore.jpg', NULL),
(240, 'Nobel', NULL, '', '', 'Reymont', 'Wladyslaw', NULL, NULL, 'Images/AwardedAuthors/Nobel/Reymont_Wladyslaw.jpg', NULL),
(241, 'Nobel', NULL, '', '', 'Rolland', 'Romain', NULL, NULL, 'Images/AwardedAuthors/Nobel/Rolland_Romain.jpg', NULL),
(242, 'Nobel', NULL, '', '', 'Russell', 'Bertrand', NULL, NULL, 'Images/AwardedAuthors/Nobel/Russell_Bertrand.jpg', NULL),
(243, 'Nobel', NULL, '', '', 'Sachs', 'Nelly', NULL, NULL, 'Images/AwardedAuthors/Nobel/Sachs_Nelly.jpg', NULL),
(244, 'Nobel', NULL, '', '', 'Saramago', 'Jose', NULL, NULL, 'Images/AwardedAuthors/Nobel/Saramago_Jose.jpg', NULL),
(245, 'Nobel', NULL, '', '', 'Sartre', 'Jean-Paul', NULL, NULL, 'Images/AwardedAuthors/Nobel/Sartre_Jean-Paul.jpg', NULL),
(246, 'Nobel', NULL, '', '', 'Seferis', 'Giorgos', NULL, NULL, 'Images/AwardedAuthors/Nobel/Seferis_Giorgos.jpg', NULL),
(247, 'Nobel', NULL, '', '', 'Seifert', 'Jaroslav', NULL, NULL, 'Images/AwardedAuthors/Nobel/Seifert_Jaroslav.jpg', NULL),
(248, 'Nobel', NULL, '', '', 'Shaw', 'George Bernard', NULL, NULL, 'Images/AwardedAuthors/Nobel/Shaw_George Bernard.jpg', NULL),
(249, 'Nobel', NULL, '', '', 'Sholokhov', 'Mikhail', NULL, NULL, 'Images/AwardedAuthors/Nobel/Sholokhov_Mikhail.jpg', NULL),
(250, 'Nobel', NULL, '', '', 'Sienkiewicz', 'Henryk', NULL, NULL, 'Images/AwardedAuthors/Nobel/Sienkiewicz_Henryk.jpg', NULL),
(251, 'Nobel', NULL, '', '', 'Sillanpaa', 'Frans', NULL, NULL, 'Images/AwardedAuthors/Nobel/Sillanpaa_Frans.jpg', NULL),
(252, 'Nobel', NULL, '', '', 'Simon', 'Claude', NULL, NULL, 'Images/AwardedAuthors/Nobel/Simon_Claude.jpg', NULL),
(253, 'Nobel', NULL, '', '', 'Singer', 'Isaac Bashevis', NULL, NULL, 'Images/AwardedAuthors/Nobel/Singer_Isaac Bashevis.jpg', NULL),
(254, 'Nobel', NULL, '', '', 'Solzhenitsyn', 'Aleksandr', NULL, NULL, 'Images/AwardedAuthors/Nobel/Solzhenitsyn_Aleksandr.jpg', NULL),
(255, 'Nobel', NULL, '', '', 'Soyinka', 'Wole', NULL, NULL, 'Images/AwardedAuthors/Nobel/Soyinka_Wole.jpg', NULL),
(256, 'Nobel', NULL, '', '', 'Spitteler', 'Carl', NULL, NULL, 'Images/AwardedAuthors/Nobel/Spitteler_Carl.jpg', NULL),
(257, 'Nobel', NULL, '', '', 'Steinbeck', 'John', NULL, NULL, 'Images/AwardedAuthors/Nobel/Steinbeck_John.jpg', NULL),
(258, 'Nobel', NULL, '', '', 'Szymborska', 'Wislawa', NULL, NULL, 'Images/AwardedAuthors/Nobel/Szymborska_Wislawa.jpg', NULL),
(259, 'Nobel', NULL, '', '', 'Tagore', 'Rabindranath', NULL, NULL, 'Images/AwardedAuthors/Nobel/Tagore_Rabindranath.jpg', NULL),
(260, 'Nobel', NULL, '', '', 'Undset', 'Sigrid', NULL, NULL, 'Images/AwardedAuthors/Nobel/Undset_Sigrid.jpg', NULL),
(261, 'Nobel', NULL, '', '', 'Walcott', 'Derek', NULL, NULL, 'Images/AwardedAuthors/Nobel/Walcott_Derek.jpg', NULL),
(262, 'Nobel', NULL, '', '', 'White', 'Patrick', NULL, NULL, 'Images/AwardedAuthors/Nobel/White_Patrick.jpg', NULL),
(263, 'Nobel', NULL, '', '', 'Xingjian', 'Gao', NULL, NULL, 'Images/AwardedAuthors/Nobel/Xingjian_Gao.jpg', NULL),
(264, 'Nobel', NULL, '', '', 'Yeats', 'William Butler', NULL, NULL, 'Images/AwardedAuthors/Nobel/Yeats_William Butler.jpg', NULL),
(265, 'Booker Intl', NULL, '', '', 'Achebe', 'Chinua', NULL, NULL, 'Images/AwardedAuthors/Booker Intl/Achebe_Chinua.jpg', NULL),
(266, 'Booker Intl', NULL, '', '', 'Kadare', 'Ismael', NULL, NULL, 'Images/AwardedAuthors/Booker Intl/Kadare_Ismael.jpg', NULL),
(267, 'IMPAC', NULL, '', '', 'Houellebecq', 'Michel', NULL, NULL, 'Images/AwardedAuthors/IMPAC/Houellebecq_Michel.jpg', NULL),
(268, 'IMPAC', NULL, '', '', 'Jelloun', 'Tahar Ben', NULL, NULL, 'Images/AwardedAuthors/IMPAC/Jelloun_Tahar Ben.jpg', NULL),
(269, 'IMPAC', NULL, '', '', 'Jones', 'Edward P', NULL, NULL, 'Images/AwardedAuthors/IMPAC/Jones_Edward P.jpg', NULL),
(270, 'IMPAC', NULL, '', '', 'Malouf', 'David', NULL, NULL, 'Images/AwardedAuthors/IMPAC/Malouf_David.jpg', NULL),
(271, 'IMPAC', NULL, '', '', 'Marias', 'Javier', NULL, NULL, 'Images/AwardedAuthors/IMPAC/Marias_Javier.jpg', NULL),
(272, 'IMPAC', NULL, '', '', 'Miller', 'Andrew', NULL, NULL, 'Images/AwardedAuthors/IMPAC/Miller_Andrew.jpg', NULL),
(273, 'IMPAC', NULL, '', '', 'Muller', 'Herta', NULL, NULL, 'Images/AwardedAuthors/IMPAC/Muller_Herta.jpg', NULL),
(274, 'IMPAC', NULL, '', '', 'Pamuk', 'Orhan', NULL, NULL, 'Images/AwardedAuthors/IMPAC/Pamuk_Orhan.jpg', NULL),
(275, 'IMPAC', NULL, '', '', 'Toibin', 'Colm', NULL, NULL, 'Images/AwardedAuthors/IMPAC/Toibin_Colm.jpg', NULL),
(276, 'Commonwealth', NULL, '', '', 'Bail', 'Murray', NULL, NULL, 'Images/AwardedAuthors/Commonwealth/Bail_Murray.jpg', NULL),
(277, 'Commonwealth', NULL, '', '', 'Bernieres', 'Louis_de', NULL, NULL, 'Images/AwardedAuthors/Commonwealth/Bernieres_Louis_de.jpg', NULL),
(278, 'Commonwealth', NULL, '', '', 'Carey', 'Peter', NULL, NULL, 'Images/AwardedAuthors/Commonwealth/Carey_Peter.jpg', NULL),
(279, 'Commonwealth', NULL, '', '', 'Clarke', 'Austin', NULL, NULL, 'Images/AwardedAuthors/Commonwealth/Clarke_Austin.jpg', NULL),
(280, 'Commonwealth', NULL, '', '', 'Coetzee', 'John M', NULL, NULL, 'Images/AwardedAuthors/Commonwealth/Coetzee_John M.jpg', NULL),
(281, 'Commonwealth', NULL, '', '', 'Flanagan', 'Richard', NULL, NULL, 'Images/AwardedAuthors/Commonwealth/Flanagan_Richard.jpg', NULL),
(282, 'Commonwealth', NULL, '', '', 'Frame', 'Janet', NULL, NULL, 'Images/AwardedAuthors/Commonwealth/Frame_Janet.jpg', NULL),
(283, 'Commonwealth', NULL, '', '', 'Grenville', 'Kate', NULL, NULL, 'Images/AwardedAuthors/Commonwealth/Grenville_Kate.jpg', NULL),
(284, 'Commonwealth', NULL, '', '', 'Hill', 'Lawrence', NULL, NULL, 'Images/AwardedAuthors/Commonwealth/Hill_Lawrence.jpg', NULL),
(285, 'Commonwealth', NULL, '', '', 'Jones', 'Lloyd', NULL, NULL, 'Images/AwardedAuthors/Commonwealth/Jones_Lloyd.jpg', NULL),
(286, 'Commonwealth', NULL, '', '', 'Levy', 'Andrea', NULL, NULL, 'Images/AwardedAuthors/Commonwealth/Levy_Andrea.jpg', NULL),
(287, 'Commonwealth', NULL, '', '', 'Lovelace', 'Earl', NULL, NULL, 'Images/AwardedAuthors/Commonwealth/Lovelace_Earl.jpg', NULL),
(288, 'Commonwealth', NULL, '', '', 'Malouf', 'David', NULL, NULL, 'Images/AwardedAuthors/Commonwealth/Malouf_David.jpg', NULL),
(289, 'Commonwealth', NULL, '', '', 'Miller', 'Alex', NULL, NULL, 'Images/AwardedAuthors/Commonwealth/Miller_Alex.jpg', NULL),
(290, 'Commonwealth', NULL, '', '', 'Mistry', 'Rohinton', NULL, NULL, 'Images/AwardedAuthors/Commonwealth/Mistry_Rohinton.jpg', NULL),
(291, 'Commonwealth', NULL, '', '', 'Phillips', 'Caryl', NULL, NULL, 'Images/AwardedAuthors/Commonwealth/Phillips_Caryl.jpg', NULL),
(292, 'Commonwealth', NULL, '', '', 'Richler', 'Mordecai', NULL, NULL, 'Images/AwardedAuthors/Commonwealth/Richler_Mordecai.jpg', NULL),
(293, 'Commonwealth', NULL, '', '', 'Senior', 'Olive', NULL, NULL, 'Images/AwardedAuthors/Commonwealth/Senior_Olive.jpg', NULL),
(294, 'Commonwealth', NULL, '', '', 'Seth', 'Vikram', NULL, NULL, 'Images/AwardedAuthors/Commonwealth/Seth_Vikram.jpg', NULL),
(295, 'Nobel', NULL, '', '', 'Lessing', 'Doris', NULL, NULL, 'Images/AwardedAuthors/Nobel/Lessing_Doris.jpg', NULL),
(296, 'Nobel', NULL, '', '', 'Clezio', 'Jean-Marie Le', NULL, NULL, 'Images/AwardedAuthors/Nobel/Clezio_Jean-Marie Le.jpg', NULL),
(297, 'NBA', NULL, '', '', 'Algren', 'Nelson', NULL, NULL, 'Images/AwardedAuthors/NBA/Algren_Nelson.jpg', NULL),
(298, 'NBA', NULL, '', '', 'Barrett', 'Andrea', NULL, NULL, 'Images/AwardedAuthors/NBA/Barrett_Andrea.jpg', NULL),
(299, 'NBA', NULL, '', '', 'Barth', 'John', NULL, NULL, 'Images/AwardedAuthors/NBA/Barth_John.jpg', NULL),
(300, 'NBA', NULL, '', '', 'Bellow', 'Saul', NULL, NULL, 'Images/AwardedAuthors/NBA/Bellow_Saul.jpg', NULL),
(301, 'NBA', NULL, '', '', 'Casey', 'John', NULL, NULL, 'Images/AwardedAuthors/NBA/Casey_John.jpg', NULL),
(302, 'NBA', NULL, '', '', 'Cheever', 'John', NULL, NULL, 'Images/AwardedAuthors/NBA/Cheever_John.jpg', NULL),
(303, 'NBA', NULL, '', '', 'DeLillo', 'Don', NULL, NULL, 'Images/AwardedAuthors/NBA/DeLillo_Don.jpg', NULL),
(304, 'NBA', NULL, '', '', 'Dexter', 'Pete', NULL, NULL, 'Images/AwardedAuthors/NBA/Dexter_Pete.jpg', NULL),
(305, 'NBA', NULL, '', '', 'Doctorow', 'E L', NULL, NULL, 'Images/AwardedAuthors/NBA/Doctorow_E L.jpg', NULL),
(306, 'NBA', NULL, '', '', 'Ellison', 'Ralph', NULL, NULL, 'Images/AwardedAuthors/NBA/Ellison_Ralph.jpg', NULL),
(307, 'NBA', NULL, '', '', 'Faulkner', 'William', NULL, NULL, 'Images/AwardedAuthors/NBA/Faulkner_William.jpg', NULL),
(308, 'NBA', NULL, '', '', 'Franzen', 'Jonathan', NULL, NULL, 'Images/AwardedAuthors/NBA/Franzen_Jonathan.jpg', NULL),
(309, 'NBA', NULL, '', '', 'Frazier', 'Charles', NULL, NULL, 'Images/AwardedAuthors/NBA/Frazier_Charles.jpg', NULL),
(310, 'NBA', NULL, '', '', 'Gaddis', 'William', NULL, NULL, 'Images/AwardedAuthors/NBA/Gaddis_William.jpg', NULL),
(311, 'NBA', NULL, '', '', 'Gilchrist', 'Ellen', NULL, NULL, 'Images/AwardedAuthors/NBA/Gilchrist_Ellen.jpg', NULL),
(312, 'NBA', NULL, '', '', 'Glass', 'Julia', NULL, NULL, 'Images/AwardedAuthors/NBA/Glass_Julia.jpg', NULL),
(313, 'NBA', NULL, '', '', 'Hazzard', 'Shirley', NULL, NULL, 'Images/AwardedAuthors/NBA/Hazzard_Shirley.jpg', NULL),
(314, 'NBA', NULL, '', '', 'Heinemann', 'Larry', NULL, NULL, 'Images/AwardedAuthors/NBA/Heinemann_Larry.jpg', NULL),
(315, 'NBA', NULL, '', '', 'Irving', 'John', NULL, NULL, 'Images/AwardedAuthors/NBA/Irving_John.jpg', NULL),
(316, 'NBA', NULL, '', '', 'Jin', 'Ha', NULL, NULL, 'Images/AwardedAuthors/NBA/Jin_Ha.jpg', NULL),
(317, 'NBA', NULL, '', '', 'Johnson', 'Charles R', NULL, NULL, 'Images/AwardedAuthors/NBA/Johnson_Charles R.jpg', NULL),
(318, 'NBA', NULL, '', '', 'Johnson', 'Denis', NULL, NULL, 'Images/AwardedAuthors/NBA/Johnson_Denis.jpg', NULL),
(319, 'NBA', NULL, '', '', 'Jones', 'James', NULL, NULL, 'Images/AwardedAuthors/NBA/Jones_James.jpg', NULL),
(320, 'NBA', NULL, '', '', 'Kosinski', 'Jerzy', NULL, NULL, 'Images/AwardedAuthors/NBA/Kosinski_Jerzy.jpg', NULL),
(321, 'NBA', NULL, '', '', 'Malamud', 'Bernard', NULL, NULL, 'Images/AwardedAuthors/NBA/Malamud_Bernard.jpg', NULL),
(322, 'NBA', NULL, '', '', 'Matthiessen', 'Peter', NULL, NULL, 'Images/AwardedAuthors/NBA/Matthiessen_Peter.jpg', NULL),
(323, 'NBA', NULL, '', '', 'Maxwell', 'William Keepers', NULL, NULL, 'Images/AwardedAuthors/NBA/Maxwell_William Keepers.jpg', NULL),
(324, 'NBA', NULL, '', '', 'McCarthy', 'Cormac', NULL, NULL, 'Images/AwardedAuthors/NBA/McCarthy_Cormac.jpg', NULL),
(325, 'NBA', NULL, '', '', 'McDermott', 'Alice', NULL, NULL, 'Images/AwardedAuthors/NBA/McDermott_Alice.jpg', NULL),
(326, 'NBA', NULL, '', '', 'Morris', 'Wright', NULL, NULL, 'Images/AwardedAuthors/NBA/Morris_Wright.jpg', NULL),
(327, 'NBA', NULL, '', '', 'Oates', 'Joyce Carol', NULL, NULL, 'Images/AwardedAuthors/NBA/Oates_Joyce Carol.jpg', NULL),
(328, 'NBA', NULL, '', '', 'OBrien', 'Tim', NULL, NULL, 'Images/AwardedAuthors/NBA/OBrien_Tim.jpg', NULL),
(329, 'NBA', NULL, '', '', 'OConnor', 'Flannery', NULL, NULL, 'Images/AwardedAuthors/NBA/OConnor_Flannery.jpg', NULL),
(330, 'NBA', NULL, '', '', 'OHara', 'John', NULL, NULL, 'Images/AwardedAuthors/NBA/OHara_John.jpg', NULL),
(331, 'NBA', NULL, '', '', 'Percy', 'Walker', NULL, NULL, 'Images/AwardedAuthors/NBA/Percy_Walker.jpg', NULL),
(332, 'NBA', NULL, '', '', 'Porter', 'Katherine Ann', NULL, NULL, 'Images/AwardedAuthors/NBA/Porter_Katherine Ann.jpg', NULL),
(333, 'NBA', NULL, '', '', 'Powers', 'J F', NULL, NULL, 'Images/AwardedAuthors/NBA/Powers_J F.jpg', NULL),
(334, 'NBA', NULL, '', '', 'Powers', 'Richard', NULL, NULL, 'Images/AwardedAuthors/NBA/Powers_Richard.jpg', NULL),
(335, 'NBA', NULL, '', '', 'Proulx', 'Annie', NULL, NULL, 'Images/AwardedAuthors/NBA/Proulx_Annie.jpg', NULL),
(336, 'NBA', NULL, '', '', 'Pynchon', 'Thomas', NULL, NULL, 'Images/AwardedAuthors/NBA/Pynchon_Thomas.jpg', NULL),
(337, 'NBA', NULL, '', '', 'Richter', 'Conrad', NULL, NULL, 'Images/AwardedAuthors/NBA/Richter_Conrad.jpg', NULL),
(338, 'NBA', NULL, '', '', 'Roth', 'Philip', NULL, NULL, 'Images/AwardedAuthors/NBA/Roth_Philip.jpg', NULL),
(339, 'NBA', NULL, '', '', 'Rush', 'Norman', NULL, NULL, 'Images/AwardedAuthors/NBA/Rush_Norman.jpg', NULL),
(340, 'NBA', NULL, '', '', 'Settle', 'Mary Lee', NULL, NULL, 'Images/AwardedAuthors/NBA/Settle_Mary Lee.jpg', NULL),
(341, 'NBA', NULL, '', '', 'Singer', 'Isaac Bashevis', NULL, NULL, 'Images/AwardedAuthors/NBA/Singer_Isaac Bashevis.jpg', NULL),
(342, 'NBA', NULL, '', '', 'Sontag', 'Susan', NULL, NULL, 'Images/AwardedAuthors/NBA/Sontag_Susan.jpg', NULL),
(343, 'NBA', NULL, '', '', 'Stegner', 'Wallace', NULL, NULL, 'Images/AwardedAuthors/NBA/Stegner_Wallace.jpg', NULL),
(344, 'NBA', NULL, '', '', 'Stone', 'Robert', NULL, NULL, 'Images/AwardedAuthors/NBA/Stone_Robert.jpg', NULL),
(345, 'NBA', NULL, '', '', 'Styron', 'William', NULL, NULL, 'Images/AwardedAuthors/NBA/Styron_William.jpg', NULL),
(346, 'NBA', NULL, '', '', 'Tuck', 'Lily', NULL, NULL, 'Images/AwardedAuthors/NBA/Tuck_Lily.jpg', NULL),
(347, 'NBA', NULL, '', '', 'Updike', 'John', NULL, NULL, 'Images/AwardedAuthors/NBA/Updike_John.jpg', NULL),
(348, 'NBA', NULL, '', '', 'Vollmann', 'William Tanner', NULL, NULL, 'Images/AwardedAuthors/NBA/Vollmann_William Tanner.jpg', NULL),
(349, 'NBA', NULL, '', '', 'Walker', 'Alice', NULL, NULL, 'Images/AwardedAuthors/NBA/Walker_Alice.jpg', NULL),
(350, 'NBA', NULL, '', '', 'Welty', 'Eudora', NULL, NULL, 'Images/AwardedAuthors/NBA/Welty_Eudora.jpg', NULL),
(351, 'NBA', NULL, '', '', 'Wilder', 'Thornton', NULL, NULL, 'Images/AwardedAuthors/NBA/Wilder_Thornton.jpg', NULL),
(352, 'NBA', NULL, '', '', 'Williams', 'Stoner', NULL, NULL, 'Images/AwardedAuthors/NBA/Williams_Stoner.jpg', NULL),
(353, 'NBA', NULL, '', '', 'Williams', 'Thomas', NULL, NULL, 'Images/AwardedAuthors/NBA/Williams_Thomas.jpg', NULL),
(354, 'PEN-Faulkner', NULL, '', '', 'Abish', 'Walter', NULL, NULL, 'Images/AwardedAuthors/PEN-Faulkner/Abish_Walter.jpg', NULL),
(355, 'PEN-Faulkner', NULL, '', '', 'Berriault', 'Gina', NULL, NULL, 'Images/AwardedAuthors/PEN-Faulkner/Berriault_Gina.jpg', NULL),
(356, 'PEN-Faulkner', NULL, '', '', 'Boyle', 'T Coraghessan', NULL, NULL, 'Images/AwardedAuthors/PEN-Faulkner/Boyle_T Coraghessan.jpg', NULL),
(357, 'PEN-Faulkner', NULL, '', '', 'Bradley', 'David', NULL, NULL, 'Images/AwardedAuthors/PEN-Faulkner/Bradley_David.jpg', NULL),
(358, 'PEN-Faulkner', NULL, '', '', 'Christensen', 'Kate', NULL, NULL, 'Images/AwardedAuthors/PEN-Faulkner/Christensen_Kate.jpg', NULL),
(359, 'PEN-Faulkner', NULL, '', '', 'Cunningham', 'Michael', NULL, NULL, 'Images/AwardedAuthors/PEN-Faulkner/Cunningham_Michael.jpg', NULL),
(360, 'PEN-Faulkner', NULL, '', '', 'DeLillo', 'Don', NULL, NULL, 'Images/AwardedAuthors/PEN-Faulkner/DeLillo_Don.jpg', NULL),
(361, 'PEN-Faulkner', NULL, '', '', 'Doctorow', 'E L', NULL, NULL, 'Images/AwardedAuthors/PEN-Faulkner/Doctorow_E L.jpg', NULL),
(362, 'PEN-Faulkner', NULL, '', '', 'Ford', 'Richard', NULL, NULL, 'Images/AwardedAuthors/PEN-Faulkner/Ford_Richard.jpg', NULL),
(363, 'PEN-Faulkner', NULL, '', '', 'Guterson', 'David', NULL, NULL, 'Images/AwardedAuthors/PEN-Faulkner/Guterson_David.jpg', NULL),
(364, 'PEN-Faulkner', NULL, '', '', 'Jin', 'Ha', NULL, NULL, 'Images/AwardedAuthors/PEN-Faulkner/Jin_Ha.jpg', NULL),
(365, 'PEN-Faulkner', NULL, '', '', 'Murray', 'Sabina', NULL, NULL, 'Images/AwardedAuthors/PEN-Faulkner/Murray_Sabina.jpg', NULL),
(366, 'PEN-Faulkner', NULL, '', '', 'Olson', 'Toby', NULL, NULL, 'Images/AwardedAuthors/PEN-Faulkner/Olson_Toby.jpg', NULL),
(367, 'PEN-Faulkner', NULL, '', '', 'Patchett', 'Ann', NULL, NULL, 'Images/AwardedAuthors/PEN-Faulkner/Patchett_Ann.jpg', NULL),
(368, 'PEN-Faulkner', NULL, '', '', 'Proulx', 'Annie', NULL, NULL, 'Images/AwardedAuthors/PEN-Faulkner/Proulx_Annie.jpg', NULL),
(369, 'PEN-Faulkner', NULL, '', '', 'Roth', 'Philip', NULL, NULL, 'Images/AwardedAuthors/PEN-Faulkner/Roth_Philip.jpg', NULL),
(370, 'PEN-Faulkner', NULL, '', '', 'Salter', 'James', NULL, NULL, 'Images/AwardedAuthors/PEN-Faulkner/Salter_James.jpg', NULL),
(371, 'PEN-Faulkner', NULL, '', '', 'Taylor', 'Peter', NULL, NULL, 'Images/AwardedAuthors/PEN-Faulkner/Taylor_Peter.jpg', NULL),
(372, 'PEN-Faulkner', NULL, '', '', 'Updike', 'John', NULL, NULL, 'Images/AwardedAuthors/PEN-Faulkner/Updike_John.jpg', NULL),
(373, 'PEN-Faulkner', NULL, '', '', 'Wideman', 'John Edgar', NULL, NULL, 'Images/AwardedAuthors/PEN-Faulkner/Wideman_John Edgar.jpg', NULL),
(374, 'PEN-Faulkner', NULL, '', '', 'Wiley', 'Richard', NULL, NULL, 'Images/AwardedAuthors/PEN-Faulkner/Wiley_Richard.jpg', NULL),
(375, 'PEN-Faulkner', NULL, '', '', 'Wolff', 'Tobias', NULL, NULL, 'Images/AwardedAuthors/PEN-Faulkner/Wolff_Tobias.jpg', NULL),
(376, 'PEN-Faulkner', NULL, '', '', 'Zabor', 'Rafi', NULL, NULL, 'Images/AwardedAuthors/PEN-Faulkner/Zabor_Rafi.jpg', NULL),
(377, 'Booker', NULL, '', '', 'Adiga', 'Aravind', NULL, NULL, 'Images/AwardedAuthors/Booker/Adiga_Aravind.jpg', NULL),
(378, 'NBCC', NULL, '', '', 'Berriault', 'Gina', NULL, NULL, 'Images/AwardedAuthors/NBCC/Berriault_Gina.jpg', NULL),
(379, 'NBCC', NULL, '', '', 'Cheever', 'John', NULL, NULL, 'Images/AwardedAuthors/NBCC/Cheever_John.jpg', NULL),
(380, 'NBCC', NULL, '', '', 'Crace', 'Jim', NULL, NULL, 'Images/AwardedAuthors/NBCC/Crace_Jim.jpg', NULL),
(381, 'NBCC', NULL, '', '', 'Desai', 'Kiran', NULL, NULL, 'Images/AwardedAuthors/NBCC/Desai_Kiran.jpg', NULL),
(382, 'NBCC', NULL, '', '', 'Diaz', 'Junot', NULL, NULL, 'Images/AwardedAuthors/NBCC/Diaz_Junot.jpg', NULL),
(383, 'NBCC', NULL, '', '', 'Doctorow', 'E L', NULL, NULL, 'Images/AwardedAuthors/NBCC/Doctorow_E L.jpg', NULL),
(384, 'NBCC', NULL, '', '', 'Elkin', 'Stanley', NULL, NULL, 'Images/AwardedAuthors/NBCC/Elkin_Stanley.jpg', NULL),
(385, 'NBCC', NULL, '', '', 'Erdrich', 'Louise', NULL, NULL, 'Images/AwardedAuthors/NBCC/Erdrich_Louise.jpg', NULL),
(386, 'NBCC', NULL, '', '', 'Fitzgerald', 'Penelope', NULL, NULL, 'Images/AwardedAuthors/NBCC/Fitzgerald_Penelope.jpg', NULL),
(387, 'NBCC', NULL, '', '', 'Flanagan', 'Tom', NULL, NULL, 'Images/AwardedAuthors/NBCC/Flanagan_Tom.jpg', NULL),
(388, 'NBCC', NULL, '', '', 'Gaines', 'Ernest J', NULL, NULL, 'Images/AwardedAuthors/NBCC/Gaines_Ernest J.jpg', NULL),
(389, 'NBCC', NULL, '', '', 'Gardner', 'John', NULL, NULL, 'Images/AwardedAuthors/NBCC/Gardner_John.jpg', NULL),
(390, 'NBCC', NULL, '', '', 'Hazzard', 'Shirley', NULL, NULL, 'Images/AwardedAuthors/NBCC/Hazzard_Shirley.jpg', NULL),
(391, 'NBCC', NULL, '', '', 'Jones', 'Edward P', NULL, NULL, 'Images/AwardedAuthors/NBCC/Jones_Edward P.jpg', NULL),
(392, 'NBCC', NULL, '', '', 'Kennedy', 'William', NULL, NULL, 'Images/AwardedAuthors/NBCC/Kennedy_William.jpg', NULL),
(393, 'NBCC', NULL, '', '', 'Lethrem', 'Jonathan', NULL, NULL, 'Images/AwardedAuthors/NBCC/Lethrem_Jonathan.jpg', NULL),
(394, 'NBCC', NULL, '', '', 'McCarthy', 'Cormac', NULL, NULL, 'Images/AwardedAuthors/NBCC/McCarthy_Cormac.jpg', NULL),
(395, 'NBCC', NULL, '', '', 'McEwan', 'Ian', NULL, NULL, 'Images/AwardedAuthors/NBCC/McEwan_Ian.jpg', NULL),
(396, 'NBCC', NULL, '', '', 'Morrison', 'Toni', NULL, NULL, 'Images/AwardedAuthors/NBCC/Morrison_Toni.jpg', NULL),
(397, 'NBCC', NULL, '', '', 'Mukherjee', 'Bharati', NULL, NULL, 'Images/AwardedAuthors/NBCC/Mukherjee_Bharati.jpg', NULL),
(398, 'NBCC', NULL, '', '', 'Munro', 'Alice', NULL, NULL, 'Images/AwardedAuthors/NBCC/Munro_Alice.jpg', NULL),
(399, 'NBCC', NULL, '', '', 'Robinson', 'Marilynne', NULL, NULL, 'Images/AwardedAuthors/NBCC/Robinson_Marilynne.jpg', NULL),
(400, 'NBCC', NULL, '', '', 'Roth', 'Philip', NULL, NULL, 'Images/AwardedAuthors/NBCC/Roth_Philip.jpg', NULL),
(401, 'NBCC', NULL, '', '', 'Sebald', 'W G', NULL, NULL, 'Images/AwardedAuthors/NBCC/Sebald_W G.jpg', NULL),
(402, 'NBCC', NULL, '', '', 'Shields', 'Carol', NULL, NULL, 'Images/AwardedAuthors/NBCC/Shields_Carol.jpg', NULL),
(403, 'NBCC', NULL, '', '', 'Smiley', 'Jane', NULL, NULL, 'Images/AwardedAuthors/NBCC/Smiley_Jane.jpg', NULL),
(404, 'NBCC', NULL, '', '', 'Taylor', 'Peter', NULL, NULL, 'Images/AwardedAuthors/NBCC/Taylor_Peter.jpg', NULL),
(405, 'NBCC', NULL, '', '', 'Tyler', 'Ann', NULL, NULL, 'Images/AwardedAuthors/NBCC/Tyler_Ann.jpg', NULL),
(406, 'NBCC', NULL, '', '', 'Updike', 'John', NULL, NULL, 'Images/AwardedAuthors/NBCC/Updike_John.jpg', NULL);
