INSERT INTO BackgroundBooks (BookID, Area, LastName, FirstName, Title, ImageURL, ISBN) VALUES (1, 'African', 'Chinweizu', '', 'African Fiction and Poetry and their Critics', NULL, NULL),
(2, 'African', 'Chinweizu', '', 'Voices from Twentieth-Century Africa: Griots and Towncriers', NULL, NULL),
(3, 'African', 'Finnegan', 'Ruth', 'Oral Literature in Africa', NULL, NULL),
(4, 'African', 'Goodwin', 'Ken', 'Understanding African Poetry: A Study of Ten Poets', NULL, NULL),
(5, 'African', 'Gordimer', 'Nadine', 'The Black Interpreters: Notes on African Writing', NULL, NULL),
(6, 'African', 'Ndebele', 'Njabulo', 'The Rediscovery of the Ordinary: Essays on South African Literature and Culture', NULL, NULL),
(7, 'African', 'Owomoyela', 'Oyekan', 'A History of Twentieth Century African Literatures', NULL, NULL),
(8, 'African', 'Ngugi', 'Wa Thiong''o', 'Moving the Centre: The Struggle for Cultural Freedoms', NULL, NULL),
(9, 'African', 'Nkosi', 'Lewis', 'Home and Exile', NULL, NULL),
(10, 'African', 'Roscoe', 'Adrian', 'Mother is Gold: A Study in West African Literature', NULL, NULL),
(11, 'Arabic', 'Allen', 'Roger', 'The Arabic Novel: An Historical and Critical Introduction', NULL, NULL),
(12, 'Arabic', 'Badawi', 'M. M.', 'A Short History of Modern Arabic Literature', NULL, NULL),
(13, 'Arabic', 'Badawi', 'M. M. ed.', 'The Cambridge History of Arabic Literature', NULL, NULL),
(14, 'Arabic', 'Cachia', 'Pierre', 'An Overview of Modern Arabic Literature', NULL, NULL),
(19, 'Brazilian', 'King', 'John', 'Modern Latin American Fiction', NULL, NULL),
(20, 'Brazilian', 'Brasil', 'Emanuel', 'Brazilian Poetry: 1950-1980', NULL, NULL),
(21, 'Brazilian', 'Lowe', 'Elizabeth', 'The City in Bazilian Literature', NULL, NULL),
(22, 'Brazilian', 'Patai', 'Daphne', 'Myth and Reality in Brazilian Literature', NULL, NULL),
(23, 'Brazilian', 'Perrone', 'Charles', 'Masters of Contemporary Brazilian Song', NULL, NULL),
(24, 'Brazilian', 'Schwarz', 'Roberto', 'Misplaced Ideas: Essays on Brazilian Culture', NULL, NULL),
(25, 'Brazilian', 'Stern', 'Irvin', 'Dictionary of Brazilian Literature', NULL, NULL),
(26, 'Canadian', 'Atwood', 'Margaret', 'The New Oxford Book of Canadian Verse in English', NULL, NULL),
(27, 'Canadian', 'Frye', 'Northrop', 'The Bush Garden: Essays on the Canadian Imagination', NULL, NULL),
(28, 'Canadian', 'Hutcheon', 'Linda', 'The Canadian Postmodern: A Study of Contemporary English-Canadian Fiction', NULL, NULL),
(29, 'Canadian', 'Keith', 'W. J.', 'An Independent Stance: Essays on English-Canadian Criticism and Fiction', NULL, NULL),
(30, 'Canadian', 'Lecker', 'Robert', 'Canadian Canons: Essays in Literary Value', NULL, NULL),
(31, 'Canadian', 'New', 'W. H.', 'The Literary History of Canada', NULL, NULL),
(32, 'Canadian', 'Stouck', 'David', 'Major Canadian Authors: A Critical Introduction to Canadian Literature in English', NULL, NULL),
(33, 'Canadian', 'Wasserman', 'Jerry', 'Modern Canadian Plays, i and ii', NULL, NULL),
(34, 'Chinese', 'Anderson', 'Marston', 'The Limits of Realism: Chinese Fiction in the Revolutionary Period', NULL, NULL),
(35, 'Chinese', '-', '', 'Best Chinese Stories (1949-1989)', NULL, NULL),
(36, 'Chinese', 'Chang', 'Sung-sheng Yvonne', 'Modernism and the Nativist Resistance: Contemporary Chinese Fiction from Taiwan', NULL, NULL),
(37, 'Chinese', 'Duke', 'Michael S.', 'Contemporary Chinese Literature: An Anthology of Post-Mao Fiction and Poetry', NULL, NULL),
(38, 'Chinese', 'Dule', 'Michael S.', 'Modern Chinese Women Writers: Critical Appraisals', NULL, NULL),
(39, 'Chinese', 'Larson', 'Wendy', 'Inside Out: Modernism and Post-Modernism in Chinise Literary Culture', NULL, NULL),
(40, 'Chinese', 'Martin', 'Helmut', 'Modern Chinese Writers: Self Portrayals', NULL, NULL),
(41, 'Chinese', 'Widmer', 'Ellen', 'From May Fourth to June Fourth: Fiction and Film in Twentieth-Century China', NULL, NULL),
(42, 'Chinese', 'Zhao', 'Henry Y. H.', 'Under Sky Underground: Chinese Writing Today', NULL, NULL),
(43, 'Czech and Slovakian', 'Goetz-Stankiewicz', 'Marketa', 'Good-bye Samizdat', NULL, NULL),
(44, 'Czech and Slovakian', 'Harkins', 'William E.', 'Czech Literature since 1956: A Symposium', NULL, NULL),
(45, 'Czech and Slovakian', 'Liehm', 'Antonin', 'The Writing on the Wall', NULL, NULL),
(46, 'Czech and Slovakian', '-', ' ', 'Modern Slavic Literatures, ii', NULL, NULL),
(47, 'Czech and Slovakian', 'Novak', 'Arne', 'Czech Literature', NULL, NULL),
(48, 'Czech and Slovakian', 'Pynsent', 'Robert B.', 'Modern Slovak Prose', NULL, NULL),
(49, 'Czech and Slovakian', 'Trensky', 'Paul I.', 'Czech Drama since World War II', NULL, NULL),
(50, 'British', 'Bergonzi', 'Bernard', 'The Myth of Modernism and Twentieth Century Literature', NULL, NULL),
(51, 'British', 'Bradbury', 'Malcolm', 'The Modern British Novel', NULL, NULL),
(52, 'British', 'Bradbury', 'Malcolm', 'The Novel Today: Contemporary Writers on Modern Fiction', NULL, NULL),
(53, 'British', 'Everett', 'Barbara', 'Poets in their Time', NULL, NULL),
(54, 'British', 'Haffenden', 'John', 'Novelists in Interview', NULL, NULL),
(55, 'British', 'Richetti', 'John', 'The Columbia History of the British Novel', NULL, NULL),
(56, 'British', 'Tredell', 'Nicholas', 'Conversations with Critics', NULL, NULL),
(57, 'French', 'Brosman', 'C. S.', 'French Novelists since 1960', NULL, NULL),
(58, 'French', 'Caws', 'M. A.', 'The Inner Theatre of Recent French Poetry', NULL, NULL),
(59, 'French', 'Roudiez', 'L.', 'French Fiction Revisited', NULL, NULL),
(60, 'French', 'Stamelman', 'R.', 'Lost beyond Telling: Representations of Death and Absence in Modern French Poetry', NULL, NULL),
(61, 'German', 'Bullivant', 'K.', 'Realism Today: Aspects of the Contemporary West German Novel', NULL, NULL),
(62, 'German', 'Bullivant', 'K.', 'After the ''Death'' of Literature: West German Writing of the 1970s', NULL, NULL),
(63, 'German', 'Bullivant', 'K.', 'The Future of German Literature', NULL, NULL),
(64, 'German', 'Burns', 'R. A.', 'Protest and Democracy in West Germany: Extra-parliamentary Opposition and the Democratic Agenda', NULL, NULL),
(65, 'German', 'Demetz', 'P.', 'After the Fires: Writing in the Germanies, Austria, and Switzerland', NULL, NULL),
(66, 'German', 'Parkes', 'K. S.', 'Writers and Politics in West Germany', NULL, NULL),
(67, 'German', 'Reid', 'J. H.', 'Writing without Taboos: The New East German Literature', NULL, NULL),
(68, 'German', 'Thomas', 'R. H.', 'Literature in Upheaval', NULL, NULL),
(69, 'German', 'Thomas', 'R. H.', 'The German Novel and the Affluent Society', NULL, NULL),
(70, 'German', 'Wallace', 'I.', 'The Writer and Society in the GDR', NULL, NULL),
(71, 'Greek', 'Beaton', 'Roderick', 'An Introduction to Modern Greek Literature', NULL, NULL),
(72, 'Hungarian', 'Czigany', 'L.', 'Oxford History of Hungarian Literature: From the Earliest Times to the Present', NULL, NULL),
(73, 'Hungarian', 'Pynsent', 'R. B.', 'Everyman Companion to East European Literature', NULL, NULL),
(74, 'Hungarian', 'Pynsent', 'R. B.', 'Encyclopedia of East European Literature', NULL, NULL),
(75, 'Indian', 'Mukherjee', 'Meenakshi', 'The Twice Born Fiction: Themes and Techniques of the Indian Novel in English', NULL, NULL),
(76, 'Indian', 'Mukherjee', 'Meenakshi', 'Realism and Reality: The Novel and Society in India', NULL, NULL),
(77, 'Indian', 'Rushdie', 'Salman', 'Imaginary Homelands: Essays and Criticism 1981-1991', NULL, NULL),
(78, 'Indian', 'Walsh', 'William', 'Indian Literature in English', NULL, NULL),
(79, 'Irish', 'Andrews', 'Elmer', 'Contemporary Irish Poetry', NULL, NULL),
(80, 'Irish', 'Calalahan', 'James M.', 'The Irish Novel', NULL, NULL),
(81, 'Irish', 'Dawe', 'G.', 'The Poet''s Place', NULL, NULL),
(82, 'Irish', 'Donoghue', 'Denis', 'We Irish', NULL, NULL),
(83, 'Irish', 'Foster', 'John Wilson', 'Forces and Themes in Ulster Fiction', NULL, NULL),
(84, 'Irish', 'Johnson', 'Dillon', 'Irish Poetry after Joyce', NULL, NULL),
(85, 'Israeli', 'Alter', 'Robert', 'After the Tradition', NULL, NULL),
(86, 'Israeli', 'Fuchs', 'Esther', 'Israeli Mythologies: Women in Contemporary Hebrew Fiction', NULL, NULL),
(87, 'Israeli', 'Shaked', 'Gershon', 'The Shadows Within: Essays on Modern Jewish Writers', NULL, NULL),
(88, 'Israeli', 'Sinclair', 'Clive', 'Diaspora Blues: A View of Israel', NULL, NULL),
(89, 'Israeli', 'Sonntag', 'Jacob', 'New Writing from Israel', NULL, NULL),
(90, 'Israeli', 'Yudkin', 'Leon', 'Beyond Sequence: Current Israeli Fiction and its Context', NULL, NULL),
(91, 'Italian', 'Caesar', 'Michael', 'Writers and Society in Contemporary Italy', NULL, NULL),
(92, 'Italian', 'Baranski', 'Z.', 'The New Italian Novel', NULL, NULL),
(93, 'Japanese', 'Gessel', 'Van C.', 'The Showa Anthology: Modern Japanese Short Stories, ii: 1961-1984', NULL, NULL),
(94, 'Japanese', 'Hibbett', 'Howard', 'Contemporary Japanese Literature', NULL, NULL),
(95, 'Japanese', 'Lewell', 'John', 'Modern Japanese Novelists: A Biographical Dictionary', NULL, NULL),
(96, 'Japanese', 'Masao', 'Miyoshi', 'Accomplices of Silence', NULL, NULL),
(97, 'Japanese', 'Masao', 'Miyoshi', 'Off Center', NULL, NULL),
(98, 'Japanese', 'Yukiko', 'Tanaka', 'This Kind of Woman: Ten Stories by Japanese Women Writers, 1960-1976', NULL, NULL),
(99, 'New Zealandic', 'Alley', 'Elizabeth', 'In the Same Room: Conversations with New Zealand Writers', NULL, NULL),
(100, 'New Zealandic', 'Baysting', 'Arthur', 'The Young New Zealand Poets', NULL, NULL),
(101, 'New Zealandic', 'Edmond', 'Murray', 'The New Poets: Initiatives in New Zealand Poetry', NULL, NULL),
(102, 'New Zealandic', 'Evans', 'Patrick', 'The Penguin History of New Zealand Literature', NULL, NULL),
(103, 'New Zealandic', 'Jackson', 'MacDonald P.', 'The Oxford Anthology of New Zealand Writing since 1945', NULL, NULL),
(104, 'New Zealandic', 'Morrissey', 'Michael', 'The New Fiction', NULL, NULL),
(105, 'New Zealandic', '-', NULL, 'The Penguin Book of New Zealand Verse', NULL, NULL),
(106, 'New Zealandic', 'Stead', 'C. K.', 'The Faber Book of Contemporary South Pacific Stories', NULL, NULL),
(107, 'New Zealandic', 'Sturm', 'Terry', 'The Oxford History of New Zealand Literature in English', NULL, NULL),
(108, 'New Zealandic', 'Williams', 'Mark', 'The Caxton Press Anthology of New Zealand Poetry 1972-1986', NULL, NULL),
(109, 'Polish', 'Bassnett', 'S.', 'Ariadne''s Thread: Polish Women Poets', NULL, NULL),
(110, 'Polish', 'Czerniawski', 'Adam', 'The Burning Forest: Modern Polish Poetry', NULL, NULL),
(111, 'Polish', 'Czerwinski', 'E. J.', 'Contemporary Polish Theatre and Drama, 1956-84', NULL, NULL),
(112, 'Polish', 'Eile', 'Sranislaw', 'New Perspectives in Twentieth Century Polish Literature', NULL, NULL),
(113, 'Polish', 'Halikowska', 'Teresa', 'The Eagle and the Crow: Modern Polish Short Stories', NULL, NULL),
(114, 'Polish', 'Pirie', 'Donald', 'Young Poets of a New Poland', NULL, NULL),
(115, 'Polish', 'Powaga', 'Wieslaw', 'The Dedalus Book of Polish Fantasy', NULL, NULL),
(116, 'Portugese', 'De Sousa', 'A. G.', 'An Anthology of Modern Portugese and Brazilian Prose', NULL, NULL),
(117, 'Portugese', 'Macedo', 'H.', 'Contemporary Portugese Poetry: An Anthology in English', NULL, NULL),
(118, 'Portugese', 'Sadlier', 'D. J.', 'The Question of How: Women Writers and New Portugese Literature', NULL, NULL),
(119, 'Portugese', '-', '', 'Studies in Modern Portugese Literature', NULL, NULL),
(120, 'Russian', 'Brown', 'D.', 'The Last Years of Soviet Russian Literature', NULL, NULL),
(121, 'Russian', 'Chukhontsev', 'O.', 'Leopard I, Dissonant Voices: The New Russian Fiction', NULL, NULL),
(122, 'Russian', 'Duffin Graham', 'S.', 'New Directions in Soviet Literature', NULL, NULL),
(123, 'Russian', 'Erofeyer', 'V.', 'The Penguin Book of New Russian Writing: Russia''s Fleurs du Mal', NULL, NULL),
(124, 'Russian', 'Kelly', 'C.', 'A History of Russian Women''s Writing 1820-1992', NULL, NULL),
(125, 'Russian', 'Kelly', 'C.', 'An Anthology of Russian Women''s Writing 1777-1992', NULL, NULL),
(126, 'Russian', 'Porter', 'R.', 'Russia''s Alternative Prose', NULL, NULL),
(127, 'Russian', 'Shneidman', 'N.', 'Russian Literature 1988-1994: The End of an Era', NULL, NULL),
(128, 'Russian', 'Smith', 'G.', 'Contemporary Russian Poetry: A Bilingual Anthology', NULL, NULL),
(129, 'Scandinavian', 'Brostrom', 'Torben', 'Denmarkings: Danish Literature Today', NULL, NULL),
(130, 'Scandinavian', 'Forsas-Scott', 'Helena', 'Textual Liberation: European Feminist Writing in the Twentieth Century', NULL, NULL),
(131, 'Scandinavian', 'Garten', 'Janet', 'Norwegian Women''s Writing 1850-1990', NULL, NULL),
(132, 'Scandinavian', 'Lomas', 'Herbert', 'Contemporary Finnish Poetry', NULL, NULL),
(133, 'Scandinavian', 'Naess', 'Harald', 'A History of Norwegian Literature', NULL, NULL),
(134, 'Scandinavian', 'Rossel', 'Sven', 'A History of Danish Literature', NULL, NULL),
(135, 'Scandinavian', 'Scobbie', 'Irene', 'Aspects of Modern Swedish Literature', NULL, NULL),
(136, 'Scandinavian', 'Zuck', 'Virpi', 'Dictionary of Scandinavian Literature', NULL, NULL),
(137, 'Scottish', 'Chapman', 'Malcolm', 'The Gaelic Vision in Scottish Culture', NULL, NULL),
(138, 'Scottish', 'Craig', 'Cairns', 'The History of Scottish Literature, iv: The Twentieth Century', NULL, NULL),
(139, 'Scottish', 'Dick', 'Eddie', 'From Limelight to Satellite: A Scottish Film Book', NULL, NULL),
(140, 'Scottish', 'McGarth', 'John', 'A Good Night Out.Popular Theatre: Audience, Class and Form', NULL, NULL),
(141, 'Scottish', 'Malzahn', 'Manfred', 'Aspects of Identity: The Contemporary Scottish Novel (1978-1981) as National Self-Expression', NULL, NULL),
(142, 'Scottish', 'Morgan', 'Edwin', 'Crossing the Border: Essays on Scottish Literature', NULL, NULL),
(143, 'Scottish', 'Wallace', 'Gavin', 'The Scottish Novel since the Seventies', NULL, NULL),
(144, 'Spanish', 'Brown', 'Joan Lipman', 'Women Writers of Contemporary Spain: Exiles in the Homeland', NULL, NULL),
(145, 'Spanish', 'Edwards', 'Gwynne', 'Dramatists in Perspective: Spanish Theatre in the Twentieth Century', NULL, NULL),
(146, 'Spanish', 'Hart', 'Stephen M.', 'White Ink: Essays on Twentieth-Century Feminine Fiction in Spain and Latin America', NULL, NULL),
(147, 'Spanish', 'Ilie', 'Paul', 'Literature and Inner Exile: Authoritarian Spain, 1939-1975', NULL, NULL),
(148, 'Spanish', 'Labanyi', 'Jo', 'Myth and History in the Contemporary Spanish Novel', NULL, NULL),
(149, 'Spanish', 'Ordonez', 'Elizabeth J.', 'Voices of their Own: Contemporary Spanish Narrative by Women', NULL, NULL),
(150, 'Spanish', 'Schneider', 'Marshall J.', 'Modern Spanish and Portugese Literatures', NULL, NULL),
(151, 'Spanish', 'Schwartz', 'Ronald', 'Spain''s New Wave Novelists', NULL, NULL),
(152, 'Spanish', 'Wright', 'Eleanor', 'The Poetry of Protest under Franco', NULL, NULL),
(153, 'Latin American', 'Brotherston', 'Gordon', 'The Emergence of the Latin American Novel', NULL, NULL),
(154, 'Latin American', 'Donoso', 'Jose', 'The Boom in Spanish American Literature: A Personal History', NULL, NULL),
(155, 'Latin American', 'Foster', 'D. W.', 'Cultural Diversity in Latin American Literature', NULL, NULL),
(156, 'Latin American', 'Franco', 'Jean', 'An Introduction to Spanish-American Literature', NULL, NULL),
(157, 'Latin American', 'Gallagher', 'D. P.', 'Modern Latin American Literature', NULL, NULL),
(158, 'Latin American', 'Kaminsky', 'Amy K.', 'Reading the Body Politic', NULL, NULL),
(159, 'Latin American', 'MacAdam', 'Alfred', 'Textual Confrontations', NULL, NULL),
(160, 'Latin American', 'Martin', 'Gerald', 'Journeys through the Labyrinth', NULL, NULL),
(161, 'Latin American', 'Wilson', 'Jason', 'An A to Z of Latin American  Literature in English Translation', NULL, NULL),
(162, 'American', 'Bercovich', 'Sacvan', 'The Cambridge History of American Literature, viii: Poetry and Criticism since 1945', NULL, NULL),
(163, 'American', 'Bradbury', 'Malcolm', 'The Modern American Novel', NULL, NULL),
(164, 'American', 'Elliott', 'Emory', 'The Columbia History of the American Novel', NULL, NULL),
(165, 'American', 'Hilfer', 'Tony', 'American Fiction since 1940', NULL, NULL),
(166, 'American', 'Parini', 'Jay', 'The Columbia History of American Poetry', NULL, NULL),
(167, 'Welsh', 'Aaron', 'Jane', 'Our Sisters'' Land: The Changing Identities of Women in Wales', NULL, NULL),
(168, 'Welsh', 'Johnston', 'Dafydd', 'The Literature of Wales: A Pocket Guide', NULL, NULL),
(169, 'Welsh', 'Smith', 'Dai', 'Wales! Wales!', NULL, NULL),
(170, 'Welsh', 'Stephens', 'Meic', 'The Oxford Companion to the Literature of Wales', NULL, NULL),
(171, 'Welsh', 'Thomas', 'M. Wynn', 'Internal Difference: Literature in 20th-Century Wales', NULL, NULL),
(172, 'Welsh', 'Thomas', 'Ned', 'The Welsh Extremist: A Culture in Crisis', NULL, NULL),
(173, 'Carribean', 'Baugh', 'Edward', 'Critics on Carribean Literature', NULL, NULL),
(174, 'Carribean', 'Benson', 'Eugene', 'Encyclopedia of Post-Colonial Literatures in English', NULL, NULL),
(175, 'Carribean', 'Chamberlain', 'Edward J.', 'Come Back to Me, My Language', NULL, NULL),
(176, 'Carribean', 'James', 'Louis', 'The Islands in Between', NULL, NULL),
(177, 'Carribean', 'Lindfors', 'Bernth', 'Dictionary of Literary Biography, Vol. 125: C20th Carribean and Black African Writers', NULL, NULL),
(178, 'Carribean', 'Ramchand', 'Kenneth', 'The West Indian Novel and Its Background', NULL, NULL),
(179, 'Iranian', 'Manoochehr', 'Aryanpur', 'A History of Persian Literature', NULL, NULL),
(180, 'Iranian', 'Clawson', 'Patrick', 'Eternal Iran', NULL, NULL),
(181, 'Iranian', 'Browne', 'E. G.', 'Literary History of Persia', NULL, NULL),
(182, 'Iranian', 'Rypka', 'Jan', 'History of Iranian Literature', NULL, NULL),
(183, 'Iranian', 'Walker', 'Benjamin', 'Persian Pageant: A Cultural History of Iran', NULL, NULL);