INSERT INTO Quotations (ID, Include, Quotation) VALUES (1, 1, 'The truth is rarely pure and never simple. Modern life would be very tedious if it were either, and modern literature a complete impossibility!  _Oscar Wilde'),
(2, 1, 'It is absurd to divide people into good and bad. People are either charming or tedious. _Oscar Wilde'),
(3, 1, 'After a good dinner one can forgive anybody, even ones own relations. _Oscar Wilde'),
(4, 1, 'In matters of grave importance, style, not sincerity is the vital thing. _Oscar Wilde'),
(5, 1, '"Reeling and Writhing, of course, to begin with," the Mock Turtle replied; "and then the different branches of Arithmetic--Ambition, Distraction, Uglification, and Derision.  _Lewis Carroll'),
(6, 1, 'To be clever enough to get all that money, one must be stupid enough to want it. _G. K. Chesterton'),
(7, 1, 'We live, as we dream--alone.  _Joseph Conrad'),
(8, 1, 'Words, as is well known, are the great foes of reality. _Joseph Conrad'),
(9, 1, '. . . dont you forget what''s divine in the Russian soul--and that''s resignation. _Joseph Conrad'),
(10, 1, 'And a word carries far--very far--deals destruction through time as the bullets go flying through space.  _Joseph Conrad'),
(11, 1, 'Man is sometimes extraordinarily, passionately, in love with suffering. _Dostoevsky'),
(12, 1, '. . . human speech is like a cracked tin kettle, on which we hammer out tunes to make bears dance when we long to move the stars. _Gustave Flaubert'),
(13, 1, 'They slipped briskly into an intimacy from which they never recovered. _F. Scott Fitzgerald'),
(14, 1, 'A funeral is not death, any more than baptism is birth or marriage union. All three are the clumsy devices, coming now too late, now too early, by which Society would register the quick motions of man.  _E. M. Foster'),
(15, 1, 'The tree rustled. It had made music before they were born, and would continue after their deaths, but its song was of the moment. _E. M. Foster'),
(16, 1, 'What is the good of your stars and trees, your sunrise and the wind, if they do not enter into our daily lives? _E. M. Foster'),
(17, 1, '. . . the rich ate and drank freely, accepting gout and apoplexy as things that ran mysteriously in respectable families .  _George Eliot'),
(18, 1, '"The human heart," he murmured, "is the tomb of many feelings."_John Galsworthy'),
(19, 1, 'The proper study of mankind is books. _Aldous Huxley'),
(20, 1, 'Why can''t somebody give us a list of things that everybody thinks and nobody says, and another list of things that everybody says and nobody thinks?  -Oliver Wendell Holmes'),
(21, 1, 'A moment''s insight is sometimes worth a life''s experience. -Oliver Wendell Holmes'),
(22, 1, 'I talk half the time to find out my own thoughts, as a school-boy turns his pockets inside out to see what is in them. _Oliver Wendell Holmes, Sr.  '),
(23, 1, 'Men are idolaters, and want something to look at and kiss and hug, or throw themselves down before; they always did, they always will; and if you don''t make it of wood, you must make it of words. -Oliver Wendell Holmes, Sr.'),
(24, 1, 'A weak mind does not accumulate force enough to hurt itself; stupidity often saves a man from going mad. _Oliver Wendell Holmes, Sr.'),
(25, 1, 'Knowledge and timber shouldn''t be much used, till they are seasoned. _Oliver Wendell Holmes, Sr.'),
(26, 1, 'Under certain circumstances there are few hours in life more agreeable than the hour dedicated to the ceremony known as afternoon tea. _Henry James'),
(27, 1, 'Let your boat of life be light, packed with only what you need - a homely home and simple pleasures, one or two friends, worth the name, someone to love and someone to love you, a cat, a dog, and a pipe or two, enough to eat and enough to wear, and a little more than enough to drink; for thirst is a dangerous thing. _Jerome K. Jerome'),
(28, 1, 'Shakespeare is the happy hunting ground of all minds that have lost their balance.  _James Joyce'),
(29, 1, '"Thats the way we all begin," said Tom Platt. "The boys they make believe all the time till they''ve cheated ''emselves into bein'' men, an so till they die - pretendin'' an pretendin''   _Rudyard Kipling'),
(30, 1, 'There are two races of people, only two, and they live side by side. His calls mine ''neurotic''; mine calls his ''stupid''.   _Sinclair Lewis'),
(31, 1, 'They think me mad--Starbuck does; but I''m demoniac, I am madness maddened! That wild madness that''s only calm to comprehend itself! _Herman Melville'),
(32, 1, 'Yea, foolish mortals, Noah''s flood is not yet subsided; two thirds of the fair world it yet covers. _Herman Melville'),
(33, 1, 'You needn''t tell me that a man who doesnt love oysters and asparagus and good wines has got a soul, or a stomach either. He''s simply got the instinct for being unhappy highly developed. _Saki'),
(34, 1, 'Remember that you are a human being with a soul and the divine gift of articulate speech: that your native language is the language of Shakespeare and Milton and The Bible; and dont sit there crooning like a bilious pigeon. _George Bernard Shaw'),
(35, 1, 'I have to live for others and not for myself: thats middle class morality. _George Bernard Shaw'),
(36, 1, 'The more things a man is ashamed of, the more respectable he is. _George Bernard Shaw'),
(37, 1, 'What is life but a series of inspired follies? _George Bernard Shaw '),
(38, 1, 'All great truths begin as blasphemies. _George Bernard Shaw'),
(39, 1, 'The confusion of marriage with morality has done more to destroy the conscience of the human race than any other single error. _George Bernard Shaw'),
(40, 1, 'It was the incarnation of blind and insensate Greed. It was a monster devouring with a thousand mouths, trampling with a thousand hoofs; it was the Great Butcher--it was the spirit of Capitalism made flesh. _Upton Sinclair'),
(41, 1, 'And whenever he spoke (which he did almost always), he took care to produce the very finest and longest words of which the vocabulary gave him the use, rightly judging that it was as cheap to employ a handsome, large, and sonorous epithet, as to use a little stingy one. _William Makepeace Thackeray'),
(42, 1, 'There is no happiness in love, except at the end of an English novel. _Anthony Trollope'),
(43, 1, 'The bishop did not whistle: we believe that they lose the power of doing so on being consecrated. _Anthony Trollope'),
(44, 1, 'When angry, count four; when very angry, swear. _Mark Twain'),
(45, 1, 'Its lovely to live on a raft. We had the sky up there, all speckled with stars, and we used to lay on our backs and look up at them, and discuss about whether they was made or only just happened. _Mark Twain'),
(46, 1, 'When you consider things like the stars, our affairs dont seem to matter very much, do they? _Virginia Woolf'),
(47, 1, 'Mediocrity knows nothing higher than itself; but talent instantly recognizes genius.  _Sir Arthur Conan Doyle'),
(48, 1, 'But Rosa soon made the discovery that Miss Twinkleton didnt read fairly. She cut the love-scenes, interpolated passages in praise of female celibacy, and was guilty of other glaring pious frauds.  _Charles Dickens'),
(49, 1, 'In other countries, art and literature are left to a lot of shabby bums living in attics and feeding on booze and spaghetti, but in America the successful writer or picture-painter is indistinguishable from any other decent business man.  _Sinclair Lewis');