INSERT INTO Splash (Include, AwardName, LastName, FirstName, ImageURL) VALUES (1, 'Booker', 'Atwood', 'Margaret', 'Images/AwardedAuthors/Booker/Atwood_Margaret.jpg'),
(1, 'Booker', 'Banville', 'John', 'Images/AwardedAuthors/Booker/Banville_John.jpg'),
(1, 'Booker', 'Barker', 'Pat', 'Images/AwardedAuthors/Booker/Barker_Pat.jpg'),
(1, 'Booker', 'Berger', 'John', 'Images/AwardedAuthors/Booker/Berger_John.jpg'),
(1, 'Booker', 'Brookner', 'Anita', 'Images/AwardedAuthors/Booker/Brookner_Anita.jpg'),
(1, 'Booker', 'Byatt', 'A S', 'Images/AwardedAuthors/Booker/Byatt_A S.jpg'),
(1, 'Booker', 'Carey', 'Peter', 'Images/AwardedAuthors/Booker/Carey_Peter.jpg'),
(1, 'Booker', 'Desai', 'Kiran', 'Images/AwardedAuthors/Booker/Desai_Kiran.jpg'),
(1, 'Booker', 'Doyle', 'Roddy', 'Images/AwardedAuthors/Booker/Doyle_Roddy.jpg'),
(1, 'Booker', 'Farrell', 'J G', 'Images/AwardedAuthors/Booker/Farrell_J G.jpg'),
(1, 'Booker', 'Fitzgerald', 'Penelope', 'Images/AwardedAuthors/Booker/Fitzgerald_Penelope.jpg'),
(1, 'Booker', 'Hollinghurst', 'Alan', 'Images/AwardedAuthors/Booker/Hollinghurst_Alan.jpg'),
(1, 'Booker', 'Hulme', 'Keri', 'Images/AwardedAuthors/Booker/Hulme_Keri.jpg'),
(1, 'Booker', 'Ishiguro', 'Kazuo', 'Images/AwardedAuthors/Booker/Ishiguro_Kazuo.jpg'),
(1, 'Booker', 'Jhabvala', 'Ruth Prawer', 'Images/AwardedAuthors/Booker/Jhabvala_Ruth Prawer.jpg'),
(1, 'Booker', 'Kelman', 'James', 'Images/AwardedAuthors/Booker/Kelman_James.jpg'),
(1, 'Booker', 'Keneally', 'Thomas', 'Images/AwardedAuthors/Booker/Keneally_Thomas.jpg'),
(1, 'Booker', 'Kingsley', 'Amis', 'Images/AwardedAuthors/Booker/Kingsley_Amis.jpg'),
(1, 'Booker', 'Lively', 'Penelope', 'Images/AwardedAuthors/Booker/Lively_Penelope.jpg'),
(1, 'Booker', 'Martel', 'Yann', 'Images/AwardedAuthors/Booker/Martel_Yann.jpg'),
(1, 'Booker', 'McEwan', 'Ian', 'Images/AwardedAuthors/Booker/McEwan_Ian.jpg'),
(1, 'Booker', 'Murdoch', 'Iris', 'Images/AwardedAuthors/Booker/Murdoch_Iris.jpg'),
(1, 'Booker', 'Newby', 'P H', 'Images/AwardedAuthors/Booker/Newby_P H.jpg'),
(1, 'Booker', 'Okri', 'Ben', 'Images/AwardedAuthors/Booker/Okri_Ben.jpg'),
(1, 'Booker', 'Ondaatje', 'Michael', 'Images/AwardedAuthors/Booker/Ondaatje_Michael.jpg'),
(1, 'Booker', 'Pierre', 'D B C', 'Images/AwardedAuthors/Booker/Pierre_D B C.jpg'),
(1, 'Booker', 'Roy', 'Arundhati', 'Images/AwardedAuthors/Booker/Roy_Arundhati.jpg'),
(1, 'Booker', 'Rubens', 'Bernice', 'Images/AwardedAuthors/Booker/Rubens_Bernice.jpg'),
(1, 'Booker', 'Rushdie', 'Salman', 'Images/AwardedAuthors/Booker/Rushdie_Salman.jpg'),
(1, 'Booker', 'Scott', 'Paul', 'Images/AwardedAuthors/Booker/Scott_Paul.jpg'),
(1, 'Booker', 'Storey', 'David', 'Images/AwardedAuthors/Booker/Storey_David.jpg'),
(1, 'Booker', 'Swift', 'Graham', 'Images/AwardedAuthors/Booker/Swift_Graham.jpg'),
(1, 'Pulitzer', 'Applebaum', 'Ann', 'Images/AwardedAuthors/Pulitzer/Applebaum_Ann.jpg'),
(1, 'Pulitzer', 'Applegate', 'Debby', 'Images/AwardedAuthors/Pulitzer/Applegate_Debby.jpg'),
(1, 'Pulitzer', 'Bird', 'Kai and Serwin_Martin', 'Images/AwardedAuthors/Pulitzer/Bird_Kai and Serwin_Martin.jpg'),
(1, 'Pulitzer', 'Brooks', 'Geraldine', 'Images/AwardedAuthors/Pulitzer/Brooks_Geraldine.jpg'),
(1, 'Pulitzer', 'Coll', 'Steve', 'Images/AwardedAuthors/Pulitzer/Coll_Steve.jpg'),
(1, 'Pulitzer', 'Elkins', 'Caroline', 'Images/AwardedAuthors/Pulitzer/Elkins_Caroline.jpg'),
(1, 'Pulitzer', 'Emerson', 'Claudia', 'Images/AwardedAuthors/Pulitzer/Emerson_Claudia.jpg'),
(1, 'Pulitzer', 'Fischer', 'David Hackett', 'Images/AwardedAuthors/Pulitzer/Fischer_David Hackett.jpg'),
(1, 'Pulitzer', 'Hahn', 'Steven', 'Images/AwardedAuthors/Pulitzer/Hahn_Steven.jpg'),
(1, 'Pulitzer', 'Kooser', 'Ted', 'Images/AwardedAuthors/Pulitzer/Kooser_Ted.jpg'),
(1, 'Pulitzer', 'Lindsay-Abaire', 'David', 'Images/AwardedAuthors/Pulitzer/Lindsay-Abaire_David.jpg'),
(1, 'Pulitzer', 'McCarthy', 'Cormac', 'Images/AwardedAuthors/Pulitzer/McCarthy_Cormac.jpg'),
(1, 'Pulitzer', 'Oshinsky', 'David M', 'Images/AwardedAuthors/Pulitzer/Oshinsky_David M.jpg'),
(1, 'Pulitzer', 'Robinson', 'Marilynne', 'Images/AwardedAuthors/Pulitzer/Robinson_Marilynne.jpg'),
(1, 'Pulitzer', 'Shanley', 'John Patrick', 'Images/AwardedAuthors/Pulitzer/Shanley_John Patrick.jpg'),
(1, 'Pulitzer', 'Sherwin', 'Martin', 'Images/AwardedAuthors/Pulitzer/Sherwin_Martin.jpg'),
(1, 'Pulitzer', 'Stevens', 'Mark and Swan_Annalyn', 'Images/AwardedAuthors/Pulitzer/Stevens_Mark and Swan_Annalyn.jpg'),
(1, 'Pulitzer', 'Taubman', 'William', 'Images/AwardedAuthors/Pulitzer/Taubman_William.jpg'),
(1, 'Pulitzer', 'Trethewey', 'Natasha', 'Images/AwardedAuthors/Pulitzer/Trethewey_Natasha.jpg'),
(1, 'Pulitzer', 'Wright', 'Doug', 'Images/AwardedAuthors/Pulitzer/Wright_Doug.jpg'),
(1, 'Pulitzer', 'Wright', 'Franz', 'Images/AwardedAuthors/Pulitzer/Wright_Franz.jpg'),
(1, 'Pulitzer', 'Wright', 'Lawrence', 'Images/AwardedAuthors/Pulitzer/Wright_Lawrence.jpg'),
(1, 'Nobel', 'Agnon', 'Shmuel Yosef', 'Images/AwardedAuthors/Nobel/Agnon_Shmuel Yosef.jpg'),
(1, 'Nobel', 'Aleixandre', 'Vincente', 'Images/AwardedAuthors/Nobel/Aleixandre_Vincente.jpg'),
(1, 'Nobel', 'Andric', 'Ivo', 'Images/AwardedAuthors/Nobel/Andric_Ivo.jpg'),
(1, 'Nobel', 'Asturias', 'Miguel', 'Images/AwardedAuthors/Nobel/Asturias_Miguel.jpg'),
(1, 'Nobel', 'Beckett', 'Samuel', 'Images/AwardedAuthors/Nobel/Beckett_Samuel.jpg'),
(1, 'Nobel', 'Bellow', 'Saul', 'Images/AwardedAuthors/Nobel/Bellow_Saul.jpg'),
(1, 'Nobel', 'Benavente', 'Jacinto', 'Images/AwardedAuthors/Nobel/Benavente_Jacinto.jpg'),
(1, 'Nobel', 'Bergson', 'Henri', 'Images/AwardedAuthors/Nobel/Bergson_Henri.jpg'),
(1, 'Nobel', 'Bjornstjerne', 'Bjornson', 'Images/AwardedAuthors/Nobel/Bjornstjerne_Bjornson.jpg'),
(1, 'Nobel', 'Boll', 'Heinrich', 'Images/AwardedAuthors/Nobel/Boll_Heinrich.jpg'),
(1, 'Nobel', 'Brodsky', 'Joseph', 'Images/AwardedAuthors/Nobel/Brodsky_Joseph.jpg'),
(1, 'Nobel', 'Buck', 'Pearl', 'Images/AwardedAuthors/Nobel/Buck_Pearl.jpg'),
(1, 'Nobel', 'Bunin', 'Ivan', 'Images/AwardedAuthors/Nobel/Bunin_Ivan.jpg'),
(1, 'Nobel', 'Camus', 'Albert', 'Images/AwardedAuthors/Nobel/Camus_Albert.jpg'),
(1, 'Nobel', 'Canetti', 'Elias', 'Images/AwardedAuthors/Nobel/Canetti_Elias.jpg'),
(1, 'Nobel', 'Carducci', 'Giosue', 'Images/AwardedAuthors/Nobel/Carducci_Giosue.jpg'),
(1, 'Nobel', 'Cela', 'Camilo Jose', 'Images/AwardedAuthors/Nobel/Cela_Camilo Jose.jpg'),
(1, 'Nobel', 'Churchill', 'Winston', 'Images/AwardedAuthors/Nobel/Churchill_Winston.jpg'),
(1, 'Nobel', 'Coetzee', 'John M', 'Images/AwardedAuthors/Nobel/Coetzee_John M.jpg'),
(1, 'Nobel', 'Deledda', 'Grazia', 'Images/AwardedAuthors/Nobel/Deledda_Grazia.jpg'),
(1, 'Nobel', 'du Gard', 'Roger', 'Images/AwardedAuthors/Nobel/du Gard_Roger.jpg'),
(1, 'Nobel', 'Eizaguirre', 'Jose', 'Images/AwardedAuthors/Nobel/Eizaguirre_Jose.jpg'),
(1, 'Nobel', 'Eliot', 'Thomas Stearns', 'Images/AwardedAuthors/Nobel/Eliot_Thomas Stearns.jpg'),
(1, 'Nobel', 'Elytis', 'Odysseus', 'Images/AwardedAuthors/Nobel/Elytis_Odysseus.jpg'),
(1, 'Nobel', 'Eucken', 'Rudolf', 'Images/AwardedAuthors/Nobel/Eucken_Rudolf.jpg'),
(1, 'Nobel', 'Faulkner', 'William', 'Images/AwardedAuthors/Nobel/Faulkner_William.jpg'),
(1, 'Nobel', 'Fo', 'Dario', 'Images/AwardedAuthors/Nobel/Fo_Dario.jpg'),
(1, 'Nobel', 'France', 'Anatole', 'Images/AwardedAuthors/Nobel/France_Anatole.jpg'),
(1, 'Nobel', 'Galsworthy', 'John', 'Images/AwardedAuthors/Nobel/Galsworthy_John.jpg'),
(1, 'Nobel', 'Gide', 'Andre', 'Images/AwardedAuthors/Nobel/Gide_Andre.jpg'),
(1, 'Nobel', 'Gjellerup', 'Karl', 'Images/AwardedAuthors/Nobel/Gjellerup_Karl.jpg'),
(1, 'Nobel', 'Golding', 'William', 'Images/AwardedAuthors/Nobel/Golding_William.jpg'),
(1, 'Nobel', 'Gordimer', 'Nadine', 'Images/AwardedAuthors/Nobel/Gordimer_Nadine.jpg'),
(1, 'Nobel', 'Grass', 'Gunter', 'Images/AwardedAuthors/Nobel/Grass_Gunter.jpg'),
(1, 'Nobel', 'Hamsun', 'Knut', 'Images/AwardedAuthors/Nobel/Hamsun_Knut.jpg'),
(1, 'Nobel', 'Hauptmann', 'Gerhart', 'Images/AwardedAuthors/Nobel/Hauptmann_Gerhart.jpg'),
(1, 'Nobel', 'Heaney', 'Seamus', 'Images/AwardedAuthors/Nobel/Heaney_Seamus.jpg'),
(1, 'Nobel', 'Hemingway', 'Ernest', 'Images/AwardedAuthors/Nobel/Hemingway_Ernest.jpg'),
(1, 'Nobel', 'Hesse', 'Hermann', 'Images/AwardedAuthors/Nobel/Hesse_Hermann.jpg'),
(1, 'Nobel', 'Heyse', 'Paul', 'Images/AwardedAuthors/Nobel/Heyse_Paul.jpg'),
(1, 'Nobel', 'Jelinek', 'Elfriede', 'Images/AwardedAuthors/Nobel/Jelinek_Elfriede.jpg'),
(1, 'Nobel', 'Jensen', 'Johannes', 'Images/AwardedAuthors/Nobel/Jensen_Johannes.jpg'),
(1, 'Nobel', 'Jimenez', 'Juan', 'Images/AwardedAuthors/Nobel/Jimenez_Juan.jpg'),
(1, 'Nobel', 'Johnson', 'Eyvind', 'Images/AwardedAuthors/Nobel/Johnson_Eyvind.jpg'),
(1, 'Nobel', 'Karlfeldt', 'Erik', 'Images/AwardedAuthors/Nobel/Karlfeldt_Erik.jpg'),
(1, 'Nobel', 'Kawabata', 'Yasunari', 'Images/AwardedAuthors/Nobel/Kawabata_Yasunari.jpg'),
(1, 'Nobel', 'Kertesz', 'Imre', 'Images/AwardedAuthors/Nobel/Kertesz_Imre.jpg'),
(1, 'Nobel', 'Kipling', 'Rudyard', 'Images/AwardedAuthors/Nobel/Kipling_Rudyard.jpg'),
(1, 'Nobel', 'Lagerkvist', 'Par', 'Images/AwardedAuthors/Nobel/Lagerkvist_Par.jpg'),
(1, 'Nobel', 'Lagerlof', 'Selma', 'Images/AwardedAuthors/Nobel/Lagerlof_Selma.jpg'),
(1, 'Nobel', 'Laxness', 'Halldor', 'Images/AwardedAuthors/Nobel/Laxness_Halldor.jpg'),
(1, 'Nobel', 'Lewis', 'Sinclair', 'Images/AwardedAuthors/Nobel/Lewis_Sinclair.jpg'),
(1, 'Nobel', 'Maeterlinck', 'Maurice', 'Images/AwardedAuthors/Nobel/Maeterlinck_Maurice.jpg'),
(1, 'Nobel', 'Mahfouz', 'Naguib', 'Images/AwardedAuthors/Nobel/Mahfouz_Naguib.jpg'),
(1, 'Nobel', 'Mann', 'Thomas', 'Images/AwardedAuthors/Nobel/Mann_Thomas.jpg'),
(1, 'Nobel', 'Marquez', 'Gabriel Garcia', 'Images/AwardedAuthors/Nobel/Marquez_Gabriel Garcia.jpg'),
(1, 'Nobel', 'Martinson', 'Harry', 'Images/AwardedAuthors/Nobel/Martinson_Harry.jpg'),
(1, 'Nobel', 'Mauriac', 'Francois', 'Images/AwardedAuthors/Nobel/Mauriac_Francois.jpg'),
(1, 'Nobel', 'Milosz', 'Czeslaw', 'Images/AwardedAuthors/Nobel/Milosz_Czeslaw.jpg'),
(1, 'Nobel', 'Mistral', 'Frederic', 'Images/AwardedAuthors/Nobel/Mistral_Frederic.jpg'),
(1, 'Nobel', 'Mistral', 'Gabriela', 'Images/AwardedAuthors/Nobel/Mistral_Gabriela.jpg'),
(1, 'Nobel', 'Mommsen', 'Theodor', 'Images/AwardedAuthors/Nobel/Mommsen_Theodor.jpg'),
(1, 'Nobel', 'Montale', 'Eugenio', 'Images/AwardedAuthors/Nobel/Montale_Eugenio.jpg'),
(1, 'Nobel', 'Morrison', 'Toni', 'Images/AwardedAuthors/Nobel/Morrison_Toni.jpg'),
(1, 'Nobel', 'Naipaul', 'V S', 'Images/AwardedAuthors/Nobel/Naipaul_V S.jpg'),
(1, 'Nobel', 'Neruda', 'Pablo', 'Images/AwardedAuthors/Nobel/Neruda_Pablo.jpg'),
(1, 'Nobel', 'Oe', 'Kenzaburo', 'Images/AwardedAuthors/Nobel/Oe_Kenzaburo.jpg'),
(1, 'Nobel', 'O''Neill', 'Eugene', 'Images/AwardedAuthors/Nobel/ONeill_Eugene.jpg'),
(1, 'Nobel', 'Pamuk', 'Orhan', 'Images/AwardedAuthors/Nobel/Pamuk_Orhan.jpg'),
(1, 'Nobel', 'Pasternak', 'Boris', 'Images/AwardedAuthors/Nobel/Pasternak_Boris.jpg'),
(1, 'Nobel', 'Paz', 'Octavio', 'Images/AwardedAuthors/Nobel/Paz_Octavio.jpg'),
(1, 'Nobel', 'Perse', 'Saint-John', 'Images/AwardedAuthors/Nobel/Perse_Saint-John.jpg'),
(1, 'Nobel', 'Pinter', 'Harold', 'Images/AwardedAuthors/Nobel/Pinter_Harold.jpg'),
(1, 'Nobel', 'Pirandello', 'Luigi', 'Images/AwardedAuthors/Nobel/Pirandello_Luigi.jpg'),
(1, 'Nobel', 'Pontoppidan', 'Henrik', 'Images/AwardedAuthors/Nobel/Pontoppidan_Henrik.jpg'),
(1, 'Nobel', 'Prudhomme', 'Sully', 'Images/AwardedAuthors/Nobel/Prudhomme_Sully.jpg'),
(1, 'Nobel', 'Quasimodo', 'Salvatore', 'Images/AwardedAuthors/Nobel/Quasimodo_Salvatore.jpg'),
(1, 'Nobel', 'Reymont', 'Wladyslaw', 'Images/AwardedAuthors/Nobel/Reymont_Wladyslaw.jpg'),
(1, 'Nobel', 'Rolland', 'Romain', 'Images/AwardedAuthors/Nobel/Rolland_Romain.jpg'),
(1, 'Nobel', 'Russell', 'Bertrand', 'Images/AwardedAuthors/Nobel/Russell_Bertrand.jpg'),
(1, 'Nobel', 'Sachs', 'Nelly', 'Images/AwardedAuthors/Nobel/Sachs_Nelly.jpg'),
(1, 'Nobel', 'Saramago', 'Jose', 'Images/AwardedAuthors/Nobel/Saramago_Jose.jpg'),
(1, 'Nobel', 'Sartre', 'Jean-Paul', 'Images/AwardedAuthors/Nobel/Sartre_Jean-Paul.jpg'),
(1, 'Nobel', 'Seferis', 'Giorgos', 'Images/AwardedAuthors/Nobel/Seferis_Giorgos.jpg'),
(1, 'Nobel', 'Seifert', 'Jaroslav', 'Images/AwardedAuthors/Nobel/Seifert_Jaroslav.jpg'),
(1, 'Nobel', 'Shaw', 'George Bernard', 'Images/AwardedAuthors/Nobel/Shaw_George Bernard.jpg'),
(1, 'Nobel', 'Sholokhov', 'Mikhail', 'Images/AwardedAuthors/Nobel/Sholokhov_Mikhail.jpg'),
(1, 'Nobel', 'Sienkiewicz', 'Henryk', 'Images/AwardedAuthors/Nobel/Sienkiewicz_Henryk.jpg'),
(1, 'Nobel', 'Sillanpaa', 'Frans', 'Images/AwardedAuthors/Nobel/Sillanpaa_Frans.jpg'),
(1, 'Nobel', 'Simon', 'Claude', 'Images/AwardedAuthors/Nobel/Simon_Claude.jpg'),
(1, 'Nobel', 'Singer', 'Isaac Bashevis', 'Images/AwardedAuthors/Nobel/Singer_Isaac Bashevis.jpg'),
(1, 'Nobel', 'Solzhenitsyn', 'Aleksandr', 'Images/AwardedAuthors/Nobel/Solzhenitsyn_Aleksandr.jpg'),
(1, 'Nobel', 'Soyinka', 'Wole', 'Images/AwardedAuthors/Nobel/Soyinka_Wole.jpg'),
(1, 'Nobel', 'Spitteler', 'Carl', 'Images/AwardedAuthors/Nobel/Spitteler_Carl.jpg'),
(1, 'Nobel', 'Steinbeck', 'John', 'Images/AwardedAuthors/Nobel/Steinbeck_John.jpg'),
(1, 'Nobel', 'Szymborska', 'Wislawa', 'Images/AwardedAuthors/Nobel/Szymborska_Wislawa.jpg'),
(1, 'Nobel', 'Tagore', 'Rabindranath', 'Images/AwardedAuthors/Nobel/Tagore_Rabindranath.jpg'),
(1, 'Nobel', 'Undset', 'Sigrid', 'Images/AwardedAuthors/Nobel/Undset_Sigrid.jpg'),
(1, 'Nobel', 'Walcott', 'Derek', 'Images/AwardedAuthors/Nobel/Walcott_Derek.jpg'),
(1, 'Nobel', 'White', 'Patrick', 'Images/AwardedAuthors/Nobel/White_Patrick.jpg'),
(1, 'Nobel', 'Xingjian', 'Gao', 'Images/AwardedAuthors/Nobel/Xingjian_Gao.jpg'),
(1, 'Nobel', 'Yeats', 'William Butler', 'Images/AwardedAuthors/Nobel/Yeats_William Butler.jpg'),
(1, 'Booker Intl', 'Achebe', 'Chinua', 'Images/AwardedAuthors/Booker Intl/Achebe_Chinua.jpg'),
(1, 'Booker Intl', 'Kadare', 'Ismael', 'Images/AwardedAuthors/Booker Intl/Kadare_Ismael.jpg'),
(1, 'IMPAC', 'Houellebecq', 'Michel', 'Images/AwardedAuthors/IMPAC/Houellebecq_Michel.jpg'),
(1, 'IMPAC', 'Jelloun', 'Tahar Ben', 'Images/AwardedAuthors/IMPAC/Jelloun_Tahar Ben.jpg'),
(1, 'IMPAC', 'Jones', 'Edward P', 'Images/AwardedAuthors/IMPAC/Jones_Edward P.jpg'),
(1, 'IMPAC', 'Malouf', 'David', 'Images/AwardedAuthors/IMPAC/Malouf_David.jpg'),
(1, 'IMPAC', 'Marias', 'Javier', 'Images/AwardedAuthors/IMPAC/Marias_Javier.jpg'),
(1, 'IMPAC', 'Miller', 'Andrew', 'Images/AwardedAuthors/IMPAC/Miller_Andrew.jpg'),
(1, 'IMPAC', 'Muller', 'Herta', 'Images/AwardedAuthors/IMPAC/Muller_Herta.jpg'),
(1, 'IMPAC', 'Toibin', 'Colm', 'Images/AwardedAuthors/IMPAC/Toibin_Colm.jpg'),
(1, 'Commonwealth', 'Bail', 'Murray', 'Images/AwardedAuthors/Commonwealth/Bail_Murray.jpg'),
(1, 'Commonwealth', 'Bernieres', 'Louis_de', 'Images/AwardedAuthors/Commonwealth/Bernieres_Louis_de.jpg'),
(1, 'Commonwealth', 'Clarke', 'Austin', 'Images/AwardedAuthors/Commonwealth/Clarke_Austin.jpg'),
(1, 'Commonwealth', 'Flanagan', 'Richard', 'Images/AwardedAuthors/Commonwealth/Flanagan_Richard.jpg'),
(1, 'Commonwealth', 'Frame', 'Janet', 'Images/AwardedAuthors/Commonwealth/Frame_Janet.jpg'),
(1, 'Commonwealth', 'Grenville', 'Kate', 'Images/AwardedAuthors/Commonwealth/Grenville_Kate.jpg'),
(1, 'Commonwealth', 'Hill', 'Lawrence', 'Images/AwardedAuthors/Commonwealth/Hill_Lawrence.jpg'),
(1, 'Commonwealth', 'Jones', 'Lloyd', 'Images/AwardedAuthors/Commonwealth/Jones_Lloyd.jpg'),
(1, 'Commonwealth', 'Levy', 'Andrea', 'Images/AwardedAuthors/Commonwealth/Levy_Andrea.jpg'),
(1, 'Commonwealth', 'Lovelace', 'Earl', 'Images/AwardedAuthors/Commonwealth/Lovelace_Earl.jpg'),
(1, 'Commonwealth', 'Miller', 'Alex', 'Images/AwardedAuthors/Commonwealth/Miller_Alex.jpg'),
(1, 'Commonwealth', 'Mistry', 'Rohinton', 'Images/AwardedAuthors/Commonwealth/Mistry_Rohinton.jpg'),
(1, 'Commonwealth', 'Phillips', 'Caryl', 'Images/AwardedAuthors/Commonwealth/Phillips_Caryl.jpg'),
(1, 'Commonwealth', 'Richler', 'Mordecai', 'Images/AwardedAuthors/Commonwealth/Richler_Mordecai.jpg'),
(1, 'Commonwealth', 'Senior', 'Olive', 'Images/AwardedAuthors/Commonwealth/Senior_Olive.jpg'),
(1, 'Commonwealth', 'Seth', 'Vikram', 'Images/AwardedAuthors/Commonwealth/Seth_Vikram.jpg'),
(1, 'Nobel', 'Lessing', 'Doris', 'Images/AwardedAuthors/Nobel/Lessing_Doris.jpg'),
(1, 'Nobel', 'Clezio', 'Jean-Marie Le', 'Images/AwardedAuthors/Nobel/Clezio_Jean-Marie Le.jpg'),
(1, 'NBA', 'Algren', 'Nelson', 'Images/AwardedAuthors/NBA/Algren_Nelson.jpg'),
(1, 'NBA', 'Barrett', 'Andrea', 'Images/AwardedAuthors/NBA/Barrett_Andrea.jpg'),
(1, 'NBA', 'Barth', 'John', 'Images/AwardedAuthors/NBA/Barth_John.jpg'),
(1, 'NBA', 'Casey', 'John', 'Images/AwardedAuthors/NBA/Casey_John.jpg'),
(1, 'NBA', 'Cheever', 'John', 'Images/AwardedAuthors/NBA/Cheever_John.jpg'),
(1, 'NBA', 'Dexter', 'Pete', 'Images/AwardedAuthors/NBA/Dexter_Pete.jpg'),
(1, 'NBA', 'Doctorow', 'E L', 'Images/AwardedAuthors/NBA/Doctorow_E L.jpg'),
(1, 'NBA', 'Ellison', 'Ralph', 'Images/AwardedAuthors/NBA/Ellison_Ralph.jpg'),
(1, 'NBA', 'Franzen', 'Jonathan', 'Images/AwardedAuthors/NBA/Franzen_Jonathan.jpg'),
(1, 'NBA', 'Frazier', 'Charles', 'Images/AwardedAuthors/NBA/Frazier_Charles.jpg'),
(1, 'NBA', 'Gaddis', 'William', 'Images/AwardedAuthors/NBA/Gaddis_William.jpg'),
(1, 'NBA', 'Gilchrist', 'Ellen', 'Images/AwardedAuthors/NBA/Gilchrist_Ellen.jpg'),
(1, 'NBA', 'Glass', 'Julia', 'Images/AwardedAuthors/NBA/Glass_Julia.jpg'),
(1, 'NBA', 'Hazzard', 'Shirley', 'Images/AwardedAuthors/NBA/Hazzard_Shirley.jpg'),
(1, 'NBA', 'Heinemann', 'Larry', 'Images/AwardedAuthors/NBA/Heinemann_Larry.jpg'),
(1, 'NBA', 'Irving', 'John', 'Images/AwardedAuthors/NBA/Irving_John.jpg'),
(1, 'NBA', 'Jin', 'Ha', 'Images/AwardedAuthors/NBA/Jin_Ha.jpg'),
(1, 'NBA', 'Johnson', 'Charles R', 'Images/AwardedAuthors/NBA/Johnson_Charles R.jpg'),
(1, 'NBA', 'Johnson', 'Denis', 'Images/AwardedAuthors/NBA/Johnson_Denis.jpg'),
(1, 'NBA', 'Jones', 'James', 'Images/AwardedAuthors/NBA/Jones_James.jpg'),
(1, 'NBA', 'Kosinski', 'Jerzy', 'Images/AwardedAuthors/NBA/Kosinski_Jerzy.jpg'),
(1, 'NBA', 'Malamud', 'Bernard', 'Images/AwardedAuthors/NBA/Malamud_Bernard.jpg'),
(1, 'NBA', 'Matthiessen', 'Peter', 'Images/AwardedAuthors/NBA/Matthiessen_Peter.jpg'),
(1, 'NBA', 'Maxwell', 'William Keepers', 'Images/AwardedAuthors/NBA/Maxwell_William Keepers.jpg'),
(1, 'NBA', 'McDermott', 'Alice', 'Images/AwardedAuthors/NBA/McDermott_Alice.jpg'),
(1, 'NBA', 'Morris', 'Wright', 'Images/AwardedAuthors/NBA/Morris_Wright.jpg'),
(1, 'NBA', 'Oates', 'Joyce Carol', 'Images/AwardedAuthors/NBA/Oates_Joyce Carol.jpg'),
(1, 'NBA', 'O''Brien', 'Tim', 'Images/AwardedAuthors/NBA/OBrien_Tim.jpg'),
(1, 'NBA', 'O''Connor', 'Flannery', 'Images/AwardedAuthors/NBA/OConnor_Flannery.jpg'),
(1, 'NBA', 'O''Hara', 'John', 'Images/AwardedAuthors/NBA/OHara_John.jpg'),
(1, 'NBA', 'Percy', 'Walker', 'Images/AwardedAuthors/NBA/Percy_Walker.jpg'),
(1, 'NBA', 'Porter', 'Katherine Ann', 'Images/AwardedAuthors/NBA/Porter_Katherine Ann.jpg'),
(1, 'NBA', 'Powers', 'J F', 'Images/AwardedAuthors/NBA/Powers_J F.jpg'),
(1, 'NBA', 'Powers', 'Richard', 'Images/AwardedAuthors/NBA/Powers_Richard.jpg'),
(1, 'NBA', 'Proulx', 'Annie', 'Images/AwardedAuthors/NBA/Proulx_Annie.jpg'),
(1, 'NBA', 'Pynchon', 'Thomas', 'Images/AwardedAuthors/NBA/Pynchon_Thomas.jpg'),
(1, 'NBA', 'Richter', 'Conrad', 'Images/AwardedAuthors/NBA/Richter_Conrad.jpg'),
(1, 'NBA', 'Roth', 'Philip', 'Images/AwardedAuthors/NBA/Roth_Philip.jpg'),
(1, 'NBA', 'Rush', 'Norman', 'Images/AwardedAuthors/NBA/Rush_Norman.jpg'),
(1, 'NBA', 'Settle', 'Mary Lee', 'Images/AwardedAuthors/NBA/Settle_Mary Lee.jpg'),
(1, 'NBA', 'Sontag', 'Susan', 'Images/AwardedAuthors/NBA/Sontag_Susan.jpg'),
(1, 'NBA', 'Stegner', 'Wallace', 'Images/AwardedAuthors/NBA/Stegner_Wallace.jpg'),
(1, 'NBA', 'Stone', 'Robert', 'Images/AwardedAuthors/NBA/Stone_Robert.jpg'),
(1, 'NBA', 'Styron', 'William', 'Images/AwardedAuthors/NBA/Styron_William.jpg'),
(1, 'NBA', 'Tuck', 'Lily', 'Images/AwardedAuthors/NBA/Tuck_Lily.jpg'),
(1, 'NBA', 'Vollmann', 'William Tanner', 'Images/AwardedAuthors/NBA/Vollmann_William Tanner.jpg'),
(1, 'NBA', 'Walker', 'Alice', 'Images/AwardedAuthors/NBA/Walker_Alice.jpg'),
(1, 'NBA', 'Welty', 'Eudora', 'Images/AwardedAuthors/NBA/Welty_Eudora.jpg'),
(1, 'NBA', 'Wilder', 'Thornton', 'Images/AwardedAuthors/NBA/Wilder_Thornton.jpg'),
(1, 'NBA', 'Williams', 'Stoner', 'Images/AwardedAuthors/NBA/Williams_Stoner.jpg'),
(1, 'NBA', 'Williams', 'Thomas', 'Images/AwardedAuthors/NBA/Williams_Thomas.jpg'),
(1, 'PEN-Faulkner', 'Abish', 'Walter', 'Images/AwardedAuthors/PEN-Faulkner/Abish_Walter.jpg'),
(1, 'PEN-Faulkner', 'Berriault', 'Gina', 'Images/AwardedAuthors/PEN-Faulkner/Berriault_Gina.jpg'),
(1, 'PEN-Faulkner', 'Boyle', 'T Coraghessan', 'Images/AwardedAuthors/PEN-Faulkner/Boyle_T Coraghessan.jpg'),
(1, 'PEN-Faulkner', 'Bradley', 'David', 'Images/AwardedAuthors/PEN-Faulkner/Bradley_David.jpg'),
(1, 'PEN-Faulkner', 'Christensen', 'Kate', 'Images/AwardedAuthors/PEN-Faulkner/Christensen_Kate.jpg'),
(1, 'PEN-Faulkner', 'Cunningham', 'Michael', 'Images/AwardedAuthors/PEN-Faulkner/Cunningham_Michael.jpg'),
(1, 'PEN-Faulkner', 'DeLillo', 'Don', 'Images/AwardedAuthors/PEN-Faulkner/DeLillo_Don.jpg'),
(1, 'PEN-Faulkner', 'Ford', 'Richard', 'Images/AwardedAuthors/PEN-Faulkner/Ford_Richard.jpg'),
(1, 'PEN-Faulkner', 'Guterson', 'David', 'Images/AwardedAuthors/PEN-Faulkner/Guterson_David.jpg'),
(1, 'PEN-Faulkner', 'Murray', 'Sabina', 'Images/AwardedAuthors/PEN-Faulkner/Murray_Sabina.jpg'),
(1, 'PEN-Faulkner', 'Olson', 'Toby', 'Images/AwardedAuthors/PEN-Faulkner/Olson_Toby.jpg'),
(1, 'PEN-Faulkner', 'Patchett', 'Ann', 'Images/AwardedAuthors/PEN-Faulkner/Patchett_Ann.jpg'),
(1, 'PEN-Faulkner', 'Salter', 'James', 'Images/AwardedAuthors/PEN-Faulkner/Salter_James.jpg'),
(1, 'PEN-Faulkner', 'Taylor', 'Peter', 'Images/AwardedAuthors/PEN-Faulkner/Taylor_Peter.jpg'),
(1, 'PEN-Faulkner', 'Updike', 'John', 'Images/AwardedAuthors/PEN-Faulkner/Updike_John.jpg'),
(1, 'PEN-Faulkner', 'Wideman', 'John Edgar', 'Images/AwardedAuthors/PEN-Faulkner/Wideman_John Edgar.jpg'),
(1, 'PEN-Faulkner', 'Wiley', 'Richard', 'Images/AwardedAuthors/PEN-Faulkner/Wiley_Richard.jpg'),
(1, 'PEN-Faulkner', 'Wolff', 'Tobias', 'Images/AwardedAuthors/PEN-Faulkner/Wolff_Tobias.jpg'),
(1, 'PEN-Faulkner', 'Zabor', 'Rafi', 'Images/AwardedAuthors/PEN-Faulkner/Zabor_Rafi.jpg'),
(1, 'Booker', 'Adiga', 'Aravind', 'Images/AwardedAuthors/Booker/Adiga_Aravind.jpg'),
(1, 'NBCC', 'Crace', 'Jim', 'Images/AwardedAuthors/NBCC/Crace_Jim.jpg'),
(1, 'NBCC', 'Diaz', 'Junot', 'Images/AwardedAuthors/NBCC/Diaz_Junot.jpg'),
(1, 'NBCC', 'Elkin', 'Stanley', 'Images/AwardedAuthors/NBCC/Elkin_Stanley.jpg'),
(1, 'NBCC', 'Erdrich', 'Louise', 'Images/AwardedAuthors/NBCC/Erdrich_Louise.jpg'),
(1, 'NBCC', 'Flanagan', 'Tom', 'Images/AwardedAuthors/NBCC/Flanagan_Tom.jpg'),
(1, 'NBCC', 'Gaines', 'Ernest J', 'Images/AwardedAuthors/NBCC/Gaines_Ernest J.jpg'),
(1, 'NBCC', 'Gardner', 'John', 'Images/AwardedAuthors/NBCC/Gardner_John.jpg'),
(1, 'NBCC', 'Kennedy', 'William', 'Images/AwardedAuthors/NBCC/Kennedy_William.jpg'),
(1, 'NBCC', 'Lethrem', 'Jonathan', 'Images/AwardedAuthors/NBCC/Lethrem_Jonathan.jpg'),
(1, 'NBCC', 'Mukherjee', 'Bharati', 'Images/AwardedAuthors/NBCC/Mukherjee_Bharati.jpg'),
(1, 'NBCC', 'Munro', 'Alice', 'Images/AwardedAuthors/NBCC/Munro_Alice.jpg'),
(1, 'NBCC', 'Sebald', 'W G', 'Images/AwardedAuthors/NBCC/Sebald_W G.jpg'),
(1, 'NBCC', 'Shields', 'Carol', 'Images/AwardedAuthors/NBCC/Shields_Carol.jpg'),
(1, 'NBCC', 'Smiley', 'Jane', 'Images/AwardedAuthors/NBCC/Smiley_Jane.jpg'),
(1, 'NBCC', 'Tyler', 'Ann', 'Images/AwardedAuthors/NBCC/Tyler_Ann.jpg');